### ISSUE TITLE
Failed webhook targets should attempt to be revived

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1033]
### Problem description
Right now, if a POST to a webhook fails too many times, the registry sets that webhook to inactive, then when the webhook recipient (sleuther, indexer) gets restarted it'll resume itself.

_However_ it doesn't always go this way... if the pod listening for the webhooks isn't stopped at the time the webhook gets cancelled, it won't re-register itself because it won't restart.

This usually works out just because kubernetes restarts things so often, but we can't rely upon it - datasets are slipping through the cracks and not getting indexed for a week after they're published on a source.

So we need to fix this somehow - either the registry api needs to periodically retry inactive hook targets, or hook targets need to periodically re-register themselves - perhaps when they spend a few hours without any new hooks?

If it's done on the registry side it might be a problem, because we've just got a single "inactive" column which conflates hooks that have hit an error with ones that are manually deactivated. On the other hand I don't know of any hooks we've intentionally deactivated, so we could probably just rename that one and add another column for manually disabled hooks.

**Comment by t83714** [comment]
@AlexGilleran 
I think it probably would be easier to do it at enhancers / sluethers' side (as at least we can be sure there is an enhancer that is listening to the hook at the time). 
- Add a timer to `enhancer / sluether -framework` (this covers all typescript codebases) & `Indexer` that will periodically check
  - If a hook's `active` field is false in database
  - If no hook record in the database
- If any above happens, the `enhancer / sluether`will try to resume the webhook

Let me know if you have better ideas on this~

**Comment by AlexGilleran** [comment]
I guess that makes sense but it adds more requirements to sleuthers - if you wanted to go make one that wasn't written in typescript, for instance, you'd have to do that work.

Could we maybe add a "lastworking" date time column and have an exponential backoff on retries from the registry side?

**Comment by t83714** [comment]
@AlexGilleran 
I was just trying to avoid adding more logic to the registry to make it more complex 😄
To implement `exponential backoff`, we probably need another column --- let's say `retry count`?
And resume hook logic used by the sleuthers probably need to be revised as these two columns need to be properly reset?
What do you think?

**Comment by t83714** [comment]
Have a chat with Alex and we are going to do in this way:
- Add `lastRetryTime` column to indicate the last retry time
- Add `RetryCount` column to indicate how many times that registry attempt to revive the hook (i.e.  set it to Active)
- The registry will periodically (every 10 mins) get a list of all `inactive` hooks and set the `active` field to true depends on  
  - whether the hook's `lastRetryTime` is either empty or older than `current time` - 2^`retryCount` * 10 mins 
- Registry should reset `lastRetryTime` & `retryCount` columns for a hook when a hook sucessfully processed a request.

**Comment by t83714** [comment]
@AlexGilleran let's me know if you have a better idea or have any specific requirements on those pre-defined parameters (i.e. 10 mins) 😄

**Comment by AlexGilleran** [comment]
Sounds good to me :+1: :+1: :+1:
