### ISSUE TITLE
Search background button issues

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1043]
### Problem description
It's the same style as the tagline even though it's a button. It should use a cta link from the DTA Design Systems: https://designsystem.gov.au/components/cta-link/

### Screenshot / Design / File reference
![image](https://user-images.githubusercontent.com/900555/40342765-ce608584-5dcf-11e8-8f21-153ec3df03ad.png)
😿 

![image](https://user-images.githubusercontent.com/900555/40342770-d72fe880-5dcf-11e8-93be-c0be0e59a425.png)
👍 💯 🎉 🌮

**Comment by philipgrimmett** [comment]
I'd argue the "explore [x] data" wasn't designed to serve as a primary CTA, and shouldn't distract from the search bar. The DTA CTA link might be overkill in this instance. I'd suggest the following:

<img width="365" alt="screenshot 2018-09-11 15 32 34" src="https://user-images.githubusercontent.com/5292858/45339964-eb97f280-b5d7-11e8-8ba9-f154bdf3b19b.png">

**Comment by aneesha09** [comment]
Could we see how it looks on the whole page @philipgrimmett ?

**Comment by philipgrimmett** [comment]
@aneesha09 I don't have an up-to-date sketch doc that perfectly mirrors the live site, but this should do for scale:
 
<img width="1052" alt="screenshot 2018-09-11 18 24 36" src="https://user-images.githubusercontent.com/5292858/45348100-0d51a380-b5f1-11e8-90fb-9e22036c6464.png">

**Comment by aneesha09** [comment]
@philipgrimmett - I think the tiny search box it is taking too much attention. Do you think we can make the text inside the box more grey instead of purple? Not sure what would be a solution. Please suggest

**Comment by philipgrimmett** [comment]
> I think the tiny search box it is taking too much attention. Do you think we can make the text inside the box more grey instead of purple? Not sure what would be a solution. Please suggest

@aneesha09 Probably better to just make the button itself purple. There's more risk of it getting lost if the hero image isn't selected carefully, but as mentioned above I don't think it's a critical CTA so not a huge concern.

![screen shot 2018-12-05 at 5 33 25 pm](https://user-images.githubusercontent.com/5292858/49494792-f00d3800-f8b4-11e8-8f15-fbaf11a10a14.png)

**Comment by aneesha09** [comment]
With the proposed changes, it is unclear whether they will help solve the problem. Given that amid other issues, we have not received feedback to have to change this, I want to not invest further in this ticket and close it for now.

We can resurrect it if it becomes a problem again in the future.
