### ISSUE TITLE
Publishers seem out of order

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1066]
### Problem description
This is meant to be alphabetised, but there's two 'D' things before 'A'

*SUPER ALEX EDIT*
The solution here is to trim the start of organisation names such that they always start with a letter or a digit.

### Screenshot / Design / File reference
<img width="1224" alt="screen shot 2018-05-23 at 12 32 15 pm" src="https://user-images.githubusercontent.com/2201814/40400445-8084c454-5e85-11e8-9f2b-28f78f8625d9.png">

**Comment by tkeuneman** [comment]
@maxious before launch, can you go in and manually fix these two up? People are going to associate this problem with the new service, not with the space bar or the ":"

**Comment by maxious** [comment]
I've fixed the Data requests org but DFSI is NSW government and doesn't seem to be coming from data.gov.au https://data.gov.au/organization?q=Dfsi&sort=title+asc

**Comment by tkeuneman** [comment]
Can we email or call them?

**Comment by maxious** [comment]
This is the bad dataset https://sdi.nsw.gov.au/catalog/search/resource/details.page?uuid=%7B06C9D4EB-CD0C-4B43-BDA5-FCE64ED981DF%7D

Voice: 02 6332 8200
E-Mail Address: sds.services@lpi.nsw.gov.au

**Comment by maxious** [comment]
Correct or as says @AlexGilleran there needs to be a filter on our side but a colon in a name isn't necessarily bad just not at the beginning.

**Comment by tkeuneman** [comment]
Chasing it up 📞

**Comment by AlexGilleran** [comment]
Added an edit - the solution for this is going to be adding trimming to the connectors.

**Comment by t83714** [comment]
Gonna remove all non-letter (a-z,A_Z) & non-digi (0-9) characters from the beginning of a string.
This change will be done at all connectors (they are the programs to do the data crawling from different sources). Incorrect data will be updated in database (and `elasticsearch`) when next re-crawl.
