### ISSUE TITLE
remove duplicate tooltip component 

### ISSUE THREAD

**Issue by chloeleichen** [magda-io/magda#1106]
### Problem description
We have two different component doing the same thing in the UI for tooltip : 
![screen shot 2018-05-29 at 1 44 29 pm](https://user-images.githubusercontent.com/7508939/40637162-91ec80a4-6346-11e8-8b31-53208cce4b48.png)

The `Tooltip` component should be removed and all instance replaced with ReactTooltip

**Comment by adamzerella** [comment]
@chloeleichen I think we are going to transition away from `react-tooltip` and use the custom solution to avoid some problems `react-tooltip` has, like using `dangerouslySetInnerHTML`

**Comment by t83714** [comment]
We probably need an alternative option to replace `transition` CSS for this issue:  #1152

**Comment by aneesha09** [comment]
Closing it
