### ISSUE TITLE
Make filter dataset count line more obvious

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1117]
### Problem description
- Make this so it doesn't look like an underlined text
- Show the # of datasets

**Comment by philipgrimmett** [comment]
Reference image for proposed changes:

![screenshot 2018-05-29 17 48 38](https://user-images.githubusercontent.com/5292858/40645103-ab3e8602-6368-11e8-8d5f-096d5763db39.png)

The same styling should be applied to the organisation filter.

**Comment by adamzerella** [comment]
@philipgrimmett Created PR for style changes to filters. @chloeleichen Did you start implementing the 'pagination filter feature'? If not I'm happy to start it :)

**Comment by MelanieHotchkiss** [comment]
Merged
