### ISSUE TITLE
Show dataset count per organisation for organisations page

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1127]
It would be great to have the number of datasets listed under each publisher (in the same style as on the datasets results page). Please make this clickable so you land on the results with the organisation as the filter.

Reference:

<img width="1278" alt="org-reference" src="https://user-images.githubusercontent.com/5292858/40757860-e2cb6a34-64cd-11e8-90e5-b1377842fdc5.png">

**Comment by t83714** [comment]
Disconnect because I incorrectly connected my PR to this.
Was supposed to connect to the other one, not this

**Comment by t83714** [comment]
merged into master via:
https://github.com/magda-io/magda/pull/1255
