### ISSUE TITLE
Search page automatically searches for * if you backspace everything and hit enter on home page

### ISSUE THREAD

**Issue by steve9164** [magda-io/magda#1144]
### Problem description
Search page automatically searches for * if you backspace everything

### Problem reproduction steps
1. Search from something
1. On the results page, backspace the search query
1. Search will automatically run and add a '*' in a few seconds

**Comment by steve9164** [comment]
This is almost fixed, but still occurs from the search bar on the front page.

**Comment by AlexGilleran** [comment]
Can't reproduce anymore
