### ISSUE TITLE
Reword 'no datasets' alert to accurately reflect content below

### ISSUE THREAD

**Issue by philipgrimmett** [magda-io/magda#1145]
### Problem description
Currently when no datasets are found we display the following alert text:

> **Sorry, we couldn't find any datasets that match your search query.**
> *Try another search, request a new dataset , or have a look at these great datasets*

We then display a number of news cards, not datasets, that could be interpreted as search results.

### Proposed solution

- Remove "or have a look at these great datasets" from alert text
- Display header "Featured articles" above news content (Featured/Recent/...?, news/articles/...?)

### Problem reproduction steps

Search for "jojojojojojoj" 
View alert

### Screenshot / Design / File reference

<img width="363" alt="screenshot 2018-06-05 15 02 17" src="https://user-images.githubusercontent.com/5292858/40956069-8893deae-68d1-11e8-9d52-9220adca6b7b.png">

**Comment by stephencannings** [comment]
I understand now to have a friendly error graphic.

**Comment by tkeuneman** [comment]
Text: Please try a different search term or check your spelling, alternatively, request a dataset

**Comment by stephencannings** [comment]
Text: Please try a different search term or check your spelling, or you can [request a dataset].

There's a push here to 'plain English', fewer syllables...

**Comment by tkeuneman** [comment]
Minor edit: Please try a different search term, check your spelling, or you can [request a dataset].
