### ISSUE TITLE
Tooltip delay is missing on desktop and doesn't go away on mobile

### ISSUE THREAD

**Issue by adamzerella** [magda-io/magda#1152]
### Problem description
DatasetDetails tooltip should have a 1 second delay (or something) so the use can click on the link inside of it. The delay appears correctly when using the Chrome mobile emulation but fails on the `real stuff` (Apple). Android seems ok

### Problem reproduction steps
On the dataset results page, hover over tooltip

### Screenshot / Design / File reference
<img width="665" alt="screen shot 2018-06-05 at 3 30 25 pm" src="https://user-images.githubusercontent.com/1501560/40956807-7cc030d8-68d5-11e8-98e2-5bc303c5c1f8.png">

**Comment by adamzerella** [comment]
It seems that the actual CSS property: `transition` isn't properly supported on mobile: 

![image](https://user-images.githubusercontent.com/1501560/41570846-d3867f06-73b3-11e8-9854-3d183b126a98.png)

Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/transition

**Comment by AlexGilleran** [comment]
Fixed by the grand tooltip unification.
