### ISSUE TITLE
`Ask a question about this dataset` button (on dataset page) won't open form on safari browser

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#1155]
### Problem description

`Ask a question about this dataset` button (on dataset page) won't open form on safari browser

### Problem reproduction steps

Click `Ask a question about this dataset` button

### Screenshot / Design / File reference
![image](https://user-images.githubusercontent.com/674387/40957128-047e86f4-68d7-11e8-81f9-da96dfca92ca.png)

**Comment by adamzerella** [comment]
@AlexGilleran @t83714 Not sure what happened here but this issue has been resolved, I made a branch but it was deleted, and merged? `issue/1155-Dataset-request-form-open-on-safari`.

On master, the file `DatasetSuggestForm.scss` contains the fix on line 6: `overflow-y: scroll;`

**Comment by t83714** [comment]
Had another try on Dev site and it works now.
I think it can be closed as it's fixed already on master

**Comment by t83714** [comment]
![image](https://user-images.githubusercontent.com/674387/42198207-faa93f3a-7ec9-11e8-9ebc-37dfd8f00628.png)

It looks like this issue is coming back.

Just checked now:
https://dev.magda.io/dataset/ds-dga-ab7eddce-84df-4098-bc8f-500d0d9776d1/details?q=*

**Comment by adamzerella** [comment]
@t83714 It seems that my branch was never merged? `issue/1155-Dataset-request-form-open-on-safari` contains the fix and it was not yet applied on master...?

On *master* the file `DatasetSuggestForm.scss` has the problem `overflow: -webkit-paged-y`, it should be `overflow: scroll`.

**Comment by t83714** [comment]
@adamzerella Would you mind re-create another PR?
The previous one probably has lost somehow.
