### ISSUE TITLE
Search for organisations - UI

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1175]
### Problem description
When on the Organisations page, I want to be able to search for my organisation, or the organisation that I trust
- [x] Search bar, new UI
- [x] Search only for organisations
- [x] Pagination for organisations page

### Screenshot / Design / File reference
Invision prototype:
https://invis.io/EUKEL58ZCKF#/301745243_organisation_Search_1

![img_20180606_134124](https://user-images.githubusercontent.com/2201814/41015912-b52862c8-698f-11e8-8a33-f623ae93d7a6.jpg)

**Comment by tkeuneman** [comment]
Mock ups are in this Invision prototype:
https://invis.io/EUKEL58ZCKF#/301745243_organisation_Search_1

If you are unable to access this, contact @philipgrimmett

**Comment by chloeleichen** [comment]
UI: https://github.com/TerriaJS/magda/tree/org-search-ui

**Comment by t83714** [comment]
@chloeleichen 
@adamzerella & I created a PR for the backend API here:
https://github.com/TerriaJS/magda/pull/1226
You can find out the API spec from the PR description.
It's now processing in gitlab. 
Once it's completed, I'll create a testing backend on Gitlab for your testing (and send you the URL)

**Comment by t83714** [comment]
close this as 
https://github.com/magda-io/magda/pull/1255
has been merged Plus we have other issue for tracking new org page development
