### ISSUE TITLE
Content for Homepage cards

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1185]
### Problem description
The current content is dummy content
- [ ] Create content around who this site is for, how they can use it
- [ ] Create content about an intro to MAGDA/new DGA
- [x] Decide where the content is going to live. e.g. Medium, old DGA etc.

**Comment by stephencannings** [comment]
Mock of Homepage content - 
[](https://vi1y65.axshare.com)

Content can be hosted on existing datagovau cms.

- [ ] Does 61 have how-to content for magda?

**Comment by stephencannings** [comment]
Aiming for thus THUR

**Comment by stephencannings** [comment]
Content list is
-(1) Blog post
-(2) Story - IP Nova
-(3) Story - NationalMap
-(4) OD intro [About Open Data]
-(5) Datacard

(1) needs to be published on DTA site. They own the content, will confirm turnaround time
(2-4) published on blog.data, will be quicker
(5) image and text, linking to TBD (either direct or blog.data page)

Issue: as the site is live we shouldn't have draft copy online until approved and published.

**Comment by stephencannings** [comment]
@tkeuneman Request login or creation of sandbox site to add teaser text and images to magda home page.

**Comment by tkeuneman** [comment]
Yup @stephencannings, once you give us the homepage copy and imagery, we can put this ticket in PR and then you'll have a link you can share.

**Comment by stephencannings** [comment]
PLACEHOLDER CONTENT (see screenshot below)

BOX1

Communities of practice

This community is for people who work with public data in the Australian Public Service or who carry out publicly funded research.

It’s also for people who develop, innovate or carry out research using Australia’s public datasets.

Our communities of practice bring together our government colleagues to collaborate, showcase work, solve problems and explore best practice.

------

BOX2

About open data

What is open data, who can use and how does it benefit Australians.

Join the open data community

------

BOX3

Open data makeover more than skin deep

People might assume the Digital Transformation Agency (DTA) is all about building new things. But working to best practice principles isn’t just about the shiny, it’s also putting some polish on important, existing online services. 

Now that open data is normal, and government agencies are required to make non-sensitive data open by default, we've worked with our partners Data61 to make it easy to find, explore and reuse Australia's public data.

------

BOX4

Data snap: Breeds in Ballarat
Ballarat council area residents can see what pooch is popular in their neighbourhood

------
BOX5

Explore the NationalMap

The NationalMap is a visualisation tool for Australia’s public data. The purpose is simple: to make geospatial data easy to use and explore. 

-------

BOX6

IP data – now intuitive, visually

IP Australia has a wealth of Intellectual Property data. But with over 40 relational tables it would make a data expert shake in their boots. 

-------

GUIDE
![image](https://user-images.githubusercontent.com/39356390/42196676-9671c53e-7ec2-11e8-9833-38a924277bbb.png)

IMAGES (more to come)
![thumb-ipnova](https://user-images.githubusercontent.com/39356390/42196896-969000e8-7ec3-11e8-8f14-c7081ad86a33.png)


![](https://files.slack.com/files-pri/T07T00WSE-FBG5E4S5Q/data-image.png)

**Comment by stephencannings** [comment]
![data-image](https://user-images.githubusercontent.com/39356390/42196922-b58a921a-7ec3-11e8-8db1-e3c8cd43bedc.png)

**Comment by stephencannings** [comment]
@tkeuneman I'll have images and links next week.

**Comment by tkeuneman** [comment]
Just an accessibility thing @stephencannings, we can't have text in a jpeg or png as people with screen readers can't access them: https://github.com/magda-io/magda/issues/1185#issuecomment-402001116

**Comment by stephencannings** [comment]
@tash, the solution is alt text = description, _or_ alt text = null (when no additional meaning, such as when its repeated underneath the image).

The DTA do it all the time here with (alt=""')
https://www.dta.gov.au/

**Comment by tkeuneman** [comment]
Good to know!

**Comment by stephencannings** [comment]
Ok, an update. Yet to publish to blog.data, just a technical difficulty to be resolved as soon as possible. Images due any moment now too. May not have ready by today's sprint.
