### ISSUE TITLE
Landing page for MAGDA

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1207]
### Problem description
So that we can point to it at launch
To make it more user-friendly for people who want to learn more about MAGDA

### To do
- [ ] Add logo to the top half
- [ ] Add stats to the top half (e.g. contributor count, commit counts, other stuff that's cool)
- [ ] Create a contribute CTA button
- [ ] Link back to MAGDA repo

**Comment by tkeuneman** [comment]
Blocked by my lack of coding skillz

**Comment by tkeuneman** [comment]
What I'm up to: https://magda-io.github.io/docs/

@AlexGilleran I'm gonna need some finesse on this

**Comment by AlexGilleran** [comment]
https://magda.io !
