### ISSUE TITLE
Search results pagination

### ISSUE THREAD

**Issue by CelineBrewster** [magda-io/magda#1220]
### Problem description

The pagination on search results seems confusing.
![image](https://user-images.githubusercontent.com/40256383/41394067-e38dcb82-6feb-11e8-85cc-5067693e5318.png)

The "1" and "..." buttons take up a lot of space without adding a lot of benefit (eg: a link to the first record would remove the need for both those buttons).

Also, it's not clear what clicking the "..." button should do, and when I do click on it it's not obvious what has happened.

### Problem reproduction steps
 - Search for "NSW"
- Navigate to page 7
- View the pagination at the bottom of the screen

### Screenshot / Design / File reference

Possibly something like this could be easier to understand:
![image](https://user-images.githubusercontent.com/40256383/41394064-d602b0e0-6feb-11e8-8c21-48b55a619bd9.png)

**Comment by t83714** [comment]
The `...` will take you to `current page - 4`
It's same as Microsoft bing search engine pagination behaviour.
More details (on this behaviour) can check this issue #557 --- the last comment

**Comment by AlexGilleran** [comment]
@tkeuneman did we have this for the last round of user testing? The concerns in the issue make sense, but if it's working OK I'm inclined to leave it as is :).

**Comment by aneesha09** [comment]
Closing this as we can live with it right now
