### ISSUE TITLE
"Ask a Question About a Dataset" modal doesn't work on small screens

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1223]
### Problem description
If you tap the "Ask a question about a dataset" button, the resulting modal is too big to fit on my phone's screen (Iphone SE). Because you can't see the X button or the submit button there's no way to even close the modal, let alone send it.

I think the modal needs scrollbars.

### Problem reproduction steps
Go to any dataset page and tap "Ask a question about a dataset"

**Comment by sukhrajghuman** [comment]
@AlexGilleran Are you using chrome? I'm not getting the same thing using iPhone 5 on chrome. I think the height can be reduced though and have some padding to both left and right.

![image](https://user-images.githubusercontent.com/20184809/41446135-282f6b06-7091-11e8-84c4-29c73640900e.png)

it's similar size as the filter search box thingy on mobile. Though I notice the overlay is a little bit weird for mobile.
![image](https://user-images.githubusercontent.com/20184809/41446219-a360c89c-7091-11e8-8321-d3c8b51d586b.png)

**Comment by sukhrajghuman** [comment]
**can do something like this:**
---
![image](https://user-images.githubusercontent.com/20184809/41446581-bfe984c0-7093-11e8-8be6-849e9b5de273.png)

---
**or for reduced height with a scroller:**

![mobilemodal](https://user-images.githubusercontent.com/20184809/41446604-e783a95c-7093-11e8-9f16-f879e1d8a356.gif)

**Comment by sukhrajghuman** [comment]
okay so this is the problem. The file type names weren't wrapped which screws it up.
               
![image](https://user-images.githubusercontent.com/20184809/41452931-4a387168-70b7-11e8-8e5e-9f06f4cfba31.png)


![image](https://user-images.githubusercontent.com/20184809/41452976-6eb61e0a-70b7-11e8-875c-736441d10ef8.png)

**Comment by sukhrajghuman** [comment]
fixed by #1318 #1253
