### ISSUE TITLE
Upgrade `elastic4s` to 6.2.9 & `elasticsearch` to 6.2.4

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#1224]
### Problem description

PR https://github.com/TerriaJS/magda/pull/1128 includes two features:
- supports synonyms
- a new way of processing quoted search string

The second item requires the `quote_field_suffix` of `simple_query_string` of `elasticsearch`.
Unfortunately, our upstream library `elastic4s` current version '5.6.0' has a bug with TCP client DSL builder, which will ignore this field.

To fix this issue, we will need:
- switch to `elastic4s` HttpClient
- Upgrade `elastic4s` to 6.2.9 as the lower versions HttpClient has incomplete DSL support
- Upgrade `elasticsearch` to 6.2.4 as `elastic4s` requires 6.x versions `elasticsearch`

Created a new branch https://github.com/TerriaJS/magda/tree/feature/es-http-changeover for the changes required. Currently, still in progress.

Task list:
- [x] Upgrade `elasticsearch` to ~~6.2.4~~( upgraded to 6.3.0 due to nested term agg bug) & make sure it works in kubernates cluster
- [x] Upgrade `elastic4s` to 6.2.4
- [x] Change incompatible `elastic4s` DSL usage in scala codebase (HttpClient DSL support is slightly different)
- [x] Change incompatible usage between Tcp client `RichSearchResponse` and Http`SearchResponse`
- [x] Create a new index for Publisher as `elasticsearch` 6.x doesn't support different types document in signle index
- [x] Solve any issue with above index changes 
- [x] Merged lastest master
- [x] Test Search API to make sure it still sends same JSON request to elasticsearch
- [x] Merged with newly created search organisation API

**Comment by t83714** [comment]
The development is on this branch:
https://github.com/magda-io/magda/tree/feature/es-http-changeover

**Comment by AlexGilleran** [comment]
Merged
