### ISSUE TITLE
 /about page content

### ISSUE THREAD

**Issue by stephencannings** [magda-io/magda#1233]
### Problem description
Content on the /about page needs to be fact & sense checked
https://search.data.gov.au/page/about

@maxious, @tkeuneman can you help?

### Content Issues
1) 
TEXT: "Before you begin, do a **quick search** of existing organizations to see if your own agency is already listed. If they are, **the listed contact can help you** to log in and publish your data sets. If not, you can register for the first time."

ISSUE
- What is the (intended) search method for the /organisations page?
- Where do you find an organisation's listed contact?

2) 
TEXT: "Enter this information to create your account. You will be redirected to your profile page. To set up your profile, select 'Manage'. It is important you fill out your profile completely, including your agency’s logo as your account image. "

ISSUE
- Is this accurate and clear instruction for new signups?

3) 
TEXT: "Subscribe to the new datasets feed or customise a feed below: [Groups](https://data.gov.au/feeds/group/), [Tags](https://data.gov.au/feeds/tag/) or [Search](https://data.gov.au/feeds/custom.atom?q=)."

ISSUE
- 2 of 3 broken. What is our content strategy with RSS as a channel? Retire or repair the broken? Have only one feed. Retire all? 

Many thanks. Any questions please ask?

Stephen

**Comment by stephencannings** [comment]
Yes, Tash. I am re-drafting this page. As you don't need to implement changes we can take it across to Asana. I'll do that now. Guess you can close...

**Comment by tkeuneman** [comment]
Thanks @stephencannings !!!

Closing as moving content editing to DTA Asana.
