### ISSUE TITLE
Only link text is clickable in hamburger items (mobile)

### ISSUE THREAD

**Issue by steve9164** [magda-io/magda#1237]
### Problem description
In most mobile hamburger menus anywhere in the bar can be pressed. On magda only the link text is clickable.

### Problem reproduction steps
1. Open hamburger on mobile
1. Try to press somewhere in the list items other than exactly on the link text

### Screenshot / Design / File reference
![image](https://user-images.githubusercontent.com/13863530/41577784-2cde5c68-73d2-11e8-8af5-e03014e7a54c.png)

**Comment by AlexGilleran** [comment]
Resolved by https://github.com/magda-io/magda/pull/1381
