### ISSUE TITLE
Date filter text boxes should default to number input

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1242]
### Problem description
If you go inside a text box in the date filter on a phone, the keyboard that comes up is for text. We should set the `type` attribute on the `input` so that it comes up with numerals.

### Problem reproduction steps
Open magda on a phone, go to search, open the date filter, go into one of the text boxes.

**Comment by aneesha09** [comment]
Currently 2% of our users come from mobile and this functionality is a minor inconvenience. We don't need to fix it.
