### ISSUE TITLE
Ask a question form on Pixel

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1243]
### Problem description
I can't see the exit arrow and can't click on the email or name form fields. The description form field is fine.
The feedback button hides the 'send' button, but that should be fixed once it's removed.

### Problem reproduction steps
Try it on a Pixel (Unable to reproduce with Samsung)

### Screenshot / Design / File reference
![screenshot_20180619-145607](https://user-images.githubusercontent.com/2201814/41578052-aff70e28-73d3-11e8-8527-25afd27bf8f9.png)

**Comment by sukhrajghuman** [comment]
@tkeuneman I believe #1240 will remove the feedback button from mobile.

I've updated the suggest modal on #1253 can you see it please

**Comment by AlexGilleran** [comment]
Resolved by removing the feedback button on mobile.
