### ISSUE TITLE
Dataset feed links: group, tags and search are 404

### ISSUE THREAD

**Issue by adamzerella** [magda-io/magda#1245]
### Problem description
These links have died!

### Problem reproduction steps
Go to -> https://search.data.gov.au/page/about, scroll to bottom and click on `Groups`, `Tags` or `Search` links.

### Screenshot / Design / File reference
# Magda
![image](https://user-images.githubusercontent.com/1501560/41578099-e1795e92-73d3-11e8-972b-e614a40480b0.png)

# data.gov.au
![image](https://user-images.githubusercontent.com/1501560/41578114-f11beee6-73d3-11e8-9da6-6ea110d4001a.png)

# :(
![image](https://user-images.githubusercontent.com/1501560/41578129-fcb844a2-73d3-11e8-9878-2b0e109739ea.png)

**Comment by chloeleichen** [comment]
Fixed in https://github.com/magda-io/magda/pull/1420
