### ISSUE TITLE
Replace X on feedback form

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1247]
### Problem description
- [ ] It needs a clearer X and it looks quite thin

### Problem reproduction steps
Look on any device

### Screenshot / Design / File reference
![screenshot_20180619-153330](https://user-images.githubusercontent.com/2201814/41578564-4f545c80-73d6-11e8-95a4-7ab05da8ae86.png)

**Comment by sukhrajghuman** [comment]
@tkeuneman can you plz see #1253 . I've made changes to this form. Let me know if the new x button is okay. I can probs still make it thicker
