### ISSUE TITLE
"State Library of Queensland - Digitised maps" dataset chart error

### ISSUE THREAD

**Issue by MelanieHotchkiss** [magda-io/magda#1249]
### Problem description
Internet Explorer - on the "State Library of Queensland - Digitised maps" dataset chart axis data is displaying an error

### Screenshot / Design / File reference
![image.png](https://images.zenhubusercontent.com/5ac7000f4b5806bc2bcde19f/96b55a36-cb08-49ee-b0dc-4f65cfdb4f4a)

**Comment by t83714** [comment]
@MelanieHotchkiss 
Saw this dataset a while ago as well.
It turns out that's the actual data of the file. 
see screenshot below:
![image](https://user-images.githubusercontent.com/674387/41579154-120d2430-73d9-11e8-9c42-1aeb76d43e2a.png)

**Comment by t83714** [comment]
Close this issue as PR https://github.com/magda-io/magda/pull/1434 has been merged.
No chart will be shown for this dataset at this moment.

**Comment by aneesha09** [comment]
@t83714 - Does this fix the issue of HTML injection as well? That is a vulnerability and we need to fix it if it is still happening. Could you kindly confirm?

**Comment by t83714** [comment]
@aneesha09 
The reason I close it is I think we'd better make sure every issue is:
- `pure`: only about one topic
- reproducible: this one currently cannot be easily reproducible on master test site
However, I re-construct a new test chart locally. Seems chart part is no html injection issue (`html injection` issue doesn't mean you can't display html tag but you should remove its function on page (e.g. <b> should not bold font and just show a <b>) or remove some insecure tag e.g. script):
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/674387/44758024-68a57f80-ab75-11e8-86aa-5ddee9ccd6e4.png">
- The data `harvesting process` issue is hard to re-produce (we will need another similar case)
However, if you want, I can create seperate issue for that
