### ISSUE TITLE
UX: Mobile menu needs some love

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1250]
### Problem description
- [ ] You can't click anywhere on the line to select the page
- [ ] It's hard to see what page you're on, there's no selected state
- [ ] It could do with a bit of visual love. No longer fits in with design language.

### Screenshot / Design / File reference
![screenshot_20180619-154033](https://user-images.githubusercontent.com/2201814/41578800-5b4ca3fc-73d7-11e8-8ae4-e2f5ff0fc6bc.png)

**Comment by QuadTog** [comment]
FYI: 60% of Data.gov.au users use Apple Products, 30% Samsung.

**Comment by tkeuneman** [comment]
Sweet, thanks @QuadTog

**Comment by philipgrimmett** [comment]
Proposed design:
![menu-v2](https://user-images.githubusercontent.com/5292858/42251576-7ca3c2ec-7f7b-11e8-83da-c1a7ed1b8382.png)

**Comment by tkeuneman** [comment]
@philipgrimmett we can move this to done now, right?
