### ISSUE TITLE
Chart Preview: Chart Type, Column selection panel is hidden on mobile version

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#1251]
### Problem description

Chart Preview: Chart Type, Column selection panel is hidden on the mobile version

We probably want to show the panel on the bottom of the chart or on top of the chart area as it provides some background information for the chart.

### Screenshot / Design / File reference

As shown below, the selection panel is available on desktop version but hidden on mobile version:

![image](https://user-images.githubusercontent.com/674387/41579001-56c92a7a-73d8-11e8-829e-1c3711ac4654.png)

**Comment by AlexGilleran** [comment]
Will be handled by https://github.com/magda-io/magda/issues/1387
