### ISSUE TITLE
Dataset page: Replace licenses for files and APIs with descriptions.

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1257]
### Problem description
License information has been moved to the distribution page, so omit it from the dataset Files and APIs.
But CKAN resources have descriptions, show a similar length snippet to eg. http://data.gov.au/dataset/taxation-statistics-2014-15/

### Screenshot / Design / File reference
https://user-images.githubusercontent.com/2201814/41146498-e8160272-6b46-11e8-9706-6e333189b919.png

**Comment by aneesha09** [comment]
We can live with this for now
