### ISSUE TITLE
Dataset download URL reporting as broken

### ISSUE THREAD

**Issue by QuadTog** [magda-io/magda#1269]
Datasets are reporting their download link as broken when it isn't.

Navigate to a dataset: https://search.data.gov.au/dataset/ds-nsw-6e653cf4-27f9-4c70-9c32-cea8910ea0e4/distribution/dist-nsw-08b23381-4cda-495e-a48e-027aeddd2fc1/details?q=water

> Download
> This dataset can be downloaded from: 
> https://spatial.industry.nsw.gov.au/arcgis/rest/services/PUBLIC/Water_Sharing_Plan_Surface_Water_Sources/MapServer(This link appears to be broken)
> 

![image](https://user-images.githubusercontent.com/20583588/41640758-2ba98f8c-74a6-11e8-92e9-da7a2d5a5ca8.png)

Link isn't broken: https://spatial.industry.nsw.gov.au/arcgis/rest/services/PUBLIC/Water_Sharing_Plan_Surface_Water_Sources/MapServer

**Comment by AlexGilleran** [comment]
Might be resolved by https://github.com/magda-io/magda/issues/1039, which we should really get around to.

**Comment by aneesha09** [comment]
This is fixed waiting for deployment

**Comment by AlexGilleran** [comment]
No longer broken 🎉
