### ISSUE TITLE
RecordHandler.js has too many resposibilities, often leading to URL encode bugs with ids

### ISSUE THREAD

**Issue by steve9164** [magda-io/magda#1273]
### Fixing this for good 🎉 🌈 💯 
This type of issue (problems with URL-like dataset ids) has occurred 3 times. We need a strategy to stop these regressions.

### Suggestions
- Move all dataset/distribution id ↔ URL transformations (for both UI URLs and registry URLs) into one JS file which hopefully doesn't need to be changed as often as the presentational code that the transformations are currently mixed into.

**Comment by steve9164** [comment]
PR #1274 fixes this, or at least change the priority from `release-blocker` to `low` (and it'll no longer be a `bug`).

**Comment by aneesha09** [comment]
@steve9164 - Can we close this?

**Comment by steve9164** [comment]
I think it's still a likely source of future bugs, but there's none that I currently know of. It's probably not likely to be a priority to fix any time soon. So maybe it should be closed.
