### ISSUE TITLE
Correct labels for axes on chart menu

### ISSUE THREAD

**Issue by stephencannings** [magda-io/magda#1278]
Change drop-down names to plain English, ie. X axis, Y axis 

![ballarat_bbq_s_data_gov_au](https://user-images.githubusercontent.com/40556131/44383439-1accbe00-a55c-11e8-9f17-b329ccf241f6.png)

**Comment by tkeuneman** [comment]
Adding to backlog! 👍

**Comment by stephencannings** [comment]
Ok, fair enough, though I cannot see the labels as such. I was wondering if there is another way to convey the information, such as a tooltip....?
