### ISSUE TITLE
Clicking "Suggest a new dataset" button in search results changes title to "Undefined"

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1279]
### Problem reproduction steps
- Go to search results (e.g. http://magda-dev.terria.io/search)
- Click on "Suggest a new dataset"
![image](https://user-images.githubusercontent.com/900555/41754493-ddfc71b6-7615-11e8-9910-c4b66e66403a.png)
- Note the page title:
![image](https://user-images.githubusercontent.com/900555/41754501-e6b2fece-7615-11e8-9f04-d911f5f5ab8b.png)

**Comment by sukhrajghuman** [comment]
will be solved with #1316
