### ISSUE TITLE
Database queries used by `/sitemap` drive DB usage to 100%

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1282]
### Problem description
Over the weekend we got a lot of automated traffic to `/sitemap` routes, which caused the database usage to go up to 100% and stay there.

Hypothesis 1:
There's a number of places where the registry uses `COUNT(*)`, which is bad https://dba.stackexchange.com/questions/184685/why-is-count-slow-when-explain-knows-the-answer.

These statements are getting logged by Google Cloud SQL, which I presume means they're executing really slowly.

Either way we should change them to `COUNT(id)`

**Comment by maxious** [comment]
That question is about MySQL btw, the PostgreSQL solutions including autosample are great! https://stackoverflow.com/questions/7943233/fast-way-to-discover-the-row-count-of-a-table-in-postgresql

**Comment by AlexGilleran** [comment]
🤔 interesting thanks.
