### ISSUE TITLE
Data Preview doesn't size properly.

### ISSUE THREAD

**Issue by QuadTog** [magda-io/magda#1284]
Data Preview doesn't size correctly. Resizing the window causes the user to lose Chart functionality/picker.

Go to a dataset. Say: https://search.data.gov.au/dataset/ds-dga-29128ebd-dbaa-4ff5-8b86-d9f30de56452/details?q=

Snap your browser to the left/right. Watch as the Data Preview shifts across but the 'Picker' disappears until you maximise again.

**Comment by AlexGilleran** [comment]
Will be resolved by #1387 :)
