### ISSUE TITLE
Sitemap times out if input is invalid

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1294]
### Problem description
If you hit the the sitemap with invalid input (e.g. /sitemap/dataset/afterToken/abc), it should return a 400, but instead it just times out. I suspect this is because it uses `end` instead of `send` in express. Should be an easy fix.

### Problem reproduction steps
Hit `/sitemap/dataset/afterToken/abc`. Note that nothing comes back until a gateway timeout.

**Comment by t83714** [comment]
Changed the `end` to `send` seems still have the timeout issues.
It seems the registry API client will re-try (and wait for 10s) for a couple times before throwing an error.
Planned to reduce the maxRetry times to 0 for sitemap function.
@AlexGilleran Let me know if you have a better idea

**Comment by AlexGilleran** [comment]
Makes perfect sense to me 👍
