### ISSUE TITLE
Filter icons and text not being centered

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1296]
### Problem description
Make sure that for each filter button, the text and icon is centered together (vertically aligned) then smack bang in the middle of the button.

It makes the human eye feel slightly confused.

### Screenshot / Design / File reference
![Screen Shot 2018-06-26 at 3.46.57 pm.png](https://images.zenhubusercontent.com/5a5b31cc4b5806bc2bc2a818/f7d9d2c6-1b6c-4b52-9efa-a6001010d7a4)

**Comment by harshyadav9** [comment]
can i pick up this issue ?

**Comment by tkeuneman** [comment]
OK! Send us a PR 👍

**Comment by chloeleichen** [comment]
@harshyadav9 are you working on this issue? Cheers!

**Comment by harshyadav9** [comment]
@chloeleichen no i am not working on the issue.

**Comment by chloeleichen** [comment]
@tkeuneman can you be a bit more specific, they look pretty aligned to me...
<img width="693" alt="screen shot 2018-07-04 at 4 28 05 pm" src="https://user-images.githubusercontent.com/7508939/42260340-5ceec24a-7fa7-11e8-8823-b173931b2a02.png">

**Comment by tkeuneman** [comment]
![screen shot 2018-07-04 at 4 33 08 pm](https://user-images.githubusercontent.com/2201814/42260493-ffe8545c-7fa7-11e8-8936-a53fcd6742f3.png)

It's 9px padding at the top and 13px at the bottom.
