### ISSUE TITLE
Omit filters from mobile

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1302]
### Problem description
There's a usability problem because the filters are an accordion that turns into modal dialog that then has search. It adds three or four layers. 

We'll hide the filters from mobile search for now and replace it with new designs as covered by: https://github.com/magda-io/magda/issues/1244

**Comment by AlexGilleran** [comment]
@tkeuneman what should it look like when a mobile user goes from the organisation page to search via the "Find datasets for this organisation" link?

**Comment by AlexGilleran** [comment]
... or if someone follows a link that has filters - we need to have some way to show that they're active and clear them.

**Comment by AlexGilleran** [comment]
Merged into https://github.com/magda-io/magda/issues/1447
