### ISSUE TITLE
Cannot set Location Filter from Location Filter Panel

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#1303]
### Problem description

Can reproduce this problem on: https://dev.magda.io/

Production site works OK.

### Problem reproduction steps

Try to select any region, you will get the following error (and nothing happen): 

### Screenshot / Design / File reference
![image](https://user-images.githubusercontent.com/674387/41896064-fd253b6e-7966-11e8-9762-6b647766021d.png)

**Comment by adamzerella** [comment]
@t83714 Was able to reproduce this yesterday on dev and local but today it seems that this specific problem is resolved. I can generate another error similar error though:

![image](https://user-images.githubusercontent.com/1501560/42068995-7fe41eb2-7b92-11e8-85a3-205d986ab8d0.png)

To reproduce this, simply scroll out faster than the tile images can refresh, seems that rollbar and the served content tiles aren't in sync causing null pointers randomly.  

Unrelated: I've put in a PR upgrading `basemaps.cartocdn.com` to https, I also think we should upgrade rollbar to `2.4.1` as we'll get better server error handling: https://github.com/rollbar/rollbar.js/releases/tag/v2.4.1

**Comment by AlexGilleran** [comment]
Closed for now in the hope that @adamzerella resolved it, will reopen if it's seen again.
