### ISSUE TITLE
Change tagline on homepage

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1313]
### Problem description
Replace tagline on homepage from: An easy way to find, access and reuse public data
to: An easy way to find, explore and reuse Australia's public data

This is a request from @stephencannings for the launch

### Screenshot / Design / File reference
![screen shot 2018-06-27 at 5 02 33 pm](https://user-images.githubusercontent.com/2201814/41957955-ec9a16d2-7a2b-11e8-812d-392bf5447605.png)

**Comment by adamzerella** [comment]
#1314 Was merged
