### ISSUE TITLE
Cannot click out of filters on iOS

### ISSUE THREAD

**Issue by steve9164** [magda-io/magda#1342]
### Problem description
It's impossible to close the organisation filter on iOS without applying the filter, and currently impossible to apply a filter due #1338.

There's also something weird happening with scrolling while on the filter making the search results behind scroll.

### Problem reproduction steps
1. Search for something on iOS
1. Open the organisation filter

**Comment by AlexGilleran** [comment]
Will be dealt with by https://github.com/magda-io/magda/issues/1302
