### ISSUE TITLE
CSV-GEO-AU is not recognised as a map in distribution page

### ISSUE THREAD

**Issue by steve9164** [magda-io/magda#1347]
### Problem description
CSV-GEO-AU is recognised as a map format on the dataset page, but is recognised only as a csv on the distribution page. On the distribution page the icon should be a map icon and the preview should be either just a map, or a map and the chart/table preview

### Problem reproduction steps
1. Go to a dataset that has a CSV-GEO-AU format distribution
    **Notice the correct map icon on the dataset page**
1. Click on the CSV-GEO-AU distribution

### Screenshot / Design / File reference

Dataset page:
![image](https://user-images.githubusercontent.com/13863530/42199320-38b87212-7ed1-11e8-8531-59c263a54f7d.png)

----

Distribution page:
![image](https://user-images.githubusercontent.com/13863530/42199194-7a9f1394-7ed0-11e8-86ac-526206ad71a2.png)

**Comment by t83714** [comment]
related #3177

**Comment by t83714** [comment]
fixed in PR: https://github.com/magda-io/magda/pull/3180
the map view is turned on distribution page

**Comment by t83714** [comment]
relevant ticket: https://github.com/magda-io/magda/pull/3180
