### ISSUE TITLE
Scala services reflect input parameters.

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1349]
### Problem description
The following routes, when passed an invalid parameter, will return that parameter as part of the response, therefore (maybe) opening us up to XSS attacks:

- [x]  /api/v0/registry/records [limit parameter] 
- [x] /api/v0/registry/records/ds-aodn-463f1924-7b41-4f52-882e-bbd45ecb37dc [dereference parameter] 
- [x] /api/v0/registry/records/ds-dga-5076fbb3-4cbb-47f4-9121-8e8207744f4b [dereference parameter] 
- [x] /api/v0/registry/records/ds-dga-5076fbb3-4cbb-47f4-9121-8e8207744f4b [script XML parameter within the dereference parameter]
- [x] /api/v0/registry/records/ds-dga-9744f475-4205-439b-b69f-43f3ce1b8827 [dereference parameter] 
- [x] /api/v0/registry/records/ds-dga-ab7eddce-84df-4098-bc8f-500d0d9776d1 [dereference parameter] 
- [x] /api/v0/registry/records/ds-dga-b748174a-e150-4f79-bb56-47e3f4d1b222 [dereference parameter] 
- [x] /api/v0/search/datasets [limit parameter]
- [x] /api/v0/search/datasets [start parameter]
- [x] /api/v0/search/facets/format/options [limit parameter]
- [x] /api/v0/search/facets/format/options [start parameter]

These need to return error messages that don't include the input passed to them.

![image](https://user-images.githubusercontent.com/900555/42200025-d0675314-7ed4-11e8-9738-c3d56880c00f.png)

**Comment by t83714** [comment]
Updated the note format (to a task list) for ease of testing
