### ISSUE TITLE
UX: What should we do if we arrive on a search page with filters but we're on mobile?

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1362]
### Problem description
We're going to remove filters from mobile, but mobile users will still be able to get to the search page with filters on them, and in this case it should still show the results with the filters applied (for instance sharing a link or going from the organisations page). We need something for mobile that :

- Indicates what filters are applied
- Allows them to be removed (en masse)

Doesn't need to be more than that, we'll redesign the filters later.

**Comment by tkeuneman** [comment]
Work in progress: https://www.figma.com/file/6V1RKGaGFsE5IJiPG3Tc4u/Organisation

Need to spar ideas with Phil when he's back from leave

**Comment by tkeuneman** [comment]
Completed. Created a ticket: https://github.com/magda-io/magda/issues/1447

**Comment by tkeuneman** [comment]
Work in progress: https://www.figma.com/file/6V1RKGaGFsE5IJiPG3Tc4u/Organisation
 Sparring idea with Phil

**Comment by tkeuneman** [comment]
Done. Final design: https://www.figma.com/file/6V1RKGaGFsE5IJiPG3Tc4u/Organisation
