### ISSUE TITLE
mismatch in meta data fields when harvesting

### ISSUE THREAD

**Issue by chloeleichen** [magda-io/magda#1363]
### Problem description
There seems to be some mismatch in fields when Magda goes out harvesting data, from GA for example, and cause certain fields to be missing/inaccurate. For example, they might have a high-quality CSV but MAGDA was not able to find it, causing rating of the dataset to be degraded.

(feedback from GA during Terria PFOD planning meeting)

**Comment by AlexGilleran** [comment]
Can't do much with this unless we know the dataset in question :(.

**Comment by kring** [comment]
I think there's a decent chance this is a duplicate of #1264.

**Comment by kring** [comment]
Actually, on further consideration, I'm probably wrong. Move along, nothing to see here.
