### ISSUE TITLE
Enter a dataset page with `*` query string will see a blank page

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#1366]
### Problem description

Enter a dataset page with `*` query string will see a blank page

### Problem reproduction steps

Access this URL:
https://magda-dev.terria.io/dataset/ds-dga-fa0b0d71-b8b8-4af8-bc59-0b000ce0d5e4?q=*
you will see a blank screen

Errors see screenshot

### Screenshot / Design / File reference

![image](https://user-images.githubusercontent.com/674387/42259444-c6fd9066-7fa3-11e8-866d-ff49c89ee912.png)

**Comment by QuadTog** [comment]
If you search with an empty string it adds an '*' to the search field.

Navigate to: https://search.data.gov.au/search?q=%2A

![image](https://user-images.githubusercontent.com/20583588/42301773-7b3ed718-805a-11e8-8c52-3e6b6ab24097.png)

**Comment by AlexGilleran** [comment]
Yep raised here: https://github.com/magda-io/magda/issues/1144

This is resolved by https://github.com/magda-io/magda/pull/1367.
