### ISSUE TITLE
mobile menu new design

### ISSUE THREAD

**Issue by chloeleichen** [magda-io/magda#1375]
### Problem description

Like this: 
https://github.com/magda-io/magda/issues/1359

as part of https://github.com/magda-io/magda/issues/1359
<img width="376" alt="screen shot 2018-07-05 at 1 18 49 pm" src="https://user-images.githubusercontent.com/7508939/42300921-092ba808-8056-11e8-8d17-eb90feba47a4.png">

**Comment by tkeuneman** [comment]
Re-opening as the thick purple line is only meant to be shown for the page that the user is on. It currently shows for all of the pages so apart from from a slight grey box, users aren't able to see what page they're on.

What it is:
![screenshot_20180712-195105](https://user-images.githubusercontent.com/2201814/42626216-100b7470-860d-11e8-8bb1-b0cfef1f3156.png)

What it should be:
https://projects.invisionapp.com/share/C7MGEREJRTE#/screens/304141820_dataset

**Comment by tkeuneman** [comment]
Adding to this:
- [ ] Fix exisiting UI bug of border being present for all pages
- [ ] Background blur for modal dialog to be re-used here

**Comment by philipgrimmett** [comment]
See #1531 for latest designs
