### ISSUE TITLE
Hide Chart Tab on Chart Error

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1396]
### Problem description
Adapting from https://github.com/magda-io/magda/issues/1005 - if there's a problem loading data for the chart: 

Amended:
Load table tab first

Chart tab is still available with error alert under the tab (in the body section) "Either there's something wrong with the file or there's an internet connection problem"

**Comment by chloeleichen** [comment]
New requirement:
1.  we need to have an error message for when the user clicks on the chart tab
2. you click on it then you see a red alert "Either there's something wrong with the file or there's an internet connection problem lol"
