### ISSUE TITLE
SPIKE - Investigate customisable text

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1401]
### Description
List all the text items that need to be customisable and not specific to "data.gov.au" so we can decide how to address them

**Comment by t83714** [comment]
@aneesha09 @AlexGilleran 
Created a list of all possible customizable Branding Items with my recommendations:
https://docs.google.com/spreadsheets/d/1AUtsXWWFTkn2ZueCPOHVd-pM2SfCqU7vcei5RRiLp3A/edit?usp=sharing
I also included branding related Image / logos & other functions when I am going through the system.
You can use the column filter to list the `text content` only.

Share with everyone to help you guys with the decision making.

I think @philipgrimmett might also be interested in this list.

Please let me know if I missed anything~
