### ISSUE TITLE
Make UI branding configurable through content-api

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1402]
### Description

As a Magda maintainer I want to be able to specify branding (colours, logos etc) without having to fork the codebase and rebuild.

### Acceptance criteria
- A fresh instance of Magda with no config should show default branding i.e. not data.gov.au, no open data toolkit and no give feedback by zendesk etc.
- We will pick this once we have completed investigation of what all needs to be "config" friendly

**Comment by t83714** [comment]
#1401  has been completed (see [comment](https://github.com/magda-io/magda/issues/1401#issuecomment-412733449)). 
I have created a list of all possible customizable Branding Items with my recommendations:
https://docs.google.com/spreadsheets/d/1AUtsXWWFTkn2ZueCPOHVd-pM2SfCqU7vcei5RRiLp3A/edit?usp=sharing

This list was aimed at helping the decision making around this topic.
Let me know if I missed anything~ Thank you~

**Comment by AlexGilleran** [comment]
Have expanded into: #1763 #1762 #1760 #1756
