### ISSUE TITLE
Redirection for data.gov.au

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1406]
### Problem description
- We need the whole list from Alex S.
- Analyse and redirect all the URLs e.g. search, organisations, org search etc.
- Check there are no redirect loops

**Comment by maxious** [comment]
Suggestions for things CKAN needs: /about, /api/3/*, /dataset/*/resource/* /dataset/edit/,* /dataset/new, /fanstatic, /feeds, /geoserver, /group, /organization, /showcase, /storage, /uploads, /user, /vendor/leaflet

Data sources below, internal links broadly across 90,000+ pages but doesn't include assets, urls.txt is an extract from a day but includes raw traffic from an ELB (including 404s!)

[internallinks.csv.txt](https://github.com/magda-io/magda/files/2187396/internallinks.csv.txt)
[urls.txt](https://github.com/magda-io/magda/files/2187388/urls.txt)

**Comment by t83714** [comment]
I think probably some URLs are more suitable to be redirected at the backend and some probably better do at frontend. Will go through the list, have a play and get back to you guys with a plan first.

**Comment by t83714** [comment]
Thanks for the help from @maxious 👍 
I have created a redirection plan:
https://docs.google.com/spreadsheets/d/1nEyknNJj2bzv1sBltjGPL92j50hW9C5yUpcTYQnvzqM
This google sheet detailed:
- All Ckan URL patterns that we are going to redirect
- Which system we are going to redirect to (Ckan or Magda)
- Where the redirection will take place (e.g. which system module, backend or frontend)
- What's the redirection logic (how it'd been done)
Please let me know if anything is missing from the list or should be corrected.

**Comment by t83714** [comment]
We quickly discussed the items listed on this document:
https://docs.google.com/document/d/1ktrjZ2V6cBqYffp1ebnM248ibKTJeBRhgaLysvs5Seg

Based on the discussion, here is the updated version of URL redirection list to reflect the up to date requirements:

https://docs.google.com/spreadsheets/d/e/2PACX-1vTd_4G3LKpw8oHSCxbXO4KUxCvwSgtMNmkf91LgqAwJHAX9TN0FbJ7REBKHW3sLHt8w_xN9zemTAKsN/pubhtml?gid=0&single=true

Regarding `the iframe support`, it will be looked after later by a separate issue and will not be covered by this issue.
