### ISSUE TITLE
SPIKE - Storage options

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1407]
### Problem description
Investigate storage options:
- Should be able to store files
- Should be secure, not open to the Internet
- Cannot lean on just a cloud service 
- Should be open so someone can choose to store files in another way
- See if we can leverage an open source lib, preferably not write our own

**Comment by aneesha09** [comment]
Figure out storage so we can publish data on Magda

**Comment by t83714** [comment]
@aneesha09 & @AlexGilleran 
About point 3: `Cannot lean on just a cloud service`
Our current solution is running in google cloud.
Does that mean the file storage service should be:
- running by itself
- outside the current cloud cluster 
- and needs to be installed on a dedicated psychical machine?

**Comment by aneesha09** [comment]
I'm not sure, don't remember the intent of writing that. @AlexGilleran - Do you think this was about allowing hosting on a server if needed?

**Comment by t83714** [comment]
Relooked at this issue & here are my two cents: 

I think several options/decisions may help to define the technical requirements in this area:
- Publish public facing dataset
  - We probably need to have a build-in function to cover this area as it seems most clients' current current data files / source are hosted on internal system without public access
  - The storage option for public facing data probably better to be a cloud based solution. And requires less security control. 
  - We may want to think more about how to help clients to integrate with those internal system during the process of:
    - Reproduce public dataset from private / internal dataset
    - Dataset pre-release sanitation to make sure no inappropriate data leaked
    - Upload public dataset to our public facing storage
- Internal data source / non-public data
  - Do we want to host the internal / non-public data file/source?
    - We probably don't want. Currently, clients likely have their internal data hosted by various internal systems (database / shared drive etc.). They are more likely needing helps on integrating those systems for publishing rather than replace them / add another system (as there could be many manual processes behinds each of those systems).
  - What we can help in this area is probably the integration part as described above
  - If we do need to provide storage options for private datasets, this solution will need to be a different solution and compare with the solution for public dataset, it will require more security feature.

**Comment by nahidakbar** [comment]
My 2.44 cents for whoever picks this up.

* Not sure how platform agnostic we want to make this solution - E.g. tied to google cloud vs not. 
* In a past project for a similar need, we used aws s3 in combination with minio (for non-aws deployments)

**Comment by aneesha09** [comment]
@MelanieHotchkiss - FYI. I suggested to @t83714 that the dev team discuss this and decide on an approach to go forward.

**Comment by AlexGilleran** [comment]
I think programming against the S3 API with https://docs.minio.io/ sounds awesome. Minio even comes with a helm chart and good integration with kubernetes 🎉
