### ISSUE TITLE
Open data tooltip bug

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1410]
### Problem description
The open data tooltip is out of alignment. Needs to be centered to align with the stars. The tooltip also has two different font sizes, depending on whether you're in the search results page or the dataset page.

- [x] Align ? icon on search results
- [x] Align ? icon on dataset page
- [x] Pick the bigger font size for both tooltips

Note: This is the third time where it has gone out of alignment. Any idea on why this keeps on happening? 

### Screenshot / Design / File reference
<img width="228" alt="screen shot 2018-07-10 at 4 40 19 pm" src="https://user-images.githubusercontent.com/2201814/42493352-0b9c49ea-8460-11e8-8db0-9742db5c810f.png">

<img width="1169" alt="screen shot 2018-07-10 at 4 43 54 pm" src="https://user-images.githubusercontent.com/2201814/42493500-9f19cf1c-8460-11e8-962f-73826e6474f2.png">
<img width="1249" alt="screen shot 2018-07-10 at 4 43 47 pm" src="https://user-images.githubusercontent.com/2201814/42493502-9f49ee72-8460-11e8-8d30-2e7cf0feb5a9.png">

**Comment by tkeuneman** [comment]
Sigh. We've lost the previous work in this PR. There's meant to be a second delay once a user moves away from the tooltip. 

The tooltip on the results page is still out of alignment. 

I think increasing the padding around the text so that it's 16px or 12px would help make this look like it can breathe a bit more.

**Comment by AlexGilleran** [comment]
Merging into https://github.com/magda-io/magda/issues/1447
