### ISSUE TITLE
Feedback dialog bugs

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1411]
### Problem description
- [x] Make the header of the modal dialog in line with the other text components
- [x] Add a 30pt padding between the left-aligned content and the dialog border (exact pt is up for conversation)
- [x] Replace 'X' with mobile menu 'X'
- [x] Make the 'X' vertically aligned with the box, then add the same padding to the right border
- [x] Fix up extra white border thinghy that's popped up
- [x] Make the dialog have 30pt between each side of the content borders (right now, there's a bigger gap on the right side), ideally it would have the same padding on each side. 

### Screenshot / Design / File reference
<img width="1405" alt="2016_soe_biodiversity_number_of_epbc_reptile_species_in_each_ibra_region_data_gov_au" src="https://user-images.githubusercontent.com/2201814/42493838-c3b0a1c4-8461-11e8-9a1f-dcec372b1e4b.png">

**Comment by AlexGilleran** [comment]
@chloeleichen 

oops, I hit merge on the PR but then realised there's these hard-to-see scrollbars on the edges:

![image](https://user-images.githubusercontent.com/900555/42667148-d2819a32-868c-11e8-9d6d-b5917cd24b4f.png)

Can you raise another one?
