### ISSUE TITLE
Replace 'x' for the banner with the mobile menu X

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1412]
### Problem description
We have three different 'x' icons floating around. 
- [x] Replace the x in the banner one with what you can find in the mobile menu.
- [x] Replace the x in the 'ask a question' dialog

### Screenshot / Design / File reference
Replace this x:
<img width="1232" alt="screen shot 2018-07-10 at 4 53 44 pm" src="https://user-images.githubusercontent.com/2201814/42493880-edd18914-8461-11e8-80a9-2fe6d6ad3e3e.png">
With this one:
<img width="391" alt="screen shot 2018-07-10 at 4 55 04 pm" src="https://user-images.githubusercontent.com/2201814/42493909-060a709a-8462-11e8-9929-72da1cf140fd.png">

**Comment by AlexGilleran** [comment]
Because this got split into two PRs I can't fully QA it in either - @tkeuneman could you see if this looks right in dev when this message is at least an hour old?

**Comment by tkeuneman** [comment]
Sure, dev is still down. Will hang tight till then.

**Comment by tkeuneman** [comment]
Good to go!

**Comment by tkeuneman** [comment]
@AlexGilleran did you want me to close this?
