### ISSUE TITLE
About page links are broken or missing

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1416]
### Problem description
- [x] Omit this text as the links don't work:
> Want to keep in touch?
> Subscribe to the new datasets feed or customise a feed below: Groups, Tags or Search.
- [x] Add link back to Open Data Toolkit when it's mentioned in the page (it happens several times): https://toolkit.data.gov.au/index.php?title=Main_Page

### Screenshot / Design / File reference
<img width="727" alt="about___data_gov_au" src="https://user-images.githubusercontent.com/2201814/42494603-17cc2c7c-8464-11e8-998a-b1ff016c62de.png">

**Comment by stephencannings** [comment]
Hi, this page is getting an edit. I can supply copy.

I made a ticket about access to edit:
https://github.com/magda-io/magda/issues/1421

S.

**Comment by tkeuneman** [comment]
Thanks. Refer to the ticket to get access and to set up an editing process within DTA! 👍🏽
