### ISSUE TITLE
Organisation dataset filter: Desktop and Mobile

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1447]
### Description
As a Magda user
I want to be able to view all data sets of an organisation on desktop as well as mobile
So that I can browse them regardless of the device I am on

### Acceptance Criteria

1. Remove filters from organisation page on mobile. The org filter would be executed in the background but the user does not need to see this. When a user types in a new search, the filter will be cleared. This is an interim step until we have filters back in mobile.
2. The first time a user goes to the search results from an organisation page on desktop, they see the tooltip. 
3. The tooltip is dismissed either by the user clicking away from the tooltip, or by clicking 'Got it'
4. The tooltip is only available on desktop
5. Once the user dismisses the tooltip, the browser remembers this and does not show the tooltip again unless they clear their cookies

### Screenshot / Design / File reference

Designs: https://www.figma.com/file/6V1RKGaGFsE5IJiPG3Tc4u/Organisation

**Comment by AlexGilleran** [comment]
No, still going! 😬
