### ISSUE TITLE
DAP Connector Puts / in front of formats

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1458]
### Problem description
All formats coming through from the DAP seem to have a `/` in front of them (e.g. `/csv`). Looks like we need to cut the string one character later.

### Problem reproduction steps
On dev.magda.io: Search with organisation = CSIRO. 
In Minikube: Trigger the DAP connector.

![datasets_search__csiro___page_1___data_gov_au_-_beta](https://user-images.githubusercontent.com/40556131/44760316-9f819280-ab81-11e8-90d9-cd258798f58a.png)

**Comment by t83714** [comment]
It looks like a bug in format enhancer --- missing index by 1 when using `substr` to split format from MIME.
The DAP connector just put MIME type to format field
Will do more tests before creating a PR.

**Comment by t83714** [comment]
While testing my PR, found out a strange issue: 
it seems only dataset record was updated during re-crawl.
Distribution records haven't been updated.
Could be the JsonConnector problem or DAP connector.
I will have a look again later today.
![image](https://user-images.githubusercontent.com/674387/42976999-16e42f48-8c08-11e8-9df2-9ad745822b6d.png)

**Comment by AlexGilleran** [comment]
🤔 good detective work 🕵️

**Comment by t83714** [comment]
Haven't got a chance to finish my debugging.
Will re-look at it when it's added to a sprint or we have a gap between sprints.
