### ISSUE TITLE
Add readiness probes to all services

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1471]
### Problem description
Right now we have liveness probes set up for everything but not readiness probes. This is a problem because it prevents deployments from being zero-downtime, and also messes up the timing of the post-upgrade helm jobs that set up the database schema. We should make it so that every pod has a readiness probe. In most cases we can just use the same method as the existing liveness probe, but in some (e.g. postgres, elasticsearch) we might have to do something different, because it needs to make sure that these are up, ready and able to serve data, not simply started but not yet actually ready to serve data.

MVP:

- [x] Common infrastructure
- [x] Content API

Connectivity:
- [x] Database
- [x] Dependencies between services
- [x] Gateway

Others:

- [x] Admin API
- [x] Auth API
- [x] Correspondence API
- [x] Registry API
- [x] Search API

**Comment by aneesha09** [comment]
After doing this, run a full preview and make sure it works.
