### ISSUE TITLE
UI is looking for wrong name for link status

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1478]
### Problem description
The ui is looking for `optionalAspect=link-status` when it's actually called `source-link-status`, which is breaking everything to do with source links. We should change that.

**Comment by t83714** [comment]
distribution related `optionAspect` parameter in the dataset request URL seems not taking any effects (as dereference=true). We should consider removing them to avoid confusion.
A separate issue is created here: #1484
