### ISSUE TITLE
Links to distributions from dataset page have "undefined" as the dataset id

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1482]
### Problem description
The URLs for distribution pages on the dataset page have "undefined" as the dataset id. This doesn't actually stop the URL from working but it is very very embarassing.

### Problem reproduction steps
- Go to a dataset page e.g. https://dev.magda.io/dataset/ds-dga-fa0b0d71-b8b8-4af8-bc59-0b000ce0d5e4/details?q=
- Click on one of the distribution links
- Notice that there's "undefined" in the URL... e.g. https://dev.magda.io/dataset/undefined/distribution/dist-dga-35953a01-a9a8-4609-8566-c9fa7de465d3/details?q=

**Comment by t83714** [comment]
merged & closed
