### ISSUE TITLE
Data.json connector doesn't get licenses

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1500]
### Problem description
We have the `magda-project-open-data-connector` to crawl `data.json` endpoints - this is mostly automatic because data.json is dcat and we're dcat so it's all good.

EXCEPT that data.json puts the license at the dataset level and we have it at the distribution level, so we need some way to copy it from the dataset to the distributions as we crawl.

Because data.json also specifies that the license field should be a link, we should also make sure that the URLs play nice with the quality enhancer.

### Problem reproduction steps
See http://www.data.act.gov.au/data.json - datasets such as https://search.data.gov.au/dataset/ds-act-https%3A%2F%2Fwww.data.act.gov.au%2Fapi%2Fviews%2Fknjh-tqjz/details?q=act have no license info.

**Comment by aneesha09** [comment]
Dataset is at the dataset level not file level. We should crawl to get the license.

**Comment by t83714** [comment]
We don't need to worry about the situation where the license field is a link.

**Comment by aneesha09** [comment]
- Rewrite the connector code to change logic to lift the information. Add field to distribution level and test. 
- Testing will require environment setup and connecting to the data source
- Finding the correct testcase would require effort
