### ISSUE TITLE
Take down http://preview.data.gov.au/

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1505]
### Problem description
We need to take down http://preview.data.gov.au/ as this is no longer reflective of the updated search.data.gov.au. Plus this is not needed now that we have the new website to point to.

**Comment by AlexGilleran** [comment]
- Delete the S3 bucket
- Remove the subdomain from Route53
- Delete the Google Analytics property

**Comment by aneesha09** [comment]
@AlexGilleran  to remove S3 bucket and @maxious to delete the DNS entry. Thanks guys!

**Comment by maxious** [comment]
Deleting from our end (data.gov.au):

preview.data.gov.au. | NS | ns-418.awsdns-52.com.  ns-747.awsdns-29.net.  ns-1282.awsdns-32.org.  ns-1862.awsdns-40.co.uk.
-- | -- | --

**Comment by aneesha09** [comment]
@t83714 - This will need admin access. I don't have that. I can only see search.data.gov.au. 

We can delete the property later, nobody can see it anyway. So we can close this.
