### ISSUE TITLE
'Suggest a new dataset' in search results: move to further down the results page

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#1521]
### Problem description
The 'Suggest a new dataset' is showing as the second result in every search that I run. If it continues to do so, it will either become part of the wallpaper to the user, or worse, people will start submitting requests even if there's a dataset that matches further on the page. 
It should show based on the relevance of the keywords to the datasets. 
- If it's set as relevance, lower the relevance threshold. 
- If it's not set as relevance and has just been done to show as the second result, change it so that it is based on relevance.

### Problem reproduction steps
Run a search on prod

### Screenshot / Design / File reference
<img width="820" alt="screen shot 2018-07-27 at 7 44 58 pm" src="https://user-images.githubusercontent.com/2201814/43314197-930c970e-91d5-11e8-8bf5-e37186ade4c0.png">

**Comment by tkeuneman** [comment]
Forgot to do this during the day. :)

**Comment by ketikat** [comment]
Hi, I'll have a crack at this.

**Comment by ketikat** [comment]
As a user, I think it makes sense to have this appear after the last returned result. So, if there are 5 results it comes after the 5th one, if there are 0 results it appears by itself.

Personally, I think it might be confusing if it appears nested inside of the results. However, I'll put it anywhere you like-- just let me know.

**Comment by AlexGilleran** [comment]
@tkeuneman is on a beach somewhere now I think :). @philipgrimmett what do you think? I remember we had a discussion about this the other day but I've completely blanked on what the outcome was.

**Comment by AlexGilleran** [comment]
Great to see you around again by the way @ketikat :)

**Comment by ketikat** [comment]
Thanks @AlexGilleran! the US/ AUS time difference isn't ideal though!

let me know when you guys have a decision on this, and I can get started

**Comment by AlexGilleran** [comment]
@ketikat I'm gonna take this one over because I want to make the form come up when the search results are below a certain score, which requires modifying the search api (and doing a bunch of docker nonsense to make it all work as a result) :).

**Comment by aneesha09** [comment]
Put the score in the response and if it dips below a certain threshold, show suggest a data set at that point. 
- Make search API return score
- Do the logic to show suggest a data set below a threshold
- Keep iterating until we find the right threshold
- Instrument with analytics so we can figure out what's happening with it
- Review as a team what's it doing on staging before we decide to release it
