### ISSUE TITLE
Once not found error is triggered, router will not functional properly (goes into a loop)

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#1529]
### Problem description

Access a non-exist dataset id:

https://dev.magda.io/dataset/ds-dsds

After that, search `*` and click any dataset link.

On chrome, any dataset page will not be loaded (see screenshot).

On Firefox, click any dataset page will trigger a redirection loop.

### Screenshot / Design / File reference

![image](https://user-images.githubusercontent.com/674387/43437949-05e19b66-94cf-11e8-92d1-e3687ab28c4e.png)

**Comment by t83714** [comment]
Might be related to https://github.com/magda-io/magda/issues/1527

**Comment by aneesha09** [comment]
Tested on Chrome and seems to be fine. @t83714 - Please test on firefox?

**Comment by t83714** [comment]
@aneesha09 
Have tested on firefox and didn't find any issue.
I think it's time to close it now~

**Comment by aneesha09** [comment]
Is it merged?

**Comment by t83714** [comment]
Yes. I think it's merged.
I was testing on https://dev.magda.io
That's domain is synced with our master branch (with one hour or so delay)
So if a function on that, it must be merged into master branch.

**Comment by aneesha09** [comment]
Closing it
