### ISSUE TITLE
Apply button is disabled in date filter

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1534]
### Problem reproduction steps
1. Search for water
2. Try to set filter to Feb 1654 to Dec 2100

Expected:
Apply button should work. It works if you apply a filter Mar 1654 to Dec 2100 and you can change it to Feb 1654 to Dec 2100 but does not work if you are applying the filter for the first time

Actual:
Apply button is disabled

### Screenshot / Design / File reference
![searching_for_water___data_gov_au](https://user-images.githubusercontent.com/40556131/43438659-bedbf244-94d2-11e8-813d-c8769ea6af93.png)
![searching_for_water___data_gov_au](https://user-images.githubusercontent.com/40556131/43438668-cca61972-94d2-11e8-82b3-dff0918db3ee.png)

**Comment by chloeleichen** [comment]
The apply button is only active after you make a change. if you are on default date, then there's nothing to apply therefore button not active
