### ISSUE TITLE
Make pagination responsive on mobile device

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#1535]
### Problem description

Currently, on master branch https://dev.magda.io

The pagination can still go over the screen.

### Problem reproduction steps

To test, please go to any page after page 7

### Screenshot / Design / File reference

![image](https://user-images.githubusercontent.com/674387/43438730-1439c630-94d3-11e8-9e55-7a8f01fd73cb.png)

**Comment by chloeleichen** [comment]
Fixed in https://github.com/magda-io/magda/pull/1502

**Comment by AlexGilleran** [comment]
Looks like #1502 was based on top of release/0.0.44 for some reason even though it wasn't marked as a showstopper, so it ended up on that branch after the release and merge to master happened. I'll revert it on 0.0.44 and merge it to master.
