### ISSUE TITLE
Deep-linking to distribution shows invalid info.

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1541]
### Problem description
If you go to this distribution: https://search.data.gov.au/dataset/ds-dga-d5a08a25-253b-4466-b8e4-fccecbd95095/distribution/dist-dga-7c8c1ed7-9e62-4e18-bca5-6504b1483ce2/details

![image](https://user-images.githubusercontent.com/900555/43497239-81f9b714-9584-11e8-9484-c8253523a8bc.png)

You'll notice that there's a number of things wrong - no organisation, and invalid dates.

However if you go to the same distribution via the dataset page:

https://search.data.gov.au/dataset/ds-dga-d5a08a25-253b-4466-b8e4-fccecbd95095/details?q= and click on the first distribution.

It works fine - has correct dates and publisher.

Deep linking to the distribution should be the same as getting to it via the dataset page.

**Comment by chloeleichen** [comment]
@AlexGilleran This is fixed in a previous PR and you can see it working on dev: https://dev.magda.io/dataset/ds-dga-d5a08a25-253b-4466-b8e4-fccecbd95095/distribution/dist-dga-7c8c1ed7-9e62-4e18-bca5-6504b1483ce2/details

**Comment by AlexGilleran** [comment]
Oh cool beans 👍
