### ISSUE TITLE
Filter Panel UI won't pre-select the option in UI when there is an option has been selected previously

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#1546]
### Problem description

Found this one when looking at issue #1524 

To trigger that, there are two criteria needs to be met:
- An option has been selected manually in organization filter panel
- Change browser URL with `organisation` query parameter with a value of a different organization

Should be low priority as not easy to re-produce

### Problem reproduction steps

- search * 
- filter result using `organisation` filter panel: e.g. select `Geoscience Australia`
- go to Organisation Page
- Click the dataset link of an `organisation` (e.g. `organisation` ACMA)
![image](https://user-images.githubusercontent.com/674387/43556436-22094364-9643-11e8-91fb-17f6a34dc182.png)
- You will find ACMA option is not selected on `organisation` filter panel
![image](https://user-images.githubusercontent.com/674387/43556496-503040bc-9643-11e8-855b-69a789fad178.png)

**Comment by aneesha09** [comment]
We don't need to fix this. People won't change URL often. It is an edge case and we can live with it now.
