### ISSUE TITLE
Investigate why SEO is so poor on search.data.gov.au

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1560]
### Problem description
A quick look on google for site:search.data.gov.au is a bit worrying:

https://www.google.com.au/search?q=site%3Asearch.data.gov.au&oq=site%3Asearch.data.gov.au+&aqs=chrome..69i57j69i58j69i59.3362j0j8&sourceid=chrome&ie=UTF-8

124 results and all the descriptions are `error`. This definitely needs investigating 😬

**Comment by AlexGilleran** [comment]
- Google hits errors loading our javascript, presumably we're not supporting Chrome 44
- It doesn't like the way we've put the sitemap url in our robots.txt, it should be on the last line and be absolute
- Our sitemap fails to load most of the time
- We should probably change the meta description on datasets and orgs.

**Comment by stephencannings** [comment]
Good sleuthing Alex!

Happy to adjust meta descriptions. For these two pages only?:

- https://search.data.gov.au/search
- https

://search.data.gov.au/organisations

Also, the description for here:
![image](https://user-images.githubusercontent.com/39356390/43750375-762bf60c-9a3b-11e8-875e-173f382ad879.png)

**Comment by AlexGilleran** [comment]
Thanks @stephencannings.

Unfortunately this is fixing something a level before even setting the meta descriptions... google can't even see the page in most cases, hence that broken message :(. I'm not sure how it managed to load a decent one for the about page.

Although if you want to write some better meta descriptions for those pages then put them in a ticket and I'll see what we can do :).

**Comment by stephencannings** [comment]
@AlexGilleran Ok, I could make a ticket and update meta descriptions but this might be a bigger and broader task, to include other pages as well. 

I see this ticket is closed. Does that mean the issue is resolved or backlogged?

**Comment by aneesha09** [comment]
@stephencannings - We fixed the sitemap and released it. Meta descriptions will have to be a separate ticket.
