### ISSUE TITLE
Login via Google

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1573]
As a Magda user
I want to be able to login via Google/Sign up via Google
So they can go to the logged in area/ register as a Magda user

### Acceptance criteria:
1. Existing or new user
2. Verify Google Login works
3. Add Login link
4. In the logged in view, show welcome username or name
5. Check the user is added to the "Users" table

### Dev Notes:
1. Give access to google app
2. Check redirect URI
3. Test!

**Comment by aneesha09** [comment]
@philipgrimmett - FYI

**Comment by nahidakbar** [comment]
What does "Add login link" mean?

**Comment by nahidakbar** [comment]
@AlexGilleran

**Comment by nahidakbar** [comment]
tested

it works

go to dev, click on sign in, click on google

**Comment by t83714** [comment]
@nahidakbar 
This issue may be related to the issue you're working on.
Not sure whether it's handy for you to fix it while you're look at your PR 😄 
https://github.com/magda-io/magda/issues/1664

**Comment by nahidakbar** [comment]
@t83714 great idea. I'll add that to the sprtint

**Comment by t83714** [comment]
@nahidakbar 
Awesome~ 👍
