### ISSUE TITLE
UX - Login via Google

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1584]
As a Magda user
I want to be able to login via Google/Sign up via Google
So they can go to the logged in area/ register as a Magda user

### Acceptance criteria:
1. Existing or new user
2. Verify Google Login works
3. Add Login link
4. In the logged in view, show welcome username or name
5. Check the user is added to the "Users" table

### Dev Notes:
1. Give access to google app
2. Check redirect URI
3. Test!

**Comment by aneesha09** [comment]
Related to #1573

**Comment by philipgrimmett** [comment]
Invision prototype:
https://invis.io/8QNQTX4D3AM#/316690808_sign_In

- Sign in page with Google option
- Create account with Google option
- First Google sign in screen for reference
- Success page with getting started banner

**Comment by aneesha09** [comment]
@philipgrimmett - Please note the additional feedback from the meeting. It would be good if you can summarise it here before you start to work on it.

**Comment by philipgrimmett** [comment]
- Added mobile prototype link: https://invis.io/6HNSN2LVKG2#/316947005_sign_In_-_Mobile
- Added Google only sign in / create accounts screens
- Updated brand block placeholder
- Updated profile with placeholder dashboard
- Updated profile image in header to display user initials by default (if no image is available)

**Comment by aneesha09** [comment]
Final desktop - https://projects.invisionapp.com/share/8QNQTX4D3AM#/screens/316690808_sign_In
Mobile - https://projects.invisionapp.com/share/6HNSN2LVKG2#/screens/317200104
