### ISSUE TITLE
Some datasets can crash mobile safari

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1591]
### Problem description
The dataset https://dev.magda.io/dataset/ds-dga-383accd9-2f6f-4cda-99c7-cd1ecddb2682/details?q=dfat crashes mobile safari, presumably because the CSV parsing is overloading the processor and locking the UI.

### Problem reproduction steps
1. Open mobile safari
2. Go to https://dev.magda.io/dataset/ds-dga-383accd9-2f6f-4cda-99c7-cd1ecddb2682/details?q=dfat
3. Wait for it...
4. Keep waiting (takes like a minute)
5. It'll die and refresh a couple of times
6. "A problem repeatedly occurred on "https://dev.magda.io/dataset/ds-dga-383accd9-2f6f-4cda-99c7-cd1ecddb2682/details?q=dfat"

**Comment by aneesha09** [comment]
We can look at this when it becomes a more widespread problem. At the moment 1% of our users are on safari and this doesn't happen on all datasets so we can look it when the volume grows
