### ISSUE TITLE
Add background colour to map preview

### ISSUE THREAD

**Issue by philipgrimmett** [magda-io/magda#1596]
### Problem description
When the preview map is loading only the spinner is shown, leaving an awkward gap in the page flow. 

### Proposed solution
Adding a subtle background colour to the loading preview map will prepare the eye for that content to appear once it has finished loading, making the sequence seem smoother (hopefully)

Background HEX: #F5F5F5

### Problem reproduction steps

1. Navigate to https://dev.magda.io/dataset/ds-nsw-188ae132-d7b4-4a1a-8785-21786bcbe0bf/details?q=
2. Scroll to see preview map loading

### Screenshot / Design / File reference

<img width="718" alt="screenshot 2018-08-14 16 31 35" src="https://user-images.githubusercontent.com/5292858/44075291-a1798a0a-9fdf-11e8-9b62-bcf3b3fb8bdb.png">

**Comment by aneesha09** [comment]
@philipgrimmett - Please provide the colour code for the colour to be added as background
