### ISSUE TITLE
API Documentation - Registry API

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1600]
### Problem description
Convert the registry api swagger doc to apidoc.

**Comment by t83714** [comment]
Have a chat on this with @AlexGilleran and I think here is what we gonna do:
- Rewrite the API / data description/comment in Registry API codebase in APIDocsjs format
- adjusts relevant scripts for:
  - Documentation site auto generation
  - API client code auto-generation. (Now swagger.json generated by APIDocsjs will be used)
Generated API client code should still be put at: 
`magda-typescript-common/src/generated/registry/api.ts`

**Comment by t83714** [comment]
Will create required `Apidocjs` comments in Scala source code for document generation purpose ONLY for now as `Apidocjs` doesn't have the capability / provide the tool to generate the metadata required for auto code generation.
My investigation concludes that we probably need to heavily customize the `Apidocjs` codebase to achieve that. 
@AlexGilleran is also doing some research around this area. 
I think we probably will know more once he has some play with `APIdocjs`.

**Comment by t83714** [comment]
A list of registry services need to be re-document:
- [ ] WebHook Service (6 endpoints)
- [ ] Aspect Definitions (5 endpoints)
- [ ] Record Aspects Service (5 endpoints)
- [ ] Record History Service (2 endpoints)
- [ ] Records Service (11 endpoints)
