### ISSUE TITLE
"yarn run create-secrets" creates everything in "test-secrets" ns by default

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1609]
### Problem description
If you choose the most default option when running the new secrets generator, everything gets created in the "test-secrets" namespace by default and there's no way to override it.

### Problem reproduction steps
1. Run `yarn run create-secrets`
2. Select `YES (Create Secrets in Cluster using existing config now)` as answer to first question

Result:
```
Successfully created secret `smtp-secret` in namespace `secrets-test`.
Successfully created secret `db-passwords` in namespace `secrets-test`.
Successfully created secret `oauth-secrets` in namespace `secrets-test`.
Successfully created secret `auth-secrets` in namespace `secrets-test`.
All required secrets have been successfully created!
✨  Done in 66.16s.
```

**Comment by t83714** [comment]
@AlexGilleran 
Is `test-secrets` from your question answer or env variable?
If you were trying to override namespace via env variable and didn't work, I must have introduced a bug via my last commit 😄 
Could you please share me your config file (if no sensitive info)?
You can dump it via `yarn create-secrets -P > config.json`. Thank you~

**Comment by AlexGilleran** [comment]
This is from a completely fresh installation and fresh terminal - no environment variables, no config json.

**Comment by AlexGilleran** [comment]
Oh I see, I thought there was no config file because I didn't see it in the workspace directory but makes sense that it lives in `~` - sorry!
