### ISSUE TITLE
Set a min-width property of body

### ISSUE THREAD

**Issue by nahidakbar** [magda-io/magda#1610]
### Problem description

looks ugly

### Problem reproduction steps

reduce window width

### Screenshot / Design / File reference

![image](https://user-images.githubusercontent.com/3362993/44184914-a9a09b80-a154-11e8-81cd-0b20aaa7a16b.png)

**Comment by AlexGilleran** [comment]
@nahidakbar is there an actual device that this has a problem with? If it's only affecting browsing through tools I think we can live with it for now?

**Comment by aneesha09** [comment]
Moving it to review later list

**Comment by aneesha09** [comment]
Issue moved to [magda-io/magda-future #1](https://github.com/magda-io/magda-future/issues/1) via [**ZenHub**](https://www.zenhub.com/)
