### ISSUE TITLE
Recent searches not working properly

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1617]
### Problem description
Picking up a search suggestion from recent searches doesn't work properly

### Problem reproduction steps
1. Search for ballarat bbq and see the results so that "ballarat bbq" gets added to your recent search
2. Type ba in the search box so you see ballarat bbq as a suggestion.
3. Click on the suggestion

Expected result:
You see the results for ballarat bbq

Actual result:
Page gets refreshed and you see results for ba

### Screenshot / Design / File reference

[Prod issue.zip](https://github.com/magda-io/magda/files/2301260/Prod.issue.zip)

**Comment by AlexGilleran** [comment]
Looks like the debounce on the search doesn't get cancelled when a search via the recent searches gets made (presumably that goes through redux so it's not listening for it).

We need to make sure the debounce gets cancelled when any kind of search happens.
