### ISSUE TITLE
Australian Government logo incorrect aspect ratio

### ISSUE THREAD

**Issue by MelanieHotchkiss** [magda-io/magda#1637]
### Problem description
Australian Government logo on home page is stretched vertically

### Screenshot / Design / File reference
![image.png](https://images.zenhubusercontent.com/5ac7000f4b5806bc2bcde19f/706994f5-135d-40d9-ac8c-3d813b5a708d)

**Comment by maxious** [comment]
Is this still occurring after https://github.com/magda-io/magda/pull/1629 was merged 2 hours later?
