### ISSUE TITLE
Link to interactive tax form showing errors

### ISSUE THREAD

**Issue by MelanieHotchkiss** [magda-io/magda#1638]
Home page link to interactive tax form is not loading correctly

![image.png](https://images.zenhubusercontent.com/5ac7000f4b5806bc2bcde19f/49c706fc-5f44-4437-9005-5f894bde19a6)

**Comment by MelanieHotchkiss** [comment]
@stephencannings did you want to fix this one?

**Comment by AlexGilleran** [comment]
(by changing the link to something better, not fixing the tax form itself, although that would also be great :p)

**Comment by maxious** [comment]
Tax form no longer current content
