### ISSUE TITLE
Investigate static content management

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1641]
### Problem description
As an Admin User
I want to change About page content
So that I can update the content for my organisation

Required outputs in a document:
1. Analysis of how other open source projects do content management
2. What content shows up in default installation

**Comment by philipgrimmett** [comment]
Working doc: https://docs.google.com/document/d/1rDS5NND1BKsGJS9nM8waYvGn9Nvm2SgnzIeWeIPEASQ/edit#

**Comment by aneesha09** [comment]
I think we have progressed this enough and we should create a ticket for technical investigation. What do you think @philipgrimmett? Can we close it?

**Comment by aneesha09** [comment]
@AlexGilleran - Do you know the technical investigation ticket for this one? Did we end up refining it at all?

**Comment by AlexGilleran** [comment]
I don't think we did. Or at least we did it ended up being pure backend.
