### ISSUE TITLE
Create an internal instance for Dept of Environment

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1656]
As a user from the Department of Environment I want my very own instance of Magda, with just my private data on there.

### How to do it
- Create a new Google Cloud account so if we ever want to give this to them we can just hand it over
- Set up a Google Cloud SQL instance. This doesn't need HA either but it does need regular backups
- Set up a GKE cluster
- Fork magda-io/magda-config and modify the config
    - I don't think it really needs to be high-availability, one replica of everything is fine
    - The only connector should be for the Dept of Environment catalog spreadsheet
    - It should be protected by a password
    - It shouldn't have any minions for now 😞 .
    - Figure out some domain for it - doee.magda.io? Don't point it anywhere yet though, just use it for the ingress!
    - It should point at the Google SQL database, obviously
- Deploy cert-manager into the cluster
- Deploy magda - run the secrets script and helm install
- 🤞 
- If it's all going ok, reserve the IP that the ingress grabbed through google cloud console and point the domain at it
- Once up, change the logo to the Dept of Environment one and make sure the connector finishes correctly, and make sure the password is working
- Load DoEE Data Catalogue into the instance

### Acceptance Criteria
I can go to this new instance, put in the right password, see a version of Magda with the Dept of Environment logo and search through their datasets.

**Comment by aneesha09** [comment]
@AlexGilleran or @t83714 to update install steps with Agriculture with errors found during deployment.

**Comment by nahidakbar** [comment]
Admin API failing
