### ISSUE TITLE
After signed-in, there is unnecessary space / gap in header

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#1664]
### Problem description

After signed-in, there is unnecessary space / gap in header

### Problem reproduction steps

Go to: https://dev.magda.io/
after you're logged in, you will see the different header.

### Screenshot / Design / File reference

![image](https://user-images.githubusercontent.com/674387/44891926-64b85f80-ad25-11e8-945b-e8c0eebbd159.png)

**Comment by aneesha09** [comment]
I think this should be a part of the Login ticket as a PR comment if it was introduced by that one. What do you think @t83714

**Comment by t83714** [comment]
@aneesha09 
Sorry I didn't know we have an existing ticket.  😅
If so, we probably can close this one.
I saw that issue on the Master branch (https://dev.magda.io/) so I thought it's something new.  
By the way, which issue / PR was it?

**Comment by aneesha09** [comment]
Hey @nahidakbar - could you please add an estimate to this?
