### ISSUE TITLE
Registry API is taking ~4gb RAM 

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1670]
### Problem description
Right now the registry api is sitting on 4gb of memory consumption in dev and in preview namespaces. It doesn't seem to be happening in prod so presumably this is something we introduced recently, though no guarantees on that.

### Problem reproduction steps
Run `kubectl top pods` in dev

**Comment by t83714** [comment]
Had some play with my local cluster but couldn't reproduce the problem.

Notice our Java version support Native Memory Tracking.
Probably we can change the dev deployment with one extra parameter if we do want to track down this issue: 
e.g.:
```
"/app/bin/magda-registry-api",
"-Dhttp.port=80",
"-Dhttp.externalUrl.v0={{ .Values.global.externalUrl }}/api/v0/registry",
"-Ddb.default.url=jdbc:postgresql://registry-db/postgres",
"-Dakka.loglevel={{ .Values.logLevel | default .Values.global.logLevel }}",
"-DauthApi.baseUrl=http://authorization-api",
"-Dscalikejdbc.global.loggingSQLAndTime.logLevel={{ .Values.global.logLevel | lower }}",
"-J-XX:NativeMemoryTracking=summary",
"-Dauthorization.skip={{ .Values.skipAuthorization | default false }}”
```
Then: 
- `kubectl exec -it registry-api-7dc7bb8896-76p55 -- /bin/bash`
- Record one baseline: `jcmd 1  VM.native_memory baseline`
Later if we do have the problem.
We can use `jcmd 1 VM.native_memory detail.diff` to tell the difference.
