### ISSUE TITLE
Investigation - Registry API: Hook service / Get Hook Endpoint may report timeout when Actors are very busy

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#1671]
### Problem description

We recently added the feature of making Actor status available from hook info result returned from Hook service endpoints (see PR https://github.com/magda-io/magda/pull/1619).

The actor status retrieve process requires sending a `getStatus` message to the actor and wait for the response.

When the actor is too busy, actor might not be able to return the response timely (within 5 seconds) and will produce a timeout exception in the log (see log from the attachment).

There's a number of ways we might solve this:
#### Solution 1
- Incease the timeout to 30 seconds
- And this timeout parameter should be adjustable from Config
- The `isRunning` & `isProcessing` fields should both be `String` (Default value is `Unknown`)
  - All available values are:
   - `Unknown`
   - `Yes`
   - `No`
   - `Timeout`
- When `getStatus` query timeout, the value for the two fields above should be "Timeout"

#### Solution 2
Have a process occasionally query the actor and get its status. When the API is invoked it gets the last status this actor got and the time it got it.

#### Solution 3
Have the webhook actor report send a message to some kind of listener whenever it changes, which stores the last state it received and returns it when the API is invoked

This an investigation to see what the best solution is.

### Problem reproduction steps
Probably reduce the CPU resource and increase the webhook actor load will see this error.

### Screenshot / Design / File reference
[registry.log](https://github.com/magda-io/magda/files/2343928/registry.log)

**Comment by AlexGilleran** [comment]
👍
