### ISSUE TITLE
Default dataset order should be "recently updated" for Organisations

### ISSUE THREAD

**Issue by QuadTog** [magda-io/magda#1674]
### Problem description
Datasets filtered by an organisation should be set to 'recently updated' as the default. Otherwise old or stale datasets may stay at the top of the organisation pages.

This change would also align the results with the previous site for consistency and we've had a couple of users suggest it.

### Problem reproduction steps
For example:
**Old**
https://data.gov.au/organization/department-of-finance

**New**
https://search.data.gov.au/search?organisation=Department%20of%20Finance

### Screenshot / Design / File reference
![image](https://user-images.githubusercontent.com/20583588/44965390-ab51c800-af78-11e8-81e2-b9eb188b68da.png)

**Comment by QuadTog** [comment]
Without this functionality, companies are starting to request how they can order their datasets to prioritise newer information. They are concerned users will get the impression that the org is providing out of date data; or that a user will access the wrong dataset.

Do we have other ways to order an organisation's datasets? Rating, popularity, creation date etc.?

**Comment by AlexGilleran** [comment]
I've created https://github.com/magda-io/magda/issues/1761 to handle making data "freshness" 🥗 a part of search ordering, which should give us this for free (filter by organisation = no search relevance to worry about, therefore datasets will be ordered by a combination of quality and most recent update). I think that should pretty much take care of the core issue here.

We don't currently keep track of popularity - we do order by rating, but not by creation date.
