### ISSUE TITLE
apidocs is broken

### ISSUE THREAD

**Issue by nahidakbar** [magda-io/magda#1679]
### Problem description

![image](https://user-images.githubusercontent.com/3362993/45005224-87a08780-b035-11e8-82d0-8225edf794bb.png)

**Comment by AlexGilleran** [comment]
with `/index.html` it works, but it'd be nice to have the root work too.

**Comment by AlexGilleran** [comment]
Seems to work fine at https://dev.magda.io/api/v0/apidocs/ for me now (?!?!)

I have no idea what changed.
