### ISSUE TITLE
EPIC: Visualization Minion Overhaul

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1714]
As a Magda user, I want to see accurate and relevant visualisations of data.

### Problem description
Right now we have a visualization sleuther that is supposed to look at tabular data (CSVs) and determine their structure so that they can be visualised. In an ideal world this would:

- Determine whether the distribution is worth visualising at all (if it's just a bunch of numbers then there's no point)
- Read the column headings
- Determine the data type of each column (string? numeric? date?)
- Determine whether each column is worth charting (e.g. if it's all the same value then it's not going to make a very good chart). This is likely to be more like a sliding scale than a yes/no
- For dates, determine the format of the date
- For strings, estimate how many different values there are for that column - ones with few differing values are likely categories that would make a good X axis
- Determine the orientation of the CSV - some are oriented 90 degrees to what you'd expect - i.e. the headers are all in the first column rather than the first row, and values are in subsequent columns
- Looks for csv-geo-au compliant columns that could be used for visualisation on TerriaJS
- _Potentially_ make a judgement on how nice the resulting chart is going to be, which could influence search ordering

Right now it _kinda_ determines column names and formats, but not very well. It also has some performance problems that could probably be alleviated by caching data locally rather than putting it in memory etc.

The purpose of this ticket is to look at the feasibility of doing all the above and produce an epic full of well-defined tickets that can be estimated and prioritised.

### Acceptance Criteria
- An epic has been created containing well-defined issues for achieving all the above
- This epic also has an issue for making the UI trust the visualisation sleuther rather than overriding it as it does now

### Related
Please see:
- https://github.com/magda-io/magda/issues/910, a bug that stops the visualisation sleuther from parsing CSVs correctly that should be part of the epic
- https://github.com/magda-io/magda/issues/381 , column formatting change

**Comment by aneesha09** [comment]
Add test cases for visualisation minion, what kind of output it should/does produce for inputs. We currently don't have test cases for this minion.

**Comment by aneesha09** [comment]
Please take the test case into account while creating tickets out of this investigation (#910)

**Comment by aneesha09** [comment]
@nahidakbar - Could we split this into stories based on your investigation? I would like to not work on an epic as a whole if we can avoid it
