### ISSUE TITLE
Redirect non-prod environment emails to a generic mailbox

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1717]
### Problem description
Right now dev and preview are sending emails to real users
Please change this for all non-production environments to send the emails to a generic email address so we can test emails and also avoid mistakes of having sent test emails to prod users

**Comment by aneesha09** [comment]
@AlexGilleran - Which email address do you think we should use? Do we sign up a new gmail ID or something?

**Comment by AlexGilleran** [comment]
We already have the magda dev google group, unless you need it to be private?

**Comment by aneesha09** [comment]
Can anyone testing see the email in the google group e.g. Me, Mel or QA when they start? Would it be a problem if it receives a lot of email?

**Comment by AlexGilleran** [comment]
Yeah anyone testing can see it, and nah it'll be no problem if it gets a lot of email, some of these mailing lists get a few emails every second :)
