### ISSUE TITLE
HTTP requests to prod domain don't redirect to HTTPS

### ISSUE THREAD

**Issue by adamzerella** [magda-io/magda#1748]
### Problem description
When requesting the live domain ( search.data.gov.au ) over `http` the web module is responding with a `200` status code. This should be `301`.

### Problem reproduction steps
`curl -I http://search.data.gov.au`

### Screenshot / Design / File reference
![image](https://user-images.githubusercontent.com/1501560/46257481-ae02f700-c4fd-11e8-8e51-6e5c6f4560fb.png)

**Comment by AlexGilleran** [comment]
GCE makes this way harder than it really should be - I guess we can do something manual as described by https://serverfault.com/questions/733166/redirect-all-http-traffic-to-https-when-using-the-https-load-balancer-on-googl
