### ISSUE TITLE
Org Search Not Working

### ISSUE THREAD

**Issue by QuadTog** [magda-io/magda#1759]
### Problem description
Currently, when searching for organisations on MAGDA I am presented with a large list of potential organisations rather than a small list of the most likely.

### Problem reproduction steps
Search for an organisation:
**Office of the Australian Information Commissioner**
https://dev.magda.io/organisations?page=1&q=Office%20of%20the%20Australian%20Information%20Commissioner

> RESULTS MATCHING "OFFICE OF THE AUSTRALIAN INFORMATION COMMISSIONER" (**222**)

Due to the large list of organisations presented in alphabetical order you don't find the OAIC until page 16.
https://dev.magda.io/organisations?page=16&q=Office%20of%20the%20Australian%20Information%20Commissioner

### Screenshot / Design / File reference
![image](https://user-images.githubusercontent.com/20583588/46389134-9735ed80-c713-11e8-9cd0-d81ce9a2fd47.png)

**Comment by aneesha09** [comment]
Looks like this is happening because org search results are sorted alphabetically and not by relevance. They should be sorted by relevance.
