### ISSUE TITLE
Make header details come from content api

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1762]
### Problem description
Currently the details of what shows up in the header are hard-coded into the client. We should make this come from the content api so we can change it. We've already made the logo work like this, so we've just got to change the links at the side.

### Acceptance Criteria
- Details of links on the header come from content api
- There's reasonable defaults for new installs (e.g. Datasets, Organisations, About)
- There's a plan for migrating search.data.gov.au (this in particularly has its 🦄 "Community" link that doesn't make sense to have as a default)

**Comment by stephencannings** [comment]
@AlexGilleran Is the content api the cms you mentioned?

**Comment by AlexGilleran** [comment]
Yeah sort of - it's the backend of the CMS. With this you'll be able to change content on the fly but there won't be a UI for it yet, this is the in-between stage to allow us to have different versions for Data.gov.au, Department of Env, Department of Agriculture etc.

This'll mean that you can change things without having to go through Github, but it'll still be a bit fiddly

**Comment by gordjw** [comment]
@AlexGilleran which CMS are you using for this? 
Interested for this project and also other work that's happening internally.

**Comment by AlexGilleran** [comment]
I think "CMS" is overstating it - what we've got so far is a home-grown API that [lets you dump files into Postgres and retrieve them](https://github.com/magda-io/magda/tree/master/magda-content-api) ;).

The idea is that we do this super-naive solution, see what problems we're running into then use that to inform a more permanent solution.

@philipgrimmett has been looking at examples of how it should work on the front end - https://github.com/magda-io/magda/issues/1641.

[Vapid](https://github.com/vapid/vapid) has also just come up, I'm really interested in whether we can use that in some way, seems quite aligned with what we need.

**Comment by nahidakbar** [comment]
// {
                //     type: "default",
                //     label: "Community",
                //     href: "https://community.digital.gov.au/c/open-data",
                //     target: "_blank",
                //     rel: "noopener noreferrer"
                // },
