### ISSUE TITLE
Change "Organisations" to "Sections" in Internal Magda instances

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1775]
### Acceptance Criteria
Department of Agriculture instance has "Sections" in the header instead of "Organisation"

### Out of scope
Changing the "Organisations" filter - we'll worry about that later.

**Comment by aneesha09** [comment]
The terminology the staff used is sections within the department.

**Comment by aneesha09** [comment]
@AlexGilleran - What do we need to update the filter label too?

**Comment by nahidakbar** [comment]
@AlexGilleran @aneesha09 just the menu or everywhere else too?

**Comment by AlexGilleran** [comment]
@aneesha09 do you think we can get away with just the menu for now?

**Comment by aneesha09** [comment]
@nahidakbar - Where are the other places you see "Organisations" appearing? I can maybe prioritise among them. Thanks

**Comment by nahidakbar** [comment]
Once you click on the link, there are a bunch of places.

**Comment by nahidakbar** [comment]
@aneesha09

**Comment by aneesha09** [comment]
@nahidakbar - Yes, breadcrumb and page title would need to change. Ideally the filter label should change too - I see it is noted out of scope but what is the effort required to do that?

**Comment by AlexGilleran** [comment]
I've opened a new issue to deal with everything EXCEPT the header, but because github is messed up I can't link to it right now :(.

**Comment by AlexGilleran** [comment]
This is now purely a configuration change, so we can do it after we've shipped all the changes we've made 👍
