### ISSUE TITLE
Show quality rating only if present

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1776]
### Problem description
Right now if the quality sleuther hasn't computed quality for a dataset, the UI will show that dataset as zero stars, which isn't fair. We should make it so that the data quality parts of the UI (i.e. the 5 stars on the search results screen and datasets screen) don't show up unless there's an actual data quality rating to show.

This is a bit bigger than it looks, because I _think_ that right now the dataset quality rating gets indexed into elasticsearch as `0` if there's no rating - ideally we'd change this to `null` for datasets with no quality rating, but that might break search ordering.

### Acceptance Criteria
- Data quality rating doesn't show up on the search results page unless there's an actual data quality rating recorded for the dataset
- Data quality rating doesn't show up on the datasets page unless there's an actual data quality rating recorded for the dataset
- Ordering by quality rating should still be functional (datasets with no quality rating can still be treated as having a `0` rating for this purpose)

**Comment by aneesha09** [comment]
This is lower priority for MVP instance. Please pick something else @t83714
