### ISSUE TITLE
Group organisations by name and jurisdiction

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1786]
### Problem description
Derived from #1530 (comment) - that issue is more about the problem, this may or may not turn out to be the solution but it's a step in the right direction.

Currently on search.data.gov.au we have a lot of duplicate organisations (e.g. there's a bunch of CSIROs, ABSes etc) because each organisation is specific to its source, which makes sense in some cases (e.g. every state has a separate "Premier and Cabinet") and doesn't in others (e.g. the aforementioned 5 different CSIROs).

The proposed solution is to:

- Collect jurisdiction from sources where available (i.e. most CKAN portals)
- Provide a default jurisdiction where it makes sense (i.e. data collected by federal agencies should default to a "Commonwealth of Australia" jurisdiction, but state portals can't have a default jurisdiction because they carry federal and local-level data).
- In the UI, group organisations by this jurisdiction... e.g. if there's 5 CSIROs and they all have the jurisdiction "Commonwealth of Australia" (which they probably should), that means they show up as one organisation called "CSIRO (Commonwealth of Australia)". This affects everything - the organisations page, the search filtering, the organisation (singular) page.

This might get sticky - e.g. what do we do if the jurisdiction on a dataset and the jurisdiction on an organisation don't agree?

**Comment by QuadTog** [comment]
User Ticket:
@education.gov.au
> Hi, it looks like the data from the Commonwealth Department of Education and Training and that from the Victorian department of the same name, are being combined. When I click on the Commonwealth Department to look at its data sets - apparently 18 - it then lists 313, which is the sum of the two departments - 18 and 295. Also are you able to label the Victorian one, similarly to the way the Tasmanian one is distinguished. Thanks.

**Comment by AlexGilleran** [comment]
Yeah this is as a result of the band-aid solution we put in from https://github.com/magda-io/magda/issues/1530.

Right now we trust the  `jurisdiction` field in some CKAN installations. E.g. https://data.nsw.gov.au/data/api/3/action/package_show?id=cf5bc650-b395-4059-8d57-b6391e2b8a70 comes through fine because it's got `jurisdiction`, whereas ones from data.vic don't have jurisdiction: https://www.data.vic.gov.au/data/api/3/action/package_show?id=d1c1eb35-ce4b-4146-8646-0278feda0b69. So to get their datasets labelled properly they need to start supplying that field from data.vic.

The other part (not being able to search by jurisdiction, just by publisher name) is still outstanding - if ingesting jurisdictions is working well enough then maybe we can append the jurisdiction name to the publisher name for search?
