### ISSUE TITLE
Change CKAN connector to pick up jurisdiction field from Organisations

### ISSUE THREAD

**Issue by MelanieHotchkiss** [magda-io/magda#1816]
### Problem description

Acceptance Criteria:
- Show jurisdiction in API for organisation where available
- More organisations have jurisdiction than did before

### Problem reproduction steps
- Add "jurisdiction" to the publisher aspect
- Modify CKAN connector to set this from sources

**Comment by t83714** [comment]
Has done a full recrawl on gitLab test site and here is statistics based on the result from all `CKAN` connectors:

| jurisdiction                            | org_count |
|-----------------------------------------|-----------|
| null                                    | 183       |
| Commonwealth of Australia               | 98        |
| Local Government                        | 65        |
| Tasmanian Government                    | 13        |
| Victoria Government                     | 12        |
| Western Australian Government           | 12        |
| New South Wales Government              | 11        |
| South Australian Government             | 3         |
| Queensland Government                   | 2         |
| Australian Capital Territory Government | 1         |
| Northern Territory Government           | 1         |
