### ISSUE TITLE
Investigate WYSIWYG Libraries

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1825]
Look at various open source WYSIWYG libraries
Shortlist up to 3 libraries which might suit Magda

Refer to - https://github.com/magda-io/magda/issues/1641

**Comment by t83714** [comment]
Had a play with 6 WYSIWYG libraries and evaluated them based on the followings:

- Whether it comes with Native React Support
- Its popularity (by github stars)
- `Markdown` output support
- `Markdown` edit view support
- Whether it comes with a `medium` style inline toolbar

Shortlisted to 3 libraries (from most recommended to less recommended):

### 1> Draft.js 

Demo: https://draftjs.org/

Pros:
* A project backed by Facebook
* Very popular
* Long term stable project
* Support React Well
* Future Extensibility 

Cons:
* Not support Markdown as output but plugin available (draftjs-md-converter)
* No Markdown Editing view (Probably can self-develop)
* No `medium` style inline tool bar (Probably can self-develop )
    * https://www.draft-js-plugins.com/plugin/inline-toolbar

We should pick this if we can spare more time on this area and aims for `Future Extensibility`.

### 2> medium-editor

This is a clone of medium.com inline editor toolbar.
MediumEditor has been written using vanilla JavaScript, no additional frameworks required.

Demo: http://yabwe.github.io/medium-editor/

Props:
* Very popular 12,887 stars
* One stop solution
*  Pure javascript; No other library required
* Light-weight 28KB
* More mature & more contributors & long history project
* A lot of plugins available 
* `medium` style inline tool bar
* Build-in image drag support

Cons:
* No native React support but plugin available (react-medium-editor-es6)
* No native markdown support but plugin available:
    * https://github.com/IonicaBizau/medium-editor-markdown

We should pick this one if we want a reliable `One stop` & `off shelve` solution.
Plus, we like `medium` style inline tool bar

### 3> React Rich Text Editor

https://github.com/sstur/react-rte

Demo: https://react-rte.org/demo

Pros: 
* Support both HTML & Markdown output
* Can edit on HTML & Markdown view as well
* Popular projects (1,916 Stars)

Cons: 
* No  `medium` style inline tool bar
* No images support

We might want to pick this one if we want to allow user to edit `Markdown` / `HTML` source code.

**Comment by t83714** [comment]
Full list of WYSIWYG Editor reviewed:

### Draft.js 

Demo: https://draftjs.org/

Pros:
* A project backed by Facebook
* Very popular
* Long term stable project
* Support React Well
* Future Extensibility 

Cons:
* Not support Markdown as output but plugin available (draftjs-md-converter)
* No Markdown Editing view (Probably can self-develop)
* No `medium` style inline tool bar (Probably can self-develop )
    * https://www.draft-js-plugins.com/plugin/inline-toolbar

We can use a plugin to add markdown support:

### markdown-draft-js

https://github.com/Rosey/markdown-draft-js

Demo: http://www.roserobertson.me/markdown-draft-js/

Pros: 
* Based on draft-js thus, native React support
* Not a simple html to markdown convertor
* Provides markdown editing view

Cons
* Not well known project (76 stars)
* No  `medium` style inline tool bar


### React Rich Text Editor

https://github.com/sstur/react-rte

Demo: https://react-rte.org/demo

Pros: 
* Support both HTML & Markdown output
* Can edit on HTML & Markdown view as well
* Popular projects (1,916 Stars)

Cons: 
* No  `medium` style inline tool bar
* No images support

### react-draft-wysiwyg

Demo: https://jpuri.github.io/react-draft-wysiwyg/#/demo

Built on Draft.js

Pros: 
* More content styling options. Plus emoji input etc.
* Quite Popular project (2,852 stars)

Cons: 
* Only support Markdown output but no markdown edit view

### medium-draft

A medium like rich text editor built upon draft-js.

Demo: http://bitwiser.in/medium-draft/

Pros: 
* Based on draft-js thus React Compatible 
* Provides medium like rich edit UI
* Very user friendly UI and probably eliminate the needs of having a preview interface

Cons:
* Doesn’t support markdown output
* Yet to support React16 (We probably need to do it by ourselves)

Can use `draftjs-md-converter` (https://www.npmjs.com/package/draftjs-md-converter) to get markdown output.

### medium-editor

This is a clone of medium.com inline editor toolbar.
MediumEditor has been written using vanilla JavaScript, no additional frameworks required.

Demo: http://yabwe.github.io/medium-editor/

Props:
* Very popular 12,887 stars
* One stop solution
*  Pure javascript; No other library required
* Light-weight 28KB
* More mature & more contributors & long history project
* A lot of plugins available 
* Build-in image drag support

Cons:
* No native React support but plugin available (react-medium-editor-es6)
* No native markdown support but plugin available:
    * https://github.com/IonicaBizau/medium-editor-markdown

**Comment by aneesha09** [comment]
We will park design ticket for this for two weeks until 27 Nov 2018

**Comment by aneesha09** [comment]
We will go with the medium-editor to start with as it is easy to integrate. Save will be required manually and not auto-save as we don't have a versioning system yet

**Comment by chloeleichen** [comment]
I've also used [React-mde](https://github.com/andrerpena/react-mde) before and it's pretty awesome, expect it only supports markdown editing
