### ISSUE TITLE
Investigate client vs serverside preview of draft content

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1826]
What do we need to do technically to allow admin user like stephen to preview content before making it live?

**Comment by t83714** [comment]
Here is the summary of my investigation:
I believe the problem we had here is that we only can have one set of global UI settings which will impact all users. Therefore, there is no way to create a `staging setting` for preview purpose for users.
I was trying to implement a Preview mode feature at the client side that:
-  Allow web UI accepts runtime settings from the client side
  - This settings only impact the current browser window
- Allow Preview mode web UI output all settings injected. 
  - This output can be used to saving as the global settings
  - OR Saving to a different area as users' `design draft` record
    - User can come back to re-look / change his design anytime

Technically, it has been achieved through:
- A controlled runtime env in a popup window
- A local mocked content API database store at clientside
- Intecepte Ajax calls to content API via `fetch` API
- Intecepte ordinary browser URL request (e.g. `<img>` tag etc.) via inline URI 

A demo has been created at branch: `feature/client-preview`
**I am gonna demo this on next demo meeting with more details & tech side demos.**
You can try it by go into `magda-web-client` and `yarn dev` (All changes are client-side to min. the impact). And then access url `/settings`. e.g. if you run client locally, you can access the demo setting page from:
`http://localhost:6108/settings`

You should see a demo setting page like:

![image](https://user-images.githubusercontent.com/674387/48585926-5243de80-e982-11e8-9b8f-76fc8c714b81.png)

You can input a content API setting record (in JSON format) into the text box. And click `Send Setting Record to Preview Window` to see the changes (before that you need to open the preview window).

The input box can accept only one record at a time. To modify a record, just send one with the same record id. There is no data will be sent to server.

By sending setting records to `Preview window`, you can alter anything currently are configurable.
