### ISSUE TITLE
search.data.gov.au migrators are going to collide with normal migrators

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1845]
### Problem description
With all this content stuff we've been doing, we've been writing Flyway migrators that we build into our migrator images, and also writing manual scripts for data.gov.au, with the idea being that when the upgrade for data.gov.au happens, we can run the manual scripts then the migrators.

_However_ because in some cases both scripts are running an `INSERT` for the same content item id, this is going to break when we run the migrator. Which is annoying.

So we need to modify the migrators we've done to have `ON CONFLICT DO NOTHING` on the `INSERT` statements.

This will be fine in all our prod deployments because we haven't released the migrators yet, but it's going to make dev.magda.io very very unhappy. So we'll have to manually fix that with `flyway repair` when the change gets merged. But that's OK.

### Acceptance Criteria
- All the migrations for v0.0.50 can successfully run after all the search.data.gov.au-specific sql scripts for v0.0.50 have run.

**Comment by t83714** [comment]
Would it be more appropriate for some of the `INSERT` to be `ON CONFLICT DO UPDATE`?
As the default settings for generic site are supposed to be replaced.

**Comment by AlexGilleran** [comment]
Then there'll be a bit in between where search.data.gov.au has all the default Magda stuff though... like the About page will say "Insert about page here!" etc. :(

**Comment by t83714** [comment]
Ah~ I see~ It's for `no break` search.data.gov.au deployment~

**Comment by t83714** [comment]
It seems we still have a few unmerged PRs gonna add or update `content migrator`.
Will look at this issue later after those are merged.

**Comment by aneesha09** [comment]
Guys - please add an estimate to this one, thanks

**Comment by t83714** [comment]
I think `3` would be fair estimate~
