### ISSUE TITLE
Search Filter (by State) not filtering by state - user report

### ISSUE THREAD

**Issue by QuadTog** [magda-io/magda#1852]
### Problem description
User Reported the following issue:

> Corey
> Oct 23 12:27
>  
> Hi just checking out the data sets and when I filtered for the Dept of Health and Human Services with a filter of QLD a lot if the results were for other states and territories. Suggest we review tagging to improve search functionality if we can.
> 
> ------------------ 
> Submitted from: https://search.data.gov.au/search?organisation=Department%20of%20Health%20and%20Human%20Services&page=7&regionId=3&regionType=STE

### Problem reproduction steps
Navigated to: https://search.data.gov.au/search?organisation=Department%20of%20Health%20and%20Human%20Services&page=7&regionId=3&regionType=STE

Multiple non-QLD datasets and organisations appear on first page. Also tried without an organisation and still seeing multiple org-nsw rocking up:
https://search.data.gov.au/search?regionId=3&regionType=STE 

### Screenshot / Design / File reference
![image](https://user-images.githubusercontent.com/20583588/48324468-fb3dc100-e684-11e8-9c1d-b9b3e978f946.png)

**Comment by t83714** [comment]
Had a quick look at the Geo spatial data included by the first NSW result returned for the QLD query:

Dataset name: Interim Biogeographic Regionalisation of Australia (IBRA) Version 4.1, NSW Subset

Dataset Id: `ds-nsw-423817ea-f0e4-4a65-8b4d-1ee37db260b9`

The GeoJson data of the dataset is actually:
```
{"type": "Polygon", "coordinates": [[[154.0, -38.0], [154.0, -28.0], [141.0, -28.0], [141.0, -38.0], [154.0, -38.0]]]}
```
See screenshot below:

![image](https://user-images.githubusercontent.com/674387/48380413-cb95c400-e72b-11e8-8f15-bbaf7f54939f.png)

The spatial coverage indicated by the GeoJson data does cover a small portion of the QLD area.

As we use a `INTERSECTS ` query (i.e. Return all documents whose geo_shape field intersects the query geometry.), that NSW dataset will be included.

It's probably hard to fix / patch this source data problem as if we use a `WITHIN ` query (i.e. Return all documents whose geo_shape field is within the query geometry), we will miss all datasets have any area outside the query geometry.

**Comment by aneesha09** [comment]
This needs an investigation.

**Comment by AlexGilleran** [comment]
Yeah the geospatial part of this looks like bad metadata.

It is worrying that we're returning datasets for a different organisation than the filter  that's specified. This is correct at the API level (the search can't anything that matches both filters so it does an `OR`) but we're not reflecting this in the UI (anymore, we used to) so some notification needs to be (re) added.
