### ISSUE TITLE
Spike: Look into Kubernetes pod priority

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1874]
### Problem description
As of a recently, Kubernetes pod priority has moved into beta:

https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/

We should look into how we can use this - probably something along the lines of making sure the gateway has the most priority, then elasticsearch/db, then public api pods, then minions/connectors.

Desired result:
Spike & do - figure out how to change the configuration and change it

**Comment by aneesha09** [comment]
Try hardest to keep certain pods up at the expense of others.
