### ISSUE TITLE
Workflow improvements to Admin

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1888]
### Problem description
UX review and workflow improvements to vanilla admin created so far to make it more usable.
Accessibility considerations out of scope for this first iteration

Deliverable:
Highlight areas of improvement and provide recommendations

**Comment by philipgrimmett** [comment]
**Recommendations by page:**

**All pages:**
- [ ] Replace thick black border with horizontal divider after each save/delete group
- [ ] Apply min. 32px margin-bottom to horizontal dividers
- [ ] Apply 16px margin-right and 24px margin-top to 'save' and 'delete' buttons
- [ ] Apply #EF3E44 background colour to 'delete button', #FFFFFF text
- [ ] Apply #106BC7 background colour to 'save', #FFFFFF text
- [ ] Increase width of save button (1.5 width of delete)
- [ ] Update 'change' button text to 'Upload new image'
- [ ] Add a 'remove' button (default to MAGDA image/background if user uploaded picture is removed)
- [ ] Add new: don't show validation error until field comes in and out of focus (and content is invalid)
- [ ] Apply H2 style to 'Add new [X]' header

**Header logo:**
- [ ] Specify mobile logo break point

**Header navigation:**
- [ ] Shorten link title (eg. 'About', not 'header/navigation/about'
- [ ] Update 'Add new' header to 'Add new link'

**Header tagline**
- [ ] Update 'text' field to 'homepage feature text'
- [ ] Update 'url' field to 'homepage feature link'

**Homepage stories**
- [ ] Shorten story titles (eg. 'Explore the NationalMap', not 'home/stories/1543458323642'

**Content pages**
- [ ] Add link to markdown guide under 'Content Pages' (https://guides.github.com/features/mastering-markdown/)

**Footer navigation**
- [ ] Shorten item titles (eg. 'Privacy Policy', 'not footer/navigation/medium/category-links/magda/privacy'
- [ ] Preeeeetty confusing in general. Might be easier to read/update if category menu items are collapsed by default in an accordion. Click title to expand/collapse? 

**Manage users**
- [ ] Update 'Admin' column to 'Account type'
- [ ] Replace 'make/unmake admin' button with dropdown list containing 'general' and 'admin'

**Comment by philipgrimmett** [comment]
@aneesha09 some more fleshed out admin concepts for us to discuss in the new year:
https://invis.io/PXPLQIAEWNR

I've added you to the invision doc so you should be able to add comments.

**Comment by aneesha09** [comment]
Thanks @philipgrimmett

**Comment by aneesha09** [comment]
Closing as moved to separate UX and dev tickets
