### ISSUE TITLE
Links not working on staging

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1890]
### Problem description
On staging the following links lead to a 500 error:
1. About 
2. Privacy Policy

![error___data_gov_au_-_beta_and_trip_summary__confirmed_](https://user-images.githubusercontent.com/40556131/49411492-32ebe480-f7bd-11e8-9510-1d0458acbbf5.png)

**Comment by nahidakbar** [comment]
this looks done

**Comment by AlexGilleran** [comment]
Yeah it's fixable in config, I'll close this when I PR the config changes 👍

**Comment by aneesha09** [comment]
Hey guys... We closed this on the physical board. Could you please close it here too?
