### ISSUE TITLE
Selected chart icon is a purple square

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1891]
### Problem description
Selected chart icon is a purple square.

### Screenshot / Design / File reference
Looks like: ![image 1](https://user-images.githubusercontent.com/900555/49411436-0932bd80-f7bd-11e8-807e-de66bc70399e.png)

Should look like ![image](https://user-images.githubusercontent.com/900555/49411522-52830d00-f7bd-11e8-8be6-bedee5082c90.png)

**Comment by t83714** [comment]
It looks works on Master:
https://dev.magda.io/dataset/ds-dga-fa0b0d71-b8b8-4af8-bc59-0b000ce0d5e4/details?q=credit
I guess this PR https://github.com/magda-io/magda/pull/1875 was only merged into master 
And the staging site probably is on 0.0.50 branch?

**Comment by AlexGilleran** [comment]
I'll try rebasing that on top of 0.0.50 and see if it helps!

**Comment by AlexGilleran** [comment]
Actually looks like this was specific to the dodgy deploy I did on staging, having redone the deploy it's working much better: https://staging.search.data.gov.au/dataset/ds-dga-786ce033-0b01-4189-8bc9-fcbbfe2b87a6/details?q=
