### ISSUE TITLE
Chart preview not working in IE

### ISSUE THREAD

**Issue by MelanieHotchkiss** [magda-io/magda#1893]
### Problem description
Chart preview not working in Internet Explorer

### Screenshot / Design / File reference
![image.png](https://images.zenhubusercontent.com/5ac7000f4b5806bc2bcde19f/541acf80-0100-4228-8a92-9accfde68425)

**Comment by t83714** [comment]
@MelanieHotchkiss 
could you please try if this one:
https://dev.magda.io/dataset/ds-dga-fa0b0d71-b8b8-4af8-bc59-0b000ce0d5e4/details?q=credit
works on IE?
If so, we probably just need to merge the master to staging site branch.

**Comment by t83714** [comment]
@AlexGilleran 
Closed it as `master` branch (https://dev.magda.io) works on @MelanieHotchkiss 's laptop as well.
If the fix should be included by `0.0.50` release, a merge from `master` to `release/0.0.50` probably would do it.
