### ISSUE TITLE
Reword email validation text

### ISSUE THREAD

**Issue by philipgrimmett** [magda-io/magda#1895]
### Problem description
When an invalid email address is entered we display the text "email is invalid". Wherever possible we should provide actionable (polite) guidance, in this instance something closer to:
> **Please enter a valid email address** 

### Problem reproduction steps
1. Enter "notvalidemail.com" into a required email form field (suggest a dataset)
2. Click submit, view error

**Comment by nahidakbar** [comment]
@philipgrimmett do you remember which form this was in?
