### ISSUE TITLE
Static Page content will not load if switch between static page

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#1896]
### Problem description

This only happens when you on a static page (.e.g about page) then click another static page link (e.g. `privacy policy`)

The issue probably is around here:

https://github.com/magda-io/magda/blob/a17348eb67b1eb0afac51f118d5ec8018a0c9f04/magda-web-client/src/Components/StaticPage.js#L16

the `componentDidMount ` will never be fired if you switch between different static page.

Put to low priority as the chance that it happens could be very low.

### Problem reproduction steps

- go to https://dev.magda.io/page/about
- Click the `Privacy Policy` link on footer
- You will see the loading message stays there forever

### Screenshot / Design / File reference

![image](https://user-images.githubusercontent.com/674387/49415669-8402d500-f7cb-11e8-8119-68bd4a6f7223.png)

**Comment by AlexGilleran** [comment]
Changing this to a showstopper because it's a regression, great catch @t83714
