### ISSUE TITLE
Text associated with search facet buttons is inadequate (med)

### ISSUE THREAD

**Issue by MelanieHotchkiss** [magda-io/magda#1917]
### To-Do to fix:
Add alt/title text to each filter:

Filter: [filter text]

Dev note: this would require updating the title text to match the current filter state. I assume this is possible? - @philipgrimmett 

### Problem description
Intopia issue 20 - Screen reader users are not given clear information about the functionality and purpose of the facet buttons.

### Problem reproduction steps
Giving the alt attribute a null value, alt=”” changes the announcement to “clickable any organisation button”, which is an improvement but still not very clear. Expanding the text to be more informative would likely cause design issues.
Therefore, consider inserting a line or two of visible text above the search facet buttons that tell the user what to do. This would likely benefit all users, and definitely those using screen readers.

### Screenshot / Design / File reference
[20] Text associated with search facet buttons is inadequate
Type: WCAG 2.1 failure
Fails 3.3.2 Labels or Instructions - Level A
Location: Search facet buttons, Search page
Platform: Desktop
Severity: Medium
What’s the issue?
Screen reader users are not given clear information about the functionality and purpose of the facet buttons.
Why it matters
Each search facet button consists of a button element wrapped around an SVG with text overlaid. The SVG is given an alt attribute. The result is that screen readers announce the first button (for example) as “clickable organisation graphic, clickable any organisation button”.
Our recommendation
Giving the alt attribute a null value, alt=”” changes the announcement to “clickable any organisation button”, which is an improvement but still not very clear. Expanding the text to be more informative would likely cause design issues.
Therefore, consider inserting a line or two of visible text above the search facet buttons that tell the user what to do. This would likely benefit all users, and definitely those using screen readers.

**Comment by philipgrimmett** [comment]
@t83714

**Default**
Filter: any organisation
Filter: any location
Filter: any date
Filter: any format

**Active**
Filter: Department of Finance
Filter: STE New South Wales
Filter: from Jan 2012 - May 2018
Filter: CSV, JSON
