### ISSUE TITLE
Searching by state is super slow

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1928]
### Problem description
This was always true, but now in the search.data.gov.au we have many more datasets with spatial information, which means that searching by WA is so slow that it can't even complete under 30 seconds.

We need to figure out some way to fix this.

My hypothesis is that we should be able to simplify the polygons more... we already do this to an extent, but we need to be absolutely _brutal_ with it - like no more than 10 vertices.

There's also a possibility of tuning the ES shape query better, or using the new `geo` type.

### Problem reproduction steps
Filter anything by WA... but do it on dev if you can because if enough people do this on prod it causes all the other searches to slow down :(.

**Comment by t83714** [comment]
This API might be useful for us:
https://docs.mapbox.com/android/api/mapbox-java/libjava-geojson/3.0.1/index.html
```
public static java.util.List<Point> simplify(@NonNull
                                                      java.util.List<Point> points)
Reduces the number of points in a polyline while retaining its shape, giving a performance boost when processing it and also reducing visual noise.
Parameters:
points - an array of points
Returns:
an array of simplified points

```

**Comment by t83714** [comment]
Closed via PR 2116
