### ISSUE TITLE
Fix or ignore snyk security issues

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1944]
### Problem description
=== By reading further you accept that you're NOT an evil cyber hacker bent on destroying our project ===

Now we've got that out of the way, adding snyk to our project ~has~ may or may not have come up with a bunch of security warnings for out of date packages. When I did a quick scan of these I found that most of them weren't really vulnerabilities (e.g. NodeJS DDoS in a library we only use in the frontend) but we should go through them and either fix them or ignore them as appropriate.

### Problem reproduction steps
- Get an invite to Snyk.io from @t83714 or @AlexGilleran and have a look through.

**Comment by aneesha09** [comment]
Add issues here - https://docs.google.com/document/d/1NbaInZMsKLmw5lvgfVZ8-mk8VJSZ1NBImqdf7K7ywuY
