### ISSUE TITLE
Search results return twice as many records as the original catalogue.

### ISSUE THREAD

**Issue by MelanieHotchkiss** [magda-io/magda#1947]
### Problem description
The overall search returns 3150 results; the original catalogue contains 1575 records.

### Problem reproduction steps
Investigation

**Comment by AlexGilleran** [comment]
Looks like this is due to multiple crawls happening under different connector id names, resulting in different ids. We either need to manually delete the duplicate records or delete everything and recrawl.

**Comment by AlexGilleran** [comment]
Manually deleted the duplicated records, agriculture is back to the right number now.
