### ISSUE TITLE
Text highlighter colour looks too similar to background

### ISSUE THREAD

**Issue by MelanieHotchkiss** [magda-io/magda#1948]
### Problem reproduction steps
Invert colour scheme for highlighted text i.e. white background and dark text. Do this only in the search bar, not everywhere in the application.
- Check with Phil once he is back / Alyce after Wednesday

### Screenshot / Design / File reference
https://trello-attachments.s3.amazonaws.com/5bfe06d0ee33aa32f1c25f82/5c12f37c3df6b387a89e52c2/2d12f1c3909de1ea69ff0eca7fc29d5b/highlighted_text_colour.PNG

**Comment by nahidakbar** [comment]
![image](https://user-images.githubusercontent.com/3362993/50615947-a018a400-0f3a-11e9-95d1-0a13011154f6.png)
hope this is gud enuf
