### ISSUE TITLE
/dashboard is not handled by CKAN redirect

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1961]
### Problem description
Just did a quick test logging into data.gov.au and changing the host to search.data.gov.au. While the `/user` route works (redirects to data.gov.au/dashboard), the `/dashboard` one results in a 404 on search.data.gov.au. This should redirect to data.gov.au/dashboard similar to the other CKAN-only routes.

**Comment by maxious** [comment]
Ah, if you were logging in and we had moved the dashboard to /data/dashboard that would happen automatically in the login process. But easy enough to add another redirect if someone has a old dashboard bookmark or something.
