### ISSUE TITLE
Metadata fields missing

### ISSUE THREAD

**Issue by MelanieHotchkiss** [magda-io/magda#1966]
### Problem description
The current mappings to catalogue fields will need to be defined, and other fields will need to be added (e.g. security classification, status, etc).but for the time being, descriptions are missing (see screenshot),

### Problem reproduction steps
For now, we will copy the dataset description to show for the distribution. So for this dataset it would show "The Livestock Exports by Air report is compiled from information in the end of journey reports and includes statistics on mortalities."

### Screenshot / Design / File reference
https://trello-attachments.s3.amazonaws.com/5bfe06d0ee33aa32f1c25f82/5c12f6822a99e409ff1484f5/4c250a56f032e9037301bdf63c74e914/missing_description.PNG

**Comment by AlexGilleran** [comment]
Fixed by #2016
