### ISSUE TITLE
SPIKE: Investigate - System-level logging & monitoring+alerts

### ISSUE THREAD

**Issue by kring** [magda-io/magda#197]
The system does not alert for any errors at present. We should have system-level monitoring and alerts in place. 

Using ELK Stack maybe - does logging & monitoring both

Output for the investigation:
1. See what kind of tools are available
2. What are the best practices for logging and monitoring
3. Discuss with the team and decide on a logging & monitoring approach
4. Figure out which part of the application we will start piloting this on

**Comment by aneesha09** [comment]
Related - https://github.com/magda-io/magda/issues/1582
