### ISSUE TITLE
Change terminology for data rating

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#1980]
### Problem description
As a DGA user
I want to see linked data rating described more accurately
So that I don't confuse it with data quality

### Acceptance Criteria

- [x] On the dataset page, change label "Open Data Quality" to "Linked Data Rating"
![global_seagrass_species_richness_-_world_conservation_monitoring_centre_2003___datasets___dev](https://user-images.githubusercontent.com/40556131/50942399-af6c9400-14dc-11e9-8cb1-a77b617ced09.png)

- [x] Change link in tooltip from "Open Data Quality" to "Linked Data Rating"

- Changes to the Dataset Quality page
- [x] Change URL of page - https://<domain>/page/dataset-quality to https://<domain>/page/linked-data-rating

- [x] Update labels in breadcrumb, page title, accessibility alt text and labels to "Linked Data Rating"

- [x] Change "How we calculate open data quality" to "How we calculate the linked data rating"
- [ ] Change text -
Our **linked data ratings** are an automatic rating based on the licensing, format and availability of data, derived from (but different to) Tim Berners-Lee’s 5-star linked data system.

**Comment by AlexGilleran** [comment]
Will require changes to the frontend (just copy text and urls), as well as a database migration to move the quality page to the new URL.
