### ISSUE TITLE
DB Usage is super high on data.gov.au

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1993]
### Problem description
Right now we're having to use a lot of CPU cycles for the production database on data.gov.au. This looks to be because even with indices in the right places, the way that registry looks up the old data.gov.au slugs (by querying `ckan-dataset.name` and others) somehow slips through a crack in postgres and avoids the index no matter how you specify it. So we need to find a different way to do it.

**Comment by t83714** [comment]
Closed via PR https://github.com/magda-io/magda/pull/1995
