### ISSUE TITLE
Fix Licenses for GA ECAT CSW Responses

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1997]
### Problem description
GA have a new CSW endpoint at https://ecat.ga.gov.au/geonetwork/srv/eng/csw. However when Magda connects to it the licenses aren't getting through, although they are in there (https://ecat.ga.gov.au/geonetwork/srv/eng/csw?service=CSW&request=GetRecords&version=2.0.2&outputSchema=http://standards.iso.org/iso/19115/-3/mdb/1.0&resultType=results&elementSetName=full&startPosition=1&maxRecords=5). Presumably this is because they're in a new place, we should modify the CSW Connector to check that place for licenses.

### Problem reproduction steps
Point a CSW connector at https://ecat.ga.gov.au/geonetwork/srv/eng/csw

**Comment by maxious** [comment]
Another fix under this issue, the source URL should at least be a mdb:metadataLinkage but for GA they have a special link:
```
cit:identifier>
<mcc:MD_Identifier>
<mcc:code>
<gco:CharacterString>
http://www.ga.gov.au/metadata-gateway/metadata/record/14802/
</gco:CharacterString>
</mcc:code>
<mcc:codeSpace>
<gco:CharacterString>ga-dataSetURI</gco:CharacterString>
</mcc:codeSpace>
</mcc:MD_Identifier>
</cit:identifier>
```
