### ISSUE TITLE
Empty source link shows as a working link in UI

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2006]
### Problem description
Datasets like this:
https://data.gov.au/dataset/ds-listtas-f7122469-cf06-4a69-a446-8e28f2c65d16/details?q=soil%20condition%20evaluation

... don't have a source link to go to, but it still shows up with `href=""`, which means that it just links to itself.

If there's no source link, there should be no link, it should just be plain text.

**Comment by aneesha09** [comment]
Need to fix this for when Env datasets are on internal Magda
