### ISSUE TITLE
SPIKE - Integration with ADFS Login

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#2008]
### Problem description
Investigate what we need to do to integrate with ADFS for single sign-on

**Comment by maxious** [comment]
AFAIK the VANguard Federated Authentication Service allows access to many government ADFS services via a single API but there is probably a cost associated with that. https://web.archive.org/web/20180502162357/http://www.vanguard.business.gov.au:80/ourservices/Pages/Federated-Authentication-Service-(FAS).aspx

**Comment by t83714** [comment]
@maxious Thanks for the info 👍 
Do you know where we can find more details of it. e.g. the protocol document?

**Comment by maxious** [comment]
"The FAS currently supports the WS-Federation Protocol https://en.wikipedia.org/wiki/WS-Federation only. SAML protocol support may be added at a later time.
The service returns SAML 1.1 tokens for maximum compatability with existing Vendor products. SAML 2 products may be available in the future." https://web.archive.org/web/20180316024001/http://www.vanguard.business.gov.au/Documents/VANguardServicesCatalogue.pdf

You might need to email industry.engagement@industry.gov.au

**Comment by t83714** [comment]
Thanks a lot!

**Comment by AlexGilleran** [comment]
Scheduled a meeting with industry for next week 😎

**Comment by nahidakbar** [comment]
Seems like https://github.com/auth0/passport-wsfed-saml2 is the common option for doing both Vanguard FAS and ADFS with passport.js. I am not seeing a lot of public vanguard specific documentation which can be both a good and a bad thing.
