### ISSUE TITLE
Search datasets API returns facets options in wrong order sometimes

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2015]
### Problem description

Two issues:
- Search API Seems NOT sort facets options correctly sometimes.
  - A options with 0 `hit count` can be returned as the first option sometimes
- Format facets sometimes returned with an invalid identifier:
  - e.g.  returned an identifier appeared to be an organisation id:
```
hitCount: 0
identifier: "org-aodn-Integrated Marine Observing System (IMOS)"
matched: true
value: "png"
```

### Problem reproduction steps

Send the following request to search API (dev site master branch):

https://dev.magda.io/api/v0/search/datasets?query=*&publisher=Department%20of%20Environment%2C%20Land%2C%20Water%20%26%20Planning&publisher=Geoscience%20Australia&publisher=CSIRO%20Oceans%20and%20Atmosphere%20-%20Information%20and%20Data%20Centre&format=pdf&format=zip&format=xlsx&format=csv&format=wms&format=tiff&format=png&region=STE%3A4&start=0&limit=11

You will got the following response (see screenshot):

![image](https://user-images.githubusercontent.com/674387/51882332-aa5f7e00-23d2-11e9-9e7f-f078abb2f3b7.png)

Problems are:
- Option `Department of Environment, Land, Water & Planning` with 0 hitCount shouldn't returned as the first option
- Option `png` with 0 hitCount shouldn't returned as the first option
- Option `png` shouldn't come with an `identifier` `org-aodn-Integrated Marine Observing System (IMOS)` (looks like an organisation id)

**Comment by AlexGilleran** [comment]
> Option png shouldn't come with an identifier org-aodn-Integrated Marine Observing System (IMOS) (looks like an organisation id)

Wtf! I think this is the whackiest bug I've seen so far 😬
