### ISSUE TITLE
Stop travis flakiness

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2020]
Travis now fails maybe 50% of the time?

We should get this fixed, it's slowing us down immensely.

It seems to be caused by the recent changes to the way the indexer catches up - sometimes it just locks up and doesn't move. We should find some way to stop that from happening, even if it means removing (preferably replacing) a test.

**Comment by t83714** [comment]
Based on my tests, it seems the freeze has something with do with test case in [StreamSourceControllerTest.scala](https://github.com/magda-io/magda/blob/master/magda-indexer/src/test/scala/au/csiro/data61/magda/indexer/helpers/StreamControllerTest.scala)

I thought I could fix it by change the `AsyncFlatSpec` to `FlatSpec`. But it will make the logic wrong --- the test cases will always success.

I think there could be some logic issue in `StreamSourceController.scala` but couldn't figure it out.

Probably leave to you to have a look~ @AlexGilleran
