### ISSUE TITLE
When searching for Register of Native Title Claims, the dataset with the exact title comes 5th

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2025]
### Problem description
E.g. https://data.gov.au/search?q=Register%20of%20Native%20Title%20Claims

Somehow despite having 3 stars, the dataset that matches the title exactly comes 5th behind some less relevant and worse quality datasets.

Need to investigate why this is, definitely doesn't seem right to me.

**Comment by gordjw** [comment]
@AlexGilleran I'm not sure if this is related, but didn't want to start a new issue without checking:

Looking for this dataset "[Street furniture including](https://data.gov.au/dataset/ds-melbourne-https%3A%2F%2Fdata.melbourne.vic.gov.au%2Fapi%2Fviews%2F8fgn-5q6t/details)"

No results are returned when searching by [exact title](https://data.gov.au/search?organisation=data.melbourne.vic.gov.au&q=%22Street%20furniture%22) (where the terms aren't also in the description)

[Searching by description](https://data.gov.au/dataset/ds-melbourne-https%3A%2F%2Fdata.melbourne.vic.gov.au%2Fapi%2Fviews%2F8fgn-5q6t/details?q=%22City%20of%20Melbourne%20owns%20and%20maintains%20various%20objects%20and%20pieces%22) or [non-exact title](https://data.gov.au/search?organisation=data.melbourne.vic.gov.au&q=Street%20furniture) works though!

**Comment by AlexGilleran** [comment]
@gordjw thanks for that - looks slightly different though, I've created #2037 :)
