### ISSUE TITLE
Registry History API has problems

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2042]
### Problem description
For the history api you can page through the same way as other Registry API calls using `?start=` and `?limit=`, but we don't mention this in the docs: https://data.gov.au/api/v0/apidocs/index.html#api-Registry_Record_History-GetV0RegistryRecordsRecordidHistory

We should add it.

We're also finding that if you use the history api with ?limit=1 (DO NOT DO THIS ON PROD), it uses an insane query plan that causes the CPU to shoot up to 100%. We can fix this by changing the SQL so that instead of using `order by eventId asc` it uses `order by eventTime asc`.

### Acceptance Criteria
- `start` and `limit` parameters are present in the API Docs for record history API
- It's possible to rapidly make a number of requests to the record history api with `limit=1` as a query parameter without causing high CPU usage on the database

### Technical Notes
- Look into Postgres' `EXPLAIN` feature (especially via PGAdmin 4) to see the difference in query plans between using `order by eventid asc` and `order by eventtime asc`.

**Comment by t83714** [comment]
It seems history API support `pageToken` parameter as well~ see [here](https://github.com/magda-io/magda/blob/master/magda-registry-api/src/main/scala/au/csiro/data61/magda/registry/RecordHistoryService.scala#L74)
We should add this to document as well as `pageToken` should work faster than `start` (thanks to @kring  👏 )
