### ISSUE TITLE
SPIKE - Investigate various ways fingerprint a file

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#2057]
### Problem description

Use hashes for exact duplicate matches 
Find out which way would work for this
Disregard fuzzy or similar duplicate identification

Expected output:
Approach for fingerprinting that meets above criteria, any libraries if needed?

**Comment by nahidakbar** [comment]
For context:

* We can't use file content directly to compare - privacy matters
* Input files may be _compressed_ vs. _not compressed_ . e.g. kmz file vs csv file
* Input data may be encoded as _text_ vs _binary_ based. e.g. csv vs shp files

## For _exact matches_

TLDR: use CRC32

CRC pre-dates software engineering as far content hashing goes. Should be able to find/make very efficient js implementations. 32 bits should be enough unless we are scaling to billions of datasets. In which case, the hashing algorithm will be one of the last things we will have to upgrade.

### Additional for for text data

For text data, we can decide to make things more complex by:

* removing or standardising white-space
* ignoring case (converting all data to a single case)
* for foreign language files and different character encodings, we could try changing things to a standard encoding (e.g. ascii using unidecode, or utf8)

Don't think these are worth it for MVP. In the long run, would not implement unless there is explicit business requirement for doing one or more of these.

**Comment by nahidakbar** [comment]
Ran a small simulation.

Results

![image](https://user-images.githubusercontent.com/3362993/53146098-0c3c8d80-35f7-11e9-8e18-d799f76b54ca.png)

Red = most similar; blue = least similar

Set up 4 documents to test different size documents and also subtle differences:

* Document 1 is a 15 byte long document all filled with 0.
* Document 2 is a 64 byte randomised document.
* Document 3 is a 5 mb randomised document.
* Document 4 is a the same as document 3 with one byte different.

Different fingerprints were used (bloom and bloom count with 3 different bin setting and tally hash  = freq)

Expect no similarity between document 1 and 2 and 3. Expect document 3 and 4 to be pretty similar.

In that respect
* Bloom filter seems to be pretty inaccurate (as it is lacking bits)
* Bloom count filter does a lot better even at low bins. Bloom count seems to outperform tally hash

**Comment by AlexGilleran** [comment]
Further investigation happening in #2075
