### ISSUE TITLE
Create a sample story of the new Access Control Model

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2091]
### Problem description

We need a sample story of the new Access Control model. 
This sample story here is not intended to be part of the new access control model proposal. 
Instead, the sample story is created to demonstrate:
- a sample template
- possible compulsory conceptual elements that should be provided as primitive building blocks for configuring any supported client org structure levels & access level requirements
- Evaluate the possible boundary / supported client org structure levels of the similar type story

### Acceptance Criteria

The story should includes:
- Definition of the compulsory conceptual elements that will be available as primitive building blocks for configuring any supported client org structure levels & access level requirements
- Describe an example story of how to configure a sample client org structure using predefined built-in blocks / options.
- Discuss any possible limitation of this story. i.e. the possible type of org structures / access controls it can support
- This sample story doesn't need to cover all aspects of access controls. Can focus only one area i.e. datasets / resource access control
- This sample story can stay at conceptual level and doesn't need to cover the technical implementation details

**Comment by t83714** [comment]
Here is the sample story I created:
https://docs.google.com/document/d/1BKKRGH6X6nVSPGKuGP5mTFkoS26qOy0FYMPKwrT8U1c

**Comment by AlexGilleran** [comment]
Well done @t83714 , looks like a massive effort! A few comments:

- When you talk about someone creating a catalogue, do you mean an unpublished dataset (the kind that we talk about being created when someone is cataloging)?
- I'm not sure if this is inherent to your solution, but it'd be better if we didn't treat org units as special - ideally we should create a role system that supports them but they shouldn't be a first-class citizen

**Comment by t83714** [comment]
@AlexGilleran 

- > When you talk about someone creating a catalogue, do you mean an unpublished dataset (the kind that we talk about being created when someone is cataloging)?

Yes.  You are correct. (I also updated the following details to section 2.3.1.2 Data Catalogue )
Every data catalogue comes with a `Draft` property to indicate whether a catalogue is a draft or published.

All data catalogued created by default will be `Draft` catalogued. 

Only operations `Publish Catalogue` (OP011) or `Unpublish Catalogue` (OP012) can change the value of the `Draft` property:
- `Publish Catalogue` (OP011): makes the `Draft` property set to false
- `Unpublish Catalogue` (OP012): makes the `Draft` property set to true

> I'm not sure if this is inherent to your solution, but it'd be better if we didn't treat org units as special - ideally we should create a role system that supports them but they shouldn't be a first-class citizen

The purpose of defining a org unit resource is for providing a short-cut to easily establish access control implicitly at user level & org level. i.e. It's aimed at serving the following scenarios: 
- User should at least be able to (by default) edit the resources he created (so he can fix thing without higher level permission)
- People within the same org unit should be able to (by default) access the resource within the org unit (and any org units at lower levels)

It's definitely possible to define this in multiple way and this might not be the way suit our situation.

**This document is more for showing `we need a document like this` rather than `we need this solution`.**

I think the `making each resource owned by one-to-many roles` idea you mentioned could provide an alternative solution for this?

We probably can talk about that idea more on our meeting?
