### ISSUE TITLE
Clicking out of search filter causes the results to refetch

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2092]
### Problem description
On data.gov.au currently, if you open a filter dropdown then click out of it, nothing happens (as you'd expect).

On `master`, if you do the same thing it reloads the search results that you already had, which is a bit jarring.

It'd be good to put it back the way it was before we release again.

### Problem reproduction steps
- Go to search page
- Click the "Organisations" dropdown
- Click outside the organisations dropdown
- Notice that the results disappear and reappear, loading bar appears, another GET request is made.

**Comment by aneesha09** [comment]
I think we should fix this. @AlexGilleran - Please add an estimate? 
Moving it to backlog.

**Comment by AlexGilleran** [comment]
Done :)
