### ISSUE TITLE
Investigate Vanguard Integration for Dept of Ag

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#2165]
DAWR use another SSO and also have Vanguard deployed as per information received from Dept of Industry. We have to validate whether the vanguard SSO will work in the Ag technological environment. Investigate using the sandbox, try to integrate with the Dept of Ag, deploy it to a preview environment and coordinate with Rodrigo to test if it works.

Also check if we can even test this using the sandbox access to vanguard or what else we need?

Store the keys in a different solution not the repo.

**Comment by AlexGilleran** [comment]
Agriculture SSO through VANguard is confirmed 👍
