### ISSUE TITLE
Investigate Esri Oauth support

### ISSUE THREAD

**Issue by rowanwins** [magda-io/magda#2167]
Hi Magda team

For a Terria project we have a requirement to display Esri services that are only available to authenticated users. @kring has suggested that we look at implementing an Esri Auth provider within magda to help facilitate this.

Esri offers an [OAuth2 endpoint](https://developers.arcgis.com/rest/users-groups-and-items/authentication.htm) which is helpful.

When it comes to Magda from what I can tell the existing OAuth providers (eg Google, Facebook) are catered for within the [magda-gateway/src/oauth2/](https://github.com/magda-io/magda/tree/28ce9fd1a7f711f1380b22596d6bfc71f8cb8d8d/magda-gateway/src/oauth2) directory. It looks like these integrations are managed using passport.js, good news is there is an [ArcGIS strategy](http://www.passportjs.org/packages/passport-arcgis/) already. So I'm hopeful that I/we could largely follow the existing patterns that have been established.

The front-end login components appear to be managed within [magda-web-client/src/Components/Account/Login.js](https://github.com/magda-io/magda/blob/eef14055ae7a81fd58cad839e21a2be06874f811/magda-web-client/src/Components/Account/Login.js).

All in all this seems fairly achievable, it feels like a lot of the pieces are already there and patterns have been established within Magda. Is there anything major that I'm missing or need to be aware of?

I'm happy to take a look and see how far I get although I'm sure I'll need a bit of hand holding as I familiarise myself with magda & typescript.

Cheers
Rowan

**Comment by AlexGilleran** [comment]
Sorry for the tardy reply, I think this happened when I was on holiday. But yep sounds like you've got it all figured out really :).

Only other thing that you might need to do is make it work via the UI, but possibly Terria is going to have some kind of alternate UI log in mechanism?
