### ISSUE TITLE
Wrong WMS layer used in preview of DGA-scraped dataset

### ISSUE THREAD

**Issue by steve9164** [magda-io/magda#2209]
### Problem description

The preview on https://data.gov.au/dataset/ds-dga-c85517ed-1a1e-47b3-bd9c-9ee87a5c481c/details?q=mobile%20black%20spot%20round%204 is for the wrong WMS layer. There is a WMS layer for that specific dataset that should be used. Navigating to the [DGA](https://data.gov.au/data/dataset/mobile-black-spot-program-round-4-funded-base-stations/resource/a9b507ce-f8ce-4aa7-973a-f9d337c7bb4d) entry for that dataset & distribution gives the correct preview.

### Screenshot / Design / File reference
Incorrect preview
![image](https://user-images.githubusercontent.com/13863530/57666495-789dba80-7643-11e9-9b4e-0238e6c0d7a3.png)

Correct preview
![image](https://user-images.githubusercontent.com/13863530/57666511-8b17f400-7643-11e9-9fd7-a06ada65d1b7.png)

**Comment by kring** [comment]
Magda is probably not looking at the `wms_layer` field on the distribution (because it's a custom field, only on DGA), and instead just showing the first layer on the WMS server.

**Comment by t83714** [comment]
fixed in https://github.com/magda-io/magda-preview-map/issues/11 & #3174

**Comment by t83714** [comment]
fixed in PR: https://github.com/magda-io/magda/pull/3180
Now you can select WMS layer when more than one is available
