### ISSUE TITLE
Vocabulary Tool for Keywords & Themes

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#2228]
As a Magda User
I want keywords to be constrained by a defined vocabulary
So that the data quality is better

### Acceptance Criteria:
1. Make keywords and themes work like predictive search /suggestions so that the user gets an idea of what is already existing in the vocabulary E.g. asic could auto-complete to ASIC. Department of Agriculture and Water Resources is always called that in that format.

**Comment by t83714** [comment]
More details on this:
- Will use https://vocabs.ands.org.au linked data APIs as the main source of vocabulary
  - The APIs comes with different endpoints for vocabularies in different areas/domains. We will query multiple endpoints and combine the result depends on the configuration
  - We will use the `prefLabel ` field (and `en` language) of each vocabulary entry
- The list of API endpoints will be configurable through `magda-web-server` pod (and will be passed through web.json config map to frontend like other config values)
- For keyword input, this feature will not get rid of the current keyword extraction feature (based on NPL - natural language processing). Instead, we will make sure the result of the NPL will only be added to the keyword input if it's on vocabulary API result.

**Comment by AlexGilleran** [comment]
@t83714 for filtering we probably want to make sure that we're allowing labels that aren't preflabels through as well 👍 . Or taking the labels that aren't preferred and turning them into preferred ones.

**Comment by t83714** [comment]
@AlexGilleran 
The returned result items are similar to:
```json
{
  "_about": "http://www.neii.gov.au/def/voc/ACLUMP/australian-land-use-and-management-classification/Wood-production-forestry",
  "broader": [
    {
      "_about": "http://www.neii.gov.au/def/voc/ACLUMP/australian-land-use-and-management-classification/Production-native-forests",
      "prefLabel": {
        "_value": "Production native forests",
        "_lang": "en"
      }
    }
  ],
  "dctermsCreated": "2017-12-06T01:22:13Z",
  "definition": "Area managed for sawlogs and pulpwood.",
  "notation": "2.2.1",
  "prefLabel": {
    "_value": "Wood production forestry",
    "_lang": "en"
  }
}
```
Most of them don't have `broader` but everyone has a `prefLabel`.
It looks like there is no other options? Any good suggestions?
