### ISSUE TITLE
SPIKE - Track views and interactions on dataset

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#2231]
Investigate open source analytics libraries to plug-in.
The library should:
1. Allow tracking of views
2. Allow tracking of interactions on the dataset page
3. Allow tracking user information about who viewed/interacted a dataset by using parameters
4. Allow tracking of user logins
5. Allows reporting of the collect data manually and by plugging metrics into a UI

**Comment by t83714** [comment]
It's a crowded space where you can find a lot of solutions.
But when it comes to the following two aspects, they're not too many options left:
- Provide built-in, is capable of or provide help of complex user interaction tracking based on front-end event capture
  - Our frontend is a SPA (single page application) that may require this kind of capability from time to time
  - We may require this kind of capability to provide deep analysis. 
- A solution that allows us to pull analytics data (or host data by ourselves) to create our own reports in our own UIs

I evaluated the solutions mostly in the following three categories:

- Frontend tracking library. Clarity JS and others: https://blogs.bing.com/webmaster/november-2018/Introducing-Clarity-a-web-analytics-product
  - https://github.com/microsoft/clarity-js
  - A Microsoft project.
  - We probably can host data in an elastic index as part of our solution
  - Allow you to track more details data for further analysis (e.g. which area user interacts more on the page or ) 
  - Still not very mature
  - We probably don’t need the power
  - This might not be the option we're after

- matomo (formly Piwik)
  - Allow you to host your own solution
  - Access tracking data through API (thus, create a report using data from APIs )
    - https://developer.matomo.org/api-reference/reporting-api
    - 
  - Managing user consent API. 
    - You still need to build your own UI. We probably don't need this feature
  - Require MySQL DB --- we need to have a DB container for dev and probably a Cloud Mysql option for production
    - This adds more complicity 


- Google Analytics + autotrack.js + Google Analytic Report Data API 
  - https://github.com/googleanalytics/autotrack (ga plugins)
  - autotrack plugin could save us a lot of effort on front code e.g.
    - cleanUrlTracker
    - urlChangeTracker
    - eventTracker
    - max-scroll-tracker
  - We can build reports using Google Analytics Reporting API API:
   - https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-js
  - By looking at the code, it seems Google has spent some time on pave the gaps between different browsers & solve tricky frontend problem. We probably want to leverage this.

My personal preference is: `Google Analytics + autotrack.js + Google Analytic Report Data API`.

Let me know your ideas 😄

**Comment by t83714** [comment]
Since our new UI design includes deep integration with dataset stats. data, we may want to reconsider our position on solution selection in this area.
Probably build a simple solution ourselves is a more viable option as we may want to search & sort dataset by that stat. data (e.g. get top 10 most read dataset) --- this may require stat. data to be stored in elastic search~

**Comment by AlexGilleran** [comment]
Spike is done, will refine in https://github.com/magda-io/magda/issues/2351.
