### ISSUE TITLE
Notifications - Prototype

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#2242]
As a Magda user
I want to be able to notify a data approver
So that they can review and approve my submitted dataset

### Acceptance Criteria:
1. At the end of the add dataset flow, allow the user to enter a name and email address to notify on for dataset approval
2. Notify this user on the specified email address that they have a dataset to approve
3. User associated with the approver email address should see this dataset in their "datasets to approve" list

Assume that the email address is always going to be a Magda user email address

### Dev Notes:
1. Use notifications API, not correspondence API to create this functionality
2. Refer to #2219 for investigation details

**Comment by AlexGilleran** [comment]
Replacing with https://github.com/magda-io/magda/issues/new
