### ISSUE TITLE
Consolidate Agency Magda Login Access

### ISSUE THREAD

**Issue by aneesha09** [magda-io/magda#2244]
As a user
I want to be able to use only one login and password to access Magda
So that I don't have to maintain different passwords for different layers for access.

### Acceptance Criteria:
1. Remove the instance password / change it to use the same login password as Magda
2. Without logging in, a user should not be able to search through internal department datasets. Instead Magda should show a not-logged-in home page. This should ask the user to log in to progress to use Magda. It should provide some introductory text about Magda helping user understand why they should log in. E.g. "Welcome to Magda. Here you can see and find datasets in the department-wide catalogue. To be able to access your department catalogue, please log in using your login information or create an account if you don't already have one".
3. Upon logging in, the user is taken to the logged in home page.
4. Login persists for the session duration across pages, shouldn't accidentally log out if you go to a different page e.g.

**Comment by aneesha09** [comment]
@AlexGilleran / @t83714 - Please review and estimate

**Comment by aneesha09** [comment]
@alyce - We may a design for this one depending on what the devs need.

**Comment by t83714** [comment]
Probably can be:
- item 1: create an OPA policy to secure all UI route / URL
  - This policy will cover all react-router routes [here](https://github.com/magda-io/magda/blob/41b9906b3d8d3b1a283c51af3ee833caa80ef302/magda-web-client/src/Routes.tsx#L91). e.g. `/admin/home`, `/suggest` or `/login` etc.
  - A route will only be added to `<Switch>` if the current user has access to it
  - The current home page should be moved from the root path `/` to something like`/homePage`
    - root path`/` will always be a redirection to a default path (the first available path)
  - The list of available UI paths will be simply part of the policy
    - We can change the setting by updating this policy
  - Estimate: 5
- Item 2: Modify Authentication API OPA proxy router to allow JSONP response type
  - allow frontend to retrieve a list of available paths in a sync way
  - Estimate: 3 
- Item 3: modify current content API policy to make the header link decided by UI path
  - estimate: 5
- Items 4: Modify the Routes.js to add route based on opa policy outcome

**Comment by AlexGilleran** [comment]
We'll also need to:
- Swap out `isAdmin` with an admin role from OPA in all the services
- Add the ability to restrict what are currently unauthenticated APIs (e.g. most GETs in registry, correspondence etc) to users with certain roles, without breaking data.gov.au

**Comment by t83714** [comment]
@AlexGilleran I tried to break the two requirements you've mentioned above into separate issue (so that we won't end up too big PR).
#2247 & #2248 
Please have a look and let me know your idea~

**Comment by AlexGilleran** [comment]
Closing in favour of @t83714 's tickets
