### ISSUE TITLE
Secure datasets in Registry API with OPA

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2247]
### Problem description

We have integrated the elasticsearch dataset store with OPA (open policy agent).

However, people still be able to fetch dataset record through registry API from the database.

We want to integrate the registry API with OPA to make sure registry API return datasets data according to access control policy.

There is a list of API we want to secure:
- Get a record aspect by ID
  - `/api/v0/registry/records/{recordId}/aspects/{aspectId}`
- Get a list of all events affecting this record
  - `/api/v0/registry/records/{recordId}/history`
- Get the version of a record that existed after a given event was applied
  - `/api/v0/registry/records/{recordId}/history/{eventId}`
  - Will make decision only on  `recordId`
- Get a list of all records as summaries
  - `/api/v0/registry/records/summary`
  - **Requires partially evaluation**
- Get a list of all records
  - `/api/v0/registry/records`
  - **Requires partially evaluation**
- Get a record by ID
  - `/api/v0/registry/records/{id}`
- Get a summary record by ID
  - `/api/v0/registry/records/summary/{id}`
- Get the count of records matching the parameters
  - `/api/v0/registry/records/count`
  - **We probably want to secure it at api level**

### Acceptance Criteria
- Requesting a record that a user has access to should return the record as long as they're logged in
- Requesting a record that the user _doesn't_ have access to should return `404` (NOT `403` because we don't want to reveal the existence of records to someone trying strings)
- Requesting multiple records should only reveal records that the user has access to (as per the search API)
- Requesting events directly should only show events for records that the user has access too
- Existing openly visible records should continue to be openly visible (including to non-logged-in users) - i.e. we should be able to deploy this on data.gov.au and change nothing for the user
- There should be some way to lock every record down so that only logged in users with a certain role can access it (this can be as manual as necessary though)
- Aspect definitions can be open to the world (for now)
- Access control should be applicable to all records, not just datasets (so we can restrict distributions, organisations etc)

**Comment by t83714** [comment]
@AlexGilleran re-think about my slack comment yesterday. 
I think probably shouldn't cover all registry record with a single resource `object.registry.record`.
That design was meant to save some effort.
However, the defined resources `object.dataset.draft` & `object.dataset.published` has covered `dataset` already.
The `object.registry.record` will create some logic overlaps on the same access control layer (securing data objects), which may create some problem for us later.
We probably have to drill down to `Record Type` level (which may be a bit harder --- considering there seems no easy way to tell record type from record table ):
- Define: `object.event` to secure registry events
  - It doesn't support any ownership or pre-authorised permission
  - i.e. only one type permissions are possible for `object.event`: No constraint 
- Dataset Record will be secured by existing policy (under resource definition `object.dataset.draft` & `object.dataset.published`)
- Dataset Distribution will be secured under `object.distribution` and its access control logic is defined by the dataset. i.e. People has the same access to the distribution as the associated dataset record 
  - OR we can figure a new story to secure distribution --- this story must work with datasets logic nicely i.e. no overlap no conflicts
- Organization Record can be secured under 
  - `object.organisation.internal`: if there is a corresponding `org-units` record
    - This will cover records in `org-units` table as well
  - `object.organisation.external`: if it's an external organization (created by connector)
  - We will need to add an extra field (or a new aspect?) to `organization-details` to tell whether it's external or internal
  
I don't have a concrete idea for this yet.  Probably we can have a quick chat on this.

**Comment by AlexGilleran** [comment]
Replaced with #2358
