### ISSUE TITLE
Consolidate OPA Admin Role & existing `admin` account type

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2248]
### Problem description

We previously have a simple `admin` account type in order to secure APIs & functions.

Considering, now, we have OPA based `admin` role which can offer more features, we should migrate code replies on existing `admin` account type to query OPA based on admin role.

We probably need the followings:
- Modify existing policies to create an exemption for admins (i.e. admins should be allowed for most cases)
- A new policy to secure all APIs. 
  - We can hardcoded all API uris in policy
  - and if we want to change the config (i.e. change an API from disallowing to allowing for a role, we just need to update the policy)
- A common middleware to query OPA and decide whether an API is allowed or not
- Code changes for APIs
- We also have frontend codebase relies on `Admin` account type. We need to migrate those code as well

### Working list of what needs securing
- All non-GETs to `content-api`
- All operations on the `admin-api`

### Acceptance Criteria
- The `isAdmin` column is deleted and everything still works!
- Users with `isAdmin` set to true are migrated such that they have the default admin role
- The existing "Make Admin" button in the admin UI grants/ungrants this role to users instead of flipping the `isAdmin` flag

**Comment by AlexGilleran** [comment]
> We can hardcoded all API uris in policy
> A common middleware to query OPA and decide whether an API is allowed or not

@t83714 : This sounds a bit brittle - would it be possible to do it on a more resource-centric basis like we're gonna do with the registry? E.g. rather than have a policy for `POST /content/x`, have a policy for editing any content api item.

**Comment by t83714** [comment]
@AlexGilleran 
I think we always can secure APIs at two layers (either layer):
- First layer: APIs themselves are resources to be secured. Access control policy defines whether a user has access to the API
  - Not all APIs are data objects related (e.g. make indexer re-crawl or send out an email) and this layer defines the bottom line.
- Second layer: Records / Data Objects are resources secured by access control. This layer normally is implemented at the data access level to make sure the user can only access data objects in a way that they are allowed to. 
  - i.e. Even a user has access to an API, access control may deny the access due to insufficient permission

The second layer provides more fine-grained access control but we probably always need a `story` for a different data object (depends on the usage of the data object) --- I haven't got a very concrete idea of the story (that covers all data objects) yet~

The first layer only requires a very simple access control story to provide the equivalent access control feature as our current admin account type mode (e.g. Whether you can access or not only depends on your account type/role). And this also allows us to gradually (one API at a time) roll-out access control for the second layer. 

For API like `POST /content/x`, we probably want to do it at the second layer as we've almost done it halfway.

Just food thought. We probably can have a quick chat on it and share some ideas~

**Comment by t83714** [comment]
We introduced a single policy entry point (together with the new decision endpoint) where we can add the exemption for the admin users easily.
It's implemented in this PR:
https://github.com/magda-io/magda/pull/3310
closed
