### ISSUE TITLE
Add Dataset Page 3: Produced in Collaboration

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2333]
As a user, I want to be able to record other organisations that collaborated on the production of a dataset.

![image](https://user-images.githubusercontent.com/900555/61013133-c9702c00-a3c4-11e9-833b-48e9fcbd7235.png)

This has already been partially done - this ticket is about aligning it with the design, and making it a drop-down for existing organisations rather than a free text field.

### Acceptance Criteria
- The organisation dropdown should work similarly to #2328: Uses the organisation search index, causes new organisations to be added to the registry, if a user puts in an existing situation it should use that one
- Multiple organisations should be selectable
- The multi-select user experience should match multi-select experiences on the previous pages - e.g. dataset keyword select

**Comment by t83714** [comment]
closed via https://github.com/magda-io/magda/pull/2435
