### ISSUE TITLE
Implement OPA-based Authorisation for Reads in the Registry

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2358]
### Problem description
Building on https://github.com/magda-io/magda/issues/2247 and https://github.com/magda-io/magda/pull/2325.

This is an epic for adding opa auth to reading things in the registry.

Not in scope for this:
- API for setting auth policies
- Events for auth policies
- Auth for update/delete of records/aspects

**Comment by t83714** [comment]
all registry APIs are secure in this PR with the new auth model:
https://github.com/magda-io/magda/pull/3310
closed
