### ISSUE TITLE
Add authorisation for records on record history API

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2376]
### Problem description
Apply record-level authorisation to the https://dev.magda.io/api/v0/apidocs/#api-Registry_Record_History-GetV0RegistryRecordsRecordidHistory endpoint. This involves only allowing access to the history of a record if the user has access to the record in general.

### Acceptance Criteria
- If the user does not have access to a record via the `records/{recordId}` endpoint, they should get a `404` from this endpoint also, as if the record didn't exist.
- If the user does have access to the record, they should be able to view all the events as normal - don't worry about securing specific events yet.
- If a record no longer exists (because it has been deleted), then respond with 404 unless the user is an admin (for now, we can figure out a more comprehensive solution later - it's fractally complicated otherwise). If the user is an admin then they can see the deleted record's history regardless of permissions.

### Technical Notes
- It should be possible to use a similar strategy as for #2369 for this

### Out of Scope
- Finer-grained authorisation of the events themselves - for now as long as you have access to a record you can see the events

**Comment by mwu2018** [comment]
@AlexGilleran 
If I understand it correctly, the out-of-scope of "Finer-grained authorisation of the events themselves" means that if
1. RecordA references  recordB
2. A user has access to recordA but not recordB
the user will get all events related to recordA. Those events will have link aspect containing reference to recordB (i.e., recordB will not be filtered out). If filtering is required, the implementation will be complicated.
