### ISSUE TITLE
Add Dataset Page 4: Question: Where user can access this dataset from?

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2399]
Require to implement a way to offer suggestions to users

> So the program will look at all previously saved datasets (probably only draft dataset?) that you have access to. Then aggregate the text content of this file location box for all dataset into a candidate list.
Then, filter the list with the user's input.
We will not restrict the text content format in this box.
So user can either put MySQL database A or /myComputer/sharedDrive/folderA
I probably will create a special elastic-search analyzer so text context will be broken into small tokens by  special chars.
i.e. when user input sharedDrive, option /myComputer/sharedDrive/folderA will be matched

Technically, we gonna re-use the current dataset search API rather than manually compile a suggestion list and filter item out.

We probably need to:
- make sure the location field is saved to Elasticsearch
- An analyzer is created so that tokens are generated by breaking any special chars (will try simple Tokenizer or Standard tokenizer)

Estimate: 8

![image](https://user-images.githubusercontent.com/674387/62674948-093c2a80-b9e8-11e9-87b4-8ca27514a9b3.png)

## Acceptance Criteria
- You should be able to override suggestions with a value that hasn't already been seen
- You should only be able to see suggestions from dataset that you have access to (draft and published)
- There should be two fields here - access _location_ and access _notes_. These should be separate, with separate copy that will be updated by @alyce.

**Comment by alyce** [comment]
Could we separate these as two fields; dataset location and dataset access notes, with the following copy?
![IMG_3468](https://user-images.githubusercontent.com/40975814/63076026-0a84ce80-bf77-11e9-8f08-202eca16bdbd.jpg)
