### ISSUE TITLE
Add Dataset Page 4: Style: What type of license should be applied?

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2401]
Add info icon & Adjust style to match the design.
So change this:
![image](https://user-images.githubusercontent.com/674387/62674700-eeb58180-b9e6-11e9-879d-bea3e9eabb1c.png)
to: 
![image](https://user-images.githubusercontent.com/674387/62674713-fb39da00-b9e6-11e9-9ce6-bda6033bf3c0.png)

probably use `react-select`
 
Estimate: 3

**Comment by AlexGilleran** [comment]
Low priority - leave this until the end when we review all the styling together.
