### ISSUE TITLE
Add reference to superceding dataset when setting dataset to superceded

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2447]
## Description
Following on from #2428, it'll be possible to set a dataset to "Superceded", but there really should be a way to set a reference to the new dataset that actually superceded it.

This should be achieved by having a new form control appear when "Superceded" is selected as a status, of the same type as the one that will be used for "derived from" in https://github.com/magda-io/magda/issues/2334. It allows for existing dataset(s) to be searched for / selected, or created as draft(s) for later filling out.

## Acceptance Criteria
- When "Superceded" is selected as a status, a dropdown appears below it.
- This dropdown allows:
    - The selection of existing datasets
    - The creation of new datasets as drafts
- For > 1 dataset to be selected

## Technical Notes
- This will require modification of the relevant aspect (currency? life-cycle?)

**Comment by t83714** [comment]
closed via PR https://github.com/magda-io/magda/pull/2476
