### ISSUE TITLE
Large data preview - script timeout

### ISSUE THREAD

**Issue by gordjw** [magda-io/magda#2448]
**Describe the bug**
Previews of large data causes the page to freeze, making all other interactions impossible.

**To Reproduce**

1. Go to 'https://data.gov.au/dataset/ds-dga-487c604c-c93e-409e-90b9-6d1461c780ac/details?q=APS%20survey%202018'
2. Click on any download links (or wait until the Preview script kicks in, then click download)
3. Expect: nothing will be clickable, may have to 'Exit page'

**Expected behavior**
To be able to interact with components that are normally working, not having one script lock up the page.

**Screenshots**

**Desktop (please complete the following information):**

-   OS: MacOS
-   Browser: Chrome
-   Version: 75

**Additional context**
Maybe disabling preview for large datasets that won't load in a "reasonable" amount of time could help, could be a size based limit for simplicity.
Could also investigate ways to run Preview script in a separate thread.

Related to #1934

**Comment by AlexGilleran** [comment]
Yeah this is actually a massive deal, it'd be really good to at least mitigate it.

> Maybe disabling preview for large datasets that won't load in a "reasonable" amount of time could help, could be a size based limit for simplicity.

This seems like a good idea, maybe we could do a HEAD request and pull it off the Content-Length header or something 🤔

**Comment by t83714** [comment]
It seems it locks up at Papa Parse parsing staging. Probably, a simple fix could be turning on `Papa Parse`'s [worker mode](https://www.papaparse.com/#worker) so it will be done in a separate thread?

**Comment by AlexGilleran** [comment]
Investigating solutions in #2455

**Comment by AlexGilleran** [comment]
No longer locks up in dev (https://dev.magda.io/dataset/ds-dga-487c604c-c93e-409e-90b9-6d1461c780ac/distribution/dist-dga-b89fa786-77e7-4aee-abd8-70fc233dfd42/details?q=APS%20survey%202018), closing this.
