### ISSUE TITLE
Improvement Visualization Frontend Performance

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2455]
## Description
There are a few quick frontend visualization improvements we probably want to implement:
1> Turn on `papa parser` [worker](https://www.papaparse.com/faq#workers) option to enable data downloading & parsing to be done in a separate thread. Thus, it won't slow down the web user interface.

This only requires set worker option to `true` (and upgrade papa parse to 5.0)

2> As table & chart preview was developed separately, they actually load/parse data independently. 
i.e. if switch from chart view to table view, the data file will be loaded again.
We should lift the data loading & Parse code to higher level so that the data will be shared between two preview component.

3>  We should use `chunk` option of papa parse to stream the remote file and only partially download the file until `certain limit`. This doesn't rely on HTTP `head` request.

Those improvements above might help #2448 

## To Investigate
- Are any/all of these quick wins?
- If so we should do them, otherwise write a ticket describing the proper way to fix it and figure out a dodgier solution (e.g. not showing for big files)

**Comment by t83714** [comment]
All 3 solutions can work together and we should implement all three if possible.
Here is the work estimate:
- item one: 
  - tiny / size 1 --- only one line of code 
- item two: 
  - medium or large: not hard but requires some code refactoring
- item three:
  - medium: probably need to get item 2 done first. Therefore, we only have one place to load the data.
  - It's based on papa parse's built-in feature. The remote file will be streamed and processed by chunks and we can decide to stop it in the halfway.
  - We probably can even make it configurable. e.g.:
    - Max. data for chart: 500mb 
    - Max. data for table preview: 50mb etc.

**Comment by maxious** [comment]
Here's some statistics about CSV files on data.gov.au CKAN:
```
> SELECT unnest(percentile_disc(array[0.25,0.5,0.6,0.7,0.75,0.8,0.9,1]) WITHIN GROUP (ORDER BY size)) as csv_size_in_bytes
   FROM (select size from resource where size is not null and (format ilike '%csv' or mimetype ilike '%csv')) a;
 csv_size_in_bytes 
-------------------
               626
              1854
             15507
             99273
            130308
            506803
          12345095
        1594208963
(8 rows)
```
ie. 80% of resources declared as CSV files which could be ZIP files with many CSVs inside are less than 0.5MB and 90% less than 12MB. So even a 2MB limit would cover quite a lot of resources and loading only that much would still be useful to peek inside a resource assuming it could be parsed.
