### ISSUE TITLE
(?) tooltip icon next to Add Dataset first issued field does nothing

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2465]
**Describe the bug**
Next to "When was the dataset first issued?", there's a tooltip icon, but when hovered over nothing comes up. Presumably there should be some information about what a first issued date does, otherwise we should remove it.

**To Reproduce**
Go to /dataset/add and click through to the first page.

**Expected behavior**
A tooltip comes up that displays "Use the date the dataset was first created or issued for release".

**Screenshots**
<img width="323" alt="image" src="https://user-images.githubusercontent.com/900555/64577090-baa2f700-d3be-11e9-9424-48212ec1455c.png">

**Technical Notes**
See other examples of tooltips in the frontend.

**Comment by AlexGilleran** [comment]
Can't see anything in the designs @alyce when you've got Magda time, what do you think this should do/say? No rush :).

**Comment by alyce** [comment]
@AlexGilleran perhaps we should just add some simple explanatory text, e.g. "Use the date the dataset was first created or issued for release"

We added a tooltip here to clarify the weird term "issued" for less data-literate users
