### ISSUE TITLE
ArcGIS REST National Map preview doesn't work 

### ISSUE THREAD

**Issue by maxious** [magda-io/magda#2475]
**Describe the bug**
ArcGIS REST National Map preview doesn't work in Magda eg. for a vector dataset with a GeoJSON resource collected from ArcGIS Open Data. These URLs do work in National Map directly if you copy an paste.

**To Reproduce**

1. Go to https://data.gov.au/dataset/ds-melbourne-water-80e3acf78d2bf23cdf7c6303036323caf8924882f1b44c03eba85acf301a199b/details?q= or https://data.gov.au/dataset/ds-logan-http%3A%2F%2Fdata-logancity.opendata.arcgis.com%2Fdatasets%2F7f24a54ca34b4a45b9f2d7f98d20ec1b_0/details?q=
2. View console errors

**Expected behavior**
A map appears on National Map UI

***Actual Behaviour ***
![image](https://user-images.githubusercontent.com/81432/64668441-ef877a80-d4a0-11e9-8f21-c5fd5a58e73a.png)

Loading indicator never disappears and Console error "Preview Map notifcation: 
 The MAGDA dataset does not have a distribution with the ID dist-melbourne-water-6bfc3760102e3e193fbf19487d907e8834f033ba8e2bf574af904a94e9d50421 or it does not have a supported format." 
 Can see an error box with the same message if you click "Open in National Map"

Windows 10, Chrome 76

**Additional context**
https://data.gov.au/api/v0/registry/records/ds-melbourne-water-80e3acf78d2bf23cdf7c6303036323caf8924882f1b44c03eba85acf301a199b?dereference=true&aspect=dcat-dataset-strings&optionalAspect=dcat-distribution-strings&optionalAspect=dataset-distributions&optionalAspect=temporal-coverage&optionalAspect=dataset-publisher&optionalAspect=source&optionalAspect=source-link-status&optionalAspect=dataset-quality-rating

Works via copying the ArcGIS REST API url and adding manually in National Map with the autodetect option https://nationalmap.gov.au/#share=s-unUUic7mhnLjmaglGFmVXIsqelR https://nationalmap.gov.au/#share=s-5D18442aiDM5KrPwPr78NLwHNmu

There may also be a different problem with raster dataset previews https://data.gov.au/dataset/ds-logan-http%3A%2F%2Fdata-logancity.opendata.arcgis.com%2Fdatasets%2Fd0899cc42a314e2a8a4db559405f1b48_0/details?q=logan%20city

**Comment by t83714** [comment]
Those Esri server URLs are `feature server` url which can't be supported perfectly by TerriaJs and has been disabled at this moment.
See: https://github.com/TerriaJS/terriajs/issues/3661
Having said that, our frontend should skip picking Esri link (if it's a feature server) for map preview and select other data source (e.g. geoJSON) for preview.
Will alter the current logic of determining data source for preview to overcome this.
i.e. Esri server only will be picked if it's not a feature server
Please let me know if you got a better idea

**Comment by t83714** [comment]
It seems Terria team will look into the feature server performance issue in the following sprint. 
I think it's probably better to wait https://github.com/TerriaJS/terriajs/issues/3661 is done rather than disable the Esri feature server from the Magda frontend (the solution described in my previous note).
My tests show that some of GeoJson data file distributions (GeoJson would normally be picked once we disabled Esri) could be very large and cause issues at client-side.

**Comment by kring** [comment]
@t83714 sorry but I don't think we're necessarily planning to look at this in the next sprint.

**Comment by t83714** [comment]
@kring No problem~ 👍 Created a PR to disable the Esri feature server for map preview for now~
