### ISSUE TITLE
"Deploy a New Instance" button

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2487]
**Is your feature request related to a problem? Please describe.**
We have a lot of problems with people asking where they can "Download" Magda (or even claiming that they have?), and getting really confused when we start talking about Docker and Kubernetes and Helm etc. Going cloud-native has some really cool benefits, but it's a problem for:

A) Non-technical people, who assume that if it can't be downloaded it's vapourware and
B) Technical people who aren't quite up to date with docker and how it works, and assume that they should just be able to download and run something and get very confused when the artifacts are text files.

... and these are just the people we talk to, there's probably a whole cohort of people who find the page, try to get it running, fail and never send us an email about it.

**Describe the solution you'd like**
To help all of these people, I think it'd be cool if we could have some kind of automatic way to get a basic instance of Magda up and running - something like the "Run on Heroku" buttons that are on some (much simpler!) open source projects.

The ideal form of this is that the user opens the Magda readme or magda.io, sees a "Create Your Own Instance" button, and once clicked this sets them up a brand new instance of Magda with a database, ES cluster, HTTPS etc all working.

Obviously it can't quite be this simple. They'll need somewhere to run it, which means they need some kind of cloud provider account, which is probably Google Cloud. So probably it'll end up working like:
- User presses the button
- User sees a brief bit of documentation telling them to set up a Google Cloud account ($300 of free credit!). So they set up their account or they already have one
- User logs into Google Cloud
- We create a new Google Cloud project with everything that Magda needs (database, es, https etc) all working
- User gets a link to their new homepage and some instructions on what to do next.

**Describe alternatives you've considered**
An alternative would be having some kind of free, massively multi-tenant Magda that people can sign up with and use, but I think that'd A) take much more work and B) be of dubious utility.

**Additional context**
- There's a whole way to automate GCE project setup at https://cloud.google.com/blog/products/gcp/automating-project-creation-with-google-cloud-deployment-manager
- If we find any corners we can cut here we should - the whole idea that anyone even wants this button is somewhat of an untested hypothesis.

**Comment by t83714** [comment]
See the proposed solution here:
https://github.com/magda-io/magda/issues/2488#issuecomment-533373895
https://github.com/magda-io/magda/issues/2488#issuecomment-533389652

**Comment by t83714** [comment]
I think this ticket is parked as a web deployment interface is not required at this moment

**Comment by AlexGilleran** [comment]
Closing this because the new terraform system is good enough.
