### ISSUE TITLE
One-Click Magda: k8s Deployment Job Docker Image

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2497]
#### A docker image which can complete the deployment (as a k8s job) 
- It will accept the following parameters (pass through as env vars):
  - the default service account access key (this service account has cluster-admin permission)
  - project name
  - zone or region name
- It will output log in the specific format to indicate the success or failure outcome (probably use [helm notes](https://github.com/helm/helm/blob/master/docs/chart_template_guide/notes_files.md)) 

Full story see:

https://github.com/magda-io/magda/issues/2488#issuecomment-533373895
https://github.com/magda-io/magda/issues/2488#issuecomment-533389652

### Technical Notes
- We need a docker image for this because Terraform is a command-line only tool, so we need to have something that can call it in an easy, reproducible way, and a Kubernetes Job is a pretty easy way to package it up

### Acceptance Criteria
- Service account key, project name and zone/region name are configurable via passed parameters.
- The job should be able to work starting with nothing more already created than:
    - A Google Cloud service account with the following permissions: (@t83714 to add list)
    - A google cloud project with and the service account above and the following APIs enabled (@t83714 to add list)
- When the job finishes, there should be:
    - A running magda instance (the job will finish when helm install finishes)
    - An ingress created (the ingress might not be running yet, but it will have been created)
    - A working SSL certificate (that will be passed to the ingress)
- If it goes wrong:
    - The job should print the details of the error to the console as JSON
    - The job should roll back everything it created
    - The process should return an error code

### Out of scope
- Waiting for the installation to be completely ready (this will be done by the frontend tool)

**Comment by t83714** [comment]
I think this ticket is parked as a web deployment interface is not required at this moment

**Comment by AlexGilleran** [comment]
Closing this because the new terraform system is good enough.
