### ISSUE TITLE
One-Click Magda: The Auto Deployment System Node-js Backend

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2498]
#### A node-js backend for the Auto Deployment System:
- is capable of the followings:
  - Serve static frontend code ([item 3](https://github.com/magda-io/magda/issues/2499))
  - Help google oauth2 processing
  - Launch k8s deployment job (as [item 1](https://github.com/magda-io/magda/issues/2497)) and proxy the job execution output

Full story see:

https://github.com/magda-io/magda/issues/2488#issuecomment-533373895
https://github.com/magda-io/magda/issues/2488#issuecomment-533389652

### Out of Scope
- Most logic in the process - this should live in the frontend

### Acceptance Criteria
- Should be packaged as a helm chart so it can be deployed to Kubernetes
- Should be completely separate to the main magda charts / k8s config
- Should enable the ability to log in via an existing Google account via the frontend
- Should be able to serve the built frontend code
- Should have an API that launches the job in #2497 

### Technical Notes
- Can be pulled together from code in the Magda Web Server and Gateway

**Comment by AlexGilleran** [comment]
Closing this because the new terraform system is good enough.
