### ISSUE TITLE
One-Click Magda: The Auto Deployment System React Frontend

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2499]
#### The Auto Deployment System React Frontend

- is capable of the followings:
  - Handle oauth to google acc
  -  talks to google APIs and complete the followings:
     - create a project (link billing acc)
     - create a service account access key
  - Create deployment k8s job (via nodejs backend) and coordinate the whole deployment process
 - In order to make this program portable and can be embedded to different websites for different purposes. The following are NOT included:
   - Documentation about `how it works` or FAQ such as:
     - What's the $300 free credit
     - what happened after the user sign up the trial google cloud account
     - How to use Magda once it's ready
   - The ACTUAL button UI
     - When embedding the trial system, we need to:
       - Add a button in any style
       - Once it's clicked, a popup will be opened and redirect the user to a pre-defined trial system URL (this frontend)

Full story see:

https://github.com/magda-io/magda/issues/2488#issuecomment-533373895
https://github.com/magda-io/magda/issues/2488#issuecomment-533389652

### Acceptance Criteria
-

**Comment by AlexGilleran** [comment]
Closing this because the new terraform system is good enough.
