### ISSUE TITLE
One-Click Magda: Investigate the Benefit of involving Terraform in solution 

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2507]
#### Investigate the Benefit of involving Terraform in solution to see:
- If Terraform can simplify the solution implementation 
- Compared with our current Helm deployment, what's the benefit of using Terraform.
  - Besides the functionality requirements of One-Click Magda, any potential improvement/benefits can be brought to our normal deployment process

**Comment by t83714** [comment]
Summary of terraform:
Benefits:
- Compared with Helm, potentially can handle changes reconciliation better. Because:
  - Terraform use `id` to reference resource (where id is not available use ID equivalent) rather than `tags` that helm uses
    - This gives you an accurate (1 to 1) `resource` <-> `config` mapping and keeps tracking changes 
    - This also introduces a better `dependency` resolution solution. i.e. you don't need to (not recommended by terraform as well). dependency graph will be auto figure out by resource variable reference. e.g. Resource A depends on Resource B because resource A's config requires resource B's id (which only be available once resource B is deployed)
- Allow you to manually import resource to adjust the current state.
  - That would be useful when moving an existing instance to terrform 
  - It comes with the plan tool to scan the current infrastructure as well 
- Support a wide range of cloud service & tools so we can support diifferent cloud provider or infrastructure easily. Full list: https://www.terraform.io/docs/providers/index.html
- Better debugging support as it's a config language rather than a template. You will get details message which line got errors

Drawback:
- Not a template language. So you can't conditionally define a portion of the config as string
- not very strong conditional logic support. You have to use `? :` operator and use `count` or `for_each` to achieve the same logic
- if the cloud provider releases a new feature, we don't have the access to the new feature until the terraform provider upgrades.

Overall, bring terraform to our deployment process can potentially improve our process in many ways. 

I created a branch `issue/2488` with a sample terraform config to deploy trial magda instance.

Detailed instruction follows in a separate note.

**Comment by t83714** [comment]
@AlexGilleran 
If you want to have a try, here is the instruction:
- Install terraform  -- can be done via brew
- switch to branch `issue/2488`
- `deploy/terraform/*` are all terraform modules
  - `deploy/terraform/magda-one-click` is the main module to deploy our trial instance
- Sign-up a new google account & cloud trial (https://cloud.google.com/free/)--- so you can avoid the cost
- The following steps will be handled by APIs but we need to do them manually now:
  - create a project (note down the project id)
  - go to IAM / service account: create a key and download the json key file for the default service account
  - go to IAM: add k82 engine admin (not cluster admin) role to the default service account
- `cd deploy/terraform/magda-one-click`
- `terraform init`
- Edit `deploy/terraform/magda-one-click/terraform.tfvars` and put in correct parameters
  - If this file doesn't exist, you will be prompt to input manually
  - you can also override this value file manually via cmd switch
- `terraform apply` and follow the instruction

#### Todo:
- https on ingress still not working, please access web ui via http & ip
  - Trial account has global 1 static IP allocation limit. Somehow, the load-balancer will try to allocate another IP --- We should be able to find a workaround 
- should find alternative solutions for all `provisioners`
#### To destroy
- `terraform destroy`

#### Others
You can `terraform apply` anytime when you have changes to apply.
It will figure out the changes (by scanning the infrastructure ) and show a plan first.
You can also run `terraform plan` to just show a plan

**Comment by AlexGilleran** [comment]
Chugging along now, very crisp!

Stuff that went wrong so far:

```
Error: Error retrieving available container cluster versions: googleapi: Error 403: Kubernetes Engine API has not been used in project 621294044548 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=621294044548 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
```

Resolved by doing what it says in the message.

```
Error: googleapi: Error 400: The user does not have access to service account "default". Ask a project owner to grant you the iam.serviceAccountUser role on the service account., badRequest

  on ../google-cluster/main.tf line 12, in resource "google_container_cluster" "primary_magda_cluster":
  12: resource "google_container_cluster" "primary_magda_cluster" {



Error: Error creating GlobalAddress: googleapi: Error 403: Required 'compute.globalAddresses.create' permission for 'projects/magda-terraform-test/global/addresses/magda-default-external-ip', forbidden

  on ../google-reserved-ip/main.tf line 9, in resource "google_compute_global_address" "external_ip":
   9: resource "google_compute_global_address" "external_ip" {
```

Resolved by granting the service account "Compute Network Admin" and "Service Account User'.

**Comment by t83714** [comment]
@AlexGilleran 
If you want, please have another try.
This pretty much fixed most issues including auto certificates issuing & domain zone record creation, although the initial deploy speed can still be improved (e.g. a couple of mins can be saved from cluster creation. I will leave it to later).
To try it:
```
cd deploy/terraform/magda-one-click
# You need to run again as I introduce more modules
terraform init
terraform apply
```
By default, the certificate will be issued by lets' encrypt staging endpoint --- i.e. the certificate will be issued by `fake CA`.
For production, we need to set the parameter `acme_server_url` to production endpoint: `https://acme-v02.api.letsencrypt.org/directory`
Please avoid trying the production endpoint due to the 50 limit.

I've created a `magda-trial-dns-bot` AWS user with sufficient permission.
You can reuse that account by creating a new access key
OR create a new user and re-use the policy I created~

**Comment by AlexGilleran** [comment]
I'd say this is closed now 👍
