### ISSUE TITLE
`yarn install` fails for node v11

### ISSUE THREAD

**Issue by sajidanower23** [magda-io/magda#2518]
**Describe the bug**
`yarn install` fails for node v11

**To Reproduce**

These were my `node` and `npm` versions:
```
$ node -v
v11.15.0

$ npm -v
6.10.1
```
`cd` to the root of the repository and run `yarn install`.

**Expected behavior**

The installer waits a while to install `@gov.au/accordion` but fails with the error message (the first part of it has been truncated): 

```
[4/4] Building fresh packages...
[-/30] ⠄ waiting...
[29/30] ⠄ @gov.au/accordion
[-/30] ⠄ waiting...
[-/30] ⠄ waiting...
error ~/magda/node_modules/@gov.au/accordion: Command failed.
Exit code: 1
Command: pancake
Arguments: 
Directory: /home/ano002/magda/node_modules/@gov.au/accordion
Output:
                         /////////////
                        +-----------+/
            (っ˘̩╭╮˘̩)っ  |  Hogwash  |/
                        +-----------+

🔥  ERROR:   Couldn't read local settings :(
```

**Screenshots**

N/A

**Desktop (please complete the following information):**

-   OS: Ubuntu 18.04

**Smartphone (please complete the following information):**

N/A

**Additional context**

This was a done as a part of setting up for a new developer, and as such, it was a fresh install.

**Comment by ds-merck** [comment]
I had the same issue. Resolution was to switch to node 10.0.0, which is the last supported version by https://github.com/govau/pancake I did so by using https://github.com/tj/n

**Comment by t83714** [comment]
closed as we've switch node 14 previously and has this PR switched to node 18:
https://github.com/magda-io/magda/pull/3501
