### ISSUE TITLE
Magda Deployment: Easily add SSL to an existing Magda deployment

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2526]
## Description
Having set up a new non-HTTPS Magda deployment in #2529, a user will probably want to add HTTPS. However, this is actually harder than everything else about setting up Magda put together. So what we'll do is create an easy way for the user to add HTTPS on one happy path (Google Managed Certificate) on their own domain. If we need to support other ways later we can add it.

### Acceptance Criteria
- There are instructions for adding SSL to your existing Magda instance (created with #2529). These don't need to be _that_ easy but let's do what we can to make them as easy as possible.
- There are extra config options in the Terraform config that allow a Magda setup created with #2529 to have HTTPS added to it with `terraform apply`
- @sajidanower23 can use it successfully based on the instructions alone

### Out of Scope
- Applying for a domain - it can be assumed that the user has access to a domain and the ability to add records to it
- Supporting too much flexibility - this is all about having one easy way. Maybe we can make it flexible later.

### Technical Info
- With Google Managed Certificates it should be possible to make this work without having to have direct access to the user's domain registrar (as we would with Let's Encrypt).

#### Background Info (from original issue)
As it's hard to implement a perfect auto TLS / HTTPS setup without security concerns (our current solution reuses the same wildcard certificate across multiple clients due to 50 certificate week generation limit of service provider `let's encrypt`), we decided to make the auto process to set up a site with HTTP access only.

At the end of the auto Magda instance creation process, we're gonna display the steps/commands that user needs to set up their own SSL certificate files (purchased from their provider) and enable HTTPS.

The installation steps will be something like:

1> Follow the instructions of the link below to install Google Cloud SDK

https://cloud.google.com/sdk/docs/downloads-interactive

2> Follow the instructions of the link below to install `kubect`l:

https://kubernetes.io/docs/tasks/tools/install-kubectl/

3> Run gcloud command to log in to your google account. You will see a web browser window for inputting your username & password

```
gcloud auth login
```

4> Run gcloud to setup your access to your cluster:

```
gcloud container clusters get-credentials [cluster name] --zone [zone name] --project [project name]
```
_* note: [cluster name], [zone name] & [project name] will be replaced with real value when display to the user_

5> Create your TLS / Certificate secret in your cluster:

```
kubectl create secret tls magda-cert -n magda --key ${KEY_FILE} --cert ${CERT_FILE}
```
> Please replace the `${KEY_FILE} ` with the path to your local certificate private key file.
And replace the `${CERT_FILE}`with the path to your local certificate file.
If your certificate issuer providers you an intermediate certificate, please add its content to the end of your certificate file and supply your certificate file path as the parameter `${CERT_FILE}`.

6> Update your ingress to enable the HTTPS access:

```
kubectl apply -n magda -f https://gist.githubusercontent.com/t83714/53585b741a2448c8f6139e01d270cb46/raw/16da285eb2709b30dfd2a0a77985cfabc93bd680/ingress-with-https.yaml
```
_* Note: here is the content of `ingress-with-https.yaml` file (as we provide a file url above, we don't need to show the content of the yaml file to user):_
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: magda-default-external-ip
  name: magda-primary-ingress
spec:
  backend:
    serviceName: gateway
    servicePort: 80
  tls:
  - secretName: magda-cert-tls
```

**Comment by t83714** [comment]
Alternatively, we can create a separate repo with some terraform config for the user to set up SSL.
This could avoid the trouble of installing `gcloud` & `kubectl` (terraform actually doesn't reply on those utilities unless our config specifically requires those).
But I think the user may eventually want to install `gcloud` & `kubectl` to manage their magda instance.

@AlexGilleran  
Please leave your comments or update the note above accordingly

**Comment by t83714** [comment]
Created PR here:
https://github.com/magda-io/magda-config/pull/5

**Comment by AlexGilleran** [comment]
Donez0rs
