### ISSUE TITLE
SoE dataset CSVs can't be displayed as charts anymore

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2539]
**Describe the bug**
Since the new chart changes (which are great in general!), there's at least one chart that worked before that doesn't now:

On dev.magda.io:
![image](https://user-images.githubusercontent.com/900555/66802561-98c20480-ef68-11e9-9e0e-aceb07ee4f3e.png)

On data.gov.au:
![image](https://user-images.githubusercontent.com/900555/66802569-a4adc680-ef68-11e9-92f9-8730f5c3d34c.png)

The error in the console says:

```console
retry new newline... backend.js:6:2315
    r backend.js:6
    chunk CsvDataLoader.ts:171
    _ papaparse.min.js:744
```

**To Reproduce**
Go to https://dev.magda.io/dataset/ds-dga-5076fbb3-4cbb-47f4-9121-8e8207744f4b/details?q= and scroll down to where the chart should be.

Compare to https://data.gov.au/dataset/ds-dga-5076fbb3-4cbb-47f4-9121-8e8207744f4b/details?q=

**Expected behavior**
Even though it's not a great chart, we should still be able to display one as per the old code on data.gov.au.

**Comment by t83714** [comment]
Probably here:
https://github.com/magda-io/magda/blob/b976f69133367ec16a6da5927ddd14d51d8e33f0/magda-web-client/src/helpers/CsvDataLoader.ts#L173
I didn't link the promise correctly 😢
