### ISSUE TITLE
Link for installing Helm is not correct

### ISSUE THREAD

**Issue by laisee** [magda-io/magda#2555]
**Describe the bug**
Clicking on link forHelm chart install generates a 404 error

**To Reproduce**
1. Open web page https://magda.io/docs/building-and-running
2. Click on the link under "Set up Helm"
3. 404 Error page for Github appears

**Expected behavior**
The link should probably open up [this page](https://helm.sh/docs/using_helm/#installing-helm), or similar content

**Screenshots**

**Desktop (please complete the following information):**

-   OS: OSX
-   Browser : Brave
-   Version NA

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by AlexGilleran** [comment]
Thanks for the report @laisee :)
