### ISSUE TITLE
Allow a blacklist of strings to be specified for automatic keyword generation

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2560]
## Description
Automatic keyword generation is picking up irrelevant strings like "Dr" in files drag-dropped onto Magda. We should implement a blacklist of words that shouldn't be used as keywords. This should be configurable with a reasonable default, so that it can be extended based on domain.

## Technical notes

- The [TagInput.tsx](../tree/master/magda-web-client/src/Components/Common/TagInput.tsx) module might serve as a good starting point to investigate this

## Acceptance Criteria
- When a file is drag-dropped, words present in the blacklist should not be present in the list of derived keywords.
- The blacklist should be able to be overridden in Helm
- There should be a default set of strings that apply to installations unless overridden

**Comment by t83714** [comment]
copied `Technical notes` from duplicated ticket #2590
