### ISSUE TITLE
Make last modified date unable to be set to the future

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2563]
## Description

Currently you can set last modified date to be in the future, which makes no sense. We should restrict this from happening.

## Acceptance Criteria

-   Datepicker for last modified date does not have future dates available
-   It's not possible to use the keyboard to set the date to the future either.

**Comment by t83714** [comment]
It seems we have created a duplicated ticket here: #2586
Close this but copy the `Acceptance Criteria` over as that ticket has more content
