### ISSUE TITLE
Misplaced tooltip doesn't do anything

### ISSUE THREAD

**Issue by sajidanower23** [magda-io/magda#2582]
**Describe the bug**
There is a tooltip in the `/dataset/add` flow that doesn't do anything.
Also, the tooltip is slightly bottom-aligned.

**To Reproduce**

1. Go to '/dataset/add'
1. Scroll down to where it says 'Spatial extent'
1. Notice the tooltip that doesn't do anything.

**Expected behavior**
The tooltip, on mouse-over, should show a helpful message, or just not be there at all.

**Screenshots**
![useless_tooltip](https://user-images.githubusercontent.com/20970821/68448853-0b0cc880-0239-11ea-9763-61e9cc484f6d.png)

**Comment by MelanieHotchkiss** [comment]
@alyce can you please confirm the expected behaviour here is:

"Select the appropriate region that best matches the spatial extent of your dataset.  
💡 This helps data users understand the scope of your dataset"

**Comment by alyce** [comment]
@MelanieHotchkiss do you mean removing the tooltip and replacing it with a lightbulb icon? If so, yes

**Comment by sajidanower23** [comment]
Yep, removing that question mark and replacing it with a lightbulb so that the whole text reads like:

Select the appropriate region that best matches the spatial extent of your dataset.
:bulb:  This helps data users understand the scope of your dataset

**Comment by alyce** [comment]
Sounds good
