### ISSUE TITLE
Date of last modification should have validation

### ISSUE THREAD

**Issue by sajidanower23** [magda-io/magda#2586]
**Describe the bug**
_Date of last modification_ allows you to have a date that's in the future.

**To Reproduce**

1. Go to '/dataset/add'
1. Click through to the page `Details and Content`
1. Scroll down to the heading `Dates and updates` and try adding a date under "When was the dataset most recently modified?" that's into the future

**Screenshots**
![future_recently_modified](https://user-images.githubusercontent.com/20970821/68553770-21549780-0478-11ea-8e3f-3afa3f17ba10.png)

**Acceptance Criteria**
- User should not be able to use a recently modified date that is into the future.
- An error message or an alert should be thrown on change of focus if the date is invalid.
- Error message should use the style similar to the DTA design system components here: https://designsystem.gov.au/components/form/#error-messages
- Datepicker for last modified date does not have future dates available
- It's not possible to use the keyboard to set the date to the future either.

**Comment by t83714** [comment]
Added more `Acceptance Criteria` info from ticket #2563
