### ISSUE TITLE
Updating Department of Agriculture logo - drop "water resources"

### ISSUE THREAD

**Issue by MelanieHotchkiss** [magda-io/magda#2594]
## Description

Agriculture's name has changed - need to replace with new logo.

## Acceptance Criteria

The new logo and name is reflected in the Agriculture Magda instance - "water resources" has been deleted.

## Technical Notes

![AG_Inline_black](https://user-images.githubusercontent.com/38118717/68733498-f8c0cf00-062a-11ea-8120-3c81ddc0c5a9.png)
![AG_Inline_white](https://user-images.githubusercontent.com/38118717/68733499-f9596580-062a-11ea-820e-041922aa07d0.png)

**Comment by t83714** [comment]
We have a separate Repo for Agriculture related config & SQL migration scripts:
https://github.com/magda-io/magda-config-agriculture/tree/master/sql-migrations
We probably want to update the sql migration script as well for the logo
