### ISSUE TITLE
"Time period" second date entered drop down calendar covers first date range entered

### ISSUE THREAD

**Issue by MelanieHotchkiss** [magda-io/magda#2598]
**Describe the bug**
When selecting a second date range, the calendar covers the first.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to /dataset/add
1. Go to details and contents
1. Enter a date range under "what time period does the dataset cover?"
1. Enter a second date range and note the calendar covers the first date range

**Expected behavior**
The calendar should render above the time period question.

**Screenshots**
![image](https://user-images.githubusercontent.com/38118717/68738092-81df0280-0639-11ea-9d1f-d184a0f2d3fc.png)

**Comment by soyarsauce** [comment]
Rendering the dropdown, not downwards, feels a little unnatural (and from a brief look, means we have to do some css hackery, `react-dates` doesn't give any nice options to do it from the library)

We're going to try putting the selected dates / "tags" above the picker (immediately below the question "What time period(s) does the dataset cover?" & see how that feels
