### ISSUE TITLE
Google Login no longer works due to dead Google+ API

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2605]
**Describe the bug**
Trying to sign in via Google now results in this error:

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/900555/69023737-f50abf00-0a13-11ea-8a4f-68cfd82a733f.png">

Going to the URL in the error message doesn't help because that API is now completely dead. Upgrading our Google Passport version should fix it: https://stackoverflow.com/questions/58661322/googleplusapi-return-error-legacy-people-api-has-not-been-used-in-project

### How to Reproduce
Go to dev.magda.io, click Sign In, click the "Google" button.

**Comment by naveedjd** [comment]
I don't get the "Google"button when I click Sign In.

**Comment by sajidanower23** [comment]
@naveedjd  Do you not see the link saying `Google` on the left?
![google_button](https://user-images.githubusercontent.com/20970821/69103866-aa904d80-0aba-11ea-884d-caddbb887726.png)

**Comment by naveedjd** [comment]
No. I don’t see this link on the left. Please refer the attached screenshot of the home page that I get.




Thanks.

Regards,
Naveed.

**Comment by naveedjd** [comment]
<img width="1271" alt="Screenshot 2019-11-19 at 10 10 36 AM" src="https://user-images.githubusercontent.com/45190647/69117673-803c9100-0ab6-11ea-9d6f-86ff5cbcbb1c.png">
