### ISSUE TITLE
dcat-dataset-strings Schema should NOT require keywords to have at least one item

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2626]
**Describe the bug**

Currently, if you run dga ckan connector, you will see the following errors:
```
Failed to PUT data registry record with ID "ds-dga-3b513cc7-b54c-4826-8da8-b18b9f03c34e". 6 retries left. Status code: 400, body:
{
  "message": "#/keywords: expected minimum item count: 1, found: 0"
}
```

The problem is the json schema `magda-registry-aspects/dcat-dataset-strings.schema.json` requires keywords to be an array with at least more than one item.

We should remove this constraint so that `[]` keyword data can be accepted by registry API with no error.

**To Reproduce**

Run the DGA ckan connector and check its pod log.

**Comment by mwu2018** [comment]
@t83714 Why there is a mini item count constraint there? What is the implication if this constraint is removed?

**Comment by t83714** [comment]
@mwu2018 
The `minLength` constraint has been added a while ago~
Not sure what's the exact reason for the `minLength` limit. 
But from git history, it seems added when we changed the field to an array.
We had a chat in slack and the conclusion is simply remove the constraint is the way to go (and probably less impact as well in my opinion)

**Comment by mwu2018** [comment]
Is this approach better? https://github.com/TerriaJS/magda/pull/3

**Comment by mwu2018** [comment]
> @mwu2018
> The `minLength` constraint has been added a while ago~
> Not sure what's the exact reason for the `minLength` limit.
> But from git history, it seems added when we changed the field to an array.
> We had a chat in slack and the conclusion is simply remove the constraint is the way to go (and probably less impact as well in my opinion)

I think you mean to remove `minItems = 1`.

**Comment by t83714** [comment]
@mwu2018 sorry, your are right. Should be ‘minItems’
