### ISSUE TITLE
No or few keywords are derived from sparse CSVs

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2635]
**Describe the bug**
Some CSV/Excel files have very little in the way of text in them, but that text is important. E.g. this SoE CSV:

https://data.gov.au/dataset/ds-dga-ebde6bad-9aef-44b0-916c-8d645ab966e5/details?q=

Looks like this:

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/900555/69603249-303d6b80-106e-11ea-893f-24e159572a13.png">

"Year" is not a good keyword, but "passenger", "car" and "ownership" are all reasonable. We need to figure out how to get those keywords out when there's not a lot of text to determine what's a keyword and what isn't.

Another example is this one:
https://data.gov.au/dataset/ds-dga-40c921f5-4ee8-4299-aadb-93e9d441c591/details?q=
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/900555/69603581-35e78100-106f-11ea-80c1-9b406495c059.png">

This includes "other arthropods" as a keyword for some reason, but it should really be including every row header as a keyword, given that there's so few rows.

**Expected behavior**
- "Passenger", "Car", "Ownership" are all generated from the CSV in https://data.gov.au/dataset/ds-dga-ebde6bad-9aef-44b0-916c-8d645ab966e5/details?q= when it's drag-dropped onto Add Dataset.
- Every row header is included as a keyword when the CSV from https://data.gov.au/dataset/ds-dga-40c921f5-4ee8-4299-aadb-93e9d441c591/details?q= is drag-dropped on the add dataset flow

**Comment by t83714** [comment]
I guess we should use a different approach for CSV files as CSV files won't a big chunk of text content for NLP processing. We should just use a simple way like (suggested in description ):
- Include headings as keywords
- Get top 10 high frequent words as keywords (we should never break words if less than 5 words in a cell)
- Optional: If text content in a cell are too long, then use NLP to determine keywords
