### ISSUE TITLE
Add the ability to add links to external files/services from the Add Dataset Flow

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2636]
**Is your feature request related to a problem? Please describe.**
While we've been very focused on files so far, many open datasets link out to data in multiple places as well as having files that are internal... or indeed _only_ consist of links out to external sources of data.

E.g. https://data.gov.au/dataset/ds-dga-fd5a0f5b-487f-4efb-bcfc-917c69432675/details?q= has both a CSV-GEO-AU / ZIP files, but also a link to DoEE's ESRI server.

**Describe the solution you'd like**
Rather than only allow _files_ to be added in Add Dataset, we should also allow for metadata to be manually added, and a link specified.

I'm thinking have some kind of "Add Manually" button next to the drop zone?

This would display a form that allows you to put in a distribution manually - specifying:
- Title
- Description
- Format
- Download URL
- Access URL
- Issued date
- Modified date

This could cover both adding external URLs of services and external URLs of files.

**Additional context**
We might want to consider allowing some of the fields above to be set on drag-dropped files too, especially description.

**Comment by alyce** [comment]
This has been addressed in the revised Add Dataset designs created last December, see InVision prototype: https://invis.io/38VM30KVGQ2

Should be user tested before implementation!

**Comment by AlexGilleran** [comment]
This is now broken up into a bunch of other issues, closing 👍
