### ISSUE TITLE
Allow upgrade to Registry DB 2.0 on large databases

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2643]
## Description

When trying to deploy 0.0.56-RC3 to data.gov.au staging, we discovered that the v2.0 upgrade causes the database to go up to 100% CPU usage, taking down everything that uses it, for _at least_ half an hour.

Specifically the problem is this line:

```
UPDATE events SET tenantId = 0 where tenantId is Null;
```

In the prod database, there are 10s of millions of events... trying to set a value on every single one is a massive operation. Trying to be cute by using a default value doesn't help either.

In the long-term, this kind of situation in general should be avoided by having some way to archive events, but in the short-term we need to be able to actually deploy to prod.

### Possibilities

- Remove this part of the migration entirely and make it so that `NULL` is equal to `0` in the registry api
- Find some less disastrous way of making this happen, like batching the updates (unlikely)
- ???

## Acceptance Criteria

-   Database upgrade from V0.0.53 to V0.0.56 can complete within 5 minutes with no loss of functionality

## Technical Notes

- Flyway gets really upset if you change a db migration file that's already run... if the checksum it recorded when it ran that migration doesn't match the file, it marks itself as corrupt and throws an error. It is possible to recover from this with `flyway repair` though... if we have to manually fix every single environment that's ever had the old V2.0 database upgrade ran on it, that is acceptable, because all of them should be our servers.

**Comment by t83714** [comment]
It seems PostgreSQL will perform an update by:
- create a new row with new values
-  mark the old row as deleted
Therefore, seems the quickest possible way of updating a large table in PostgresSQL could be:
```sql
-- create a tmp with only one tenantid column 
CREATE TEMP TABLE temp_table(
   tenantid int8 
);

-- create one row with 0 tenantid
INSERT INTO temp_table values (0);

-- create a new table by full join
CREATE TABLE new_events
AS 
SELECT events.eventid, events.eventtime, events.eventtypeid, events.userid, events."data", temp_table.tenantid 
FROM events, temp_table;

-- drop old table
DROP TABLE events;

-- rename the new table
ALTER TABLE new_events
RENAME TO events;
```

**Comment by AlexGilleran** [comment]
No dice @t83714 :(

<img width="431" alt="image" src="https://user-images.githubusercontent.com/900555/70485807-2888c700-1b44-11ea-8f54-4b620e96f47c.png">
