### ISSUE TITLE
Error loading CSV files smaller than 2MB

### ISSUE THREAD

**Issue by maxious** [magda-io/magda#2687]
**Describe the bug**
Requesting a range for bytes on a file smaller than that range causes an HTTP 416 error:
```
$ curl 'https://data.gov.au/preview-map/proxy/_0d/https://data.gov.au/data/dataset/a03ae98f-da63-4669-9abf-fef9947b666a/resource/467fcec1-fd07-407a-ae19-790262d2d6c7/download/yarra-dumped-waste.csv'  -H 'range: bytes=0-2097151'
<html>
  <head><title>Request Range Not Satisfiable</title></head>
  <body>
    <h1>Request Range Not Satisfiable</h1>
    <p>The Range requested is not available.
<br/>Range request was made beyond the end of the content,
which is 1276263 long.
  Range: bytes=0-2097151
<!--  --></p>
    <hr noshade>
    <div align="right">WSGI Server</div>
  </body>
</html>
```

**To Reproduce**

1. Go to https://data.gov.au/dataset/ds-dga-a03ae98f-da63-4669-9abf-fef9947b666a/distribution/dist-dga-467fcec1-fd07-407a-ae19-790262d2d6c7/details

**Expected behavior**
CSV file is loaded in the table

**Actual behaviour**
Console error:
```
Failed to process CSV data file:  Error
    at u._chunkError (blob:https://data.gov.au/17d6eba8-eb8a-49ad-8519-770327b554ed:1)
    at u._chunkLoaded (blob:https://data.gov.au/17d6eba8-eb8a-49ad-8519-770327b554ed:1)
    at u._nextChunk (blob:https://data.gov.au/17d6eba8-eb8a-49ad-8519-770327b554ed:1)
    at u.stream (blob:https://data.gov.au/17d6eba8-eb8a-49ad-8519-770327b554ed:1)
    at Object.parse (blob:https://data.gov.au/17d6eba8-eb8a-49ad-8519-770327b554ed:1)
    at t.onmessage (blob:https://data.gov.au/17d6eba8-eb8a-49ad-8519-770327b554ed:1)
```

**Additional context**
https://github.com/magda-io/magda/pull/2489
The 2MB range seems to come from https://github.com/magda-io/magda/blob/d43e9783e22afa5e707147715070af569b96476a/magda-web-client/src/config.ts#L253

**Comment by AlexGilleran** [comment]
Ah jeez, makes sense that it would happen though.

I guess the logic should be more like.

1. Do a `HEAD` on the URL of the file
  - Bad response? Don't preview the file
2. Get `content-range` or `content-length` header in the response from the HEAD to get the length of the file.
  - Neither of these headers? Don't preview the file
3. GET the file with the end of the Content-Range set to the minimum between the length of the file or 2mb
