### ISSUE TITLE
API Documentation for Storage API

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2692]
## Description

The storage api is currently missing from the [API Docs](https://dev.magda.io/api/v0/apidocs/) - documentation for each API endpoint needs to be added, just as it is for the other services.

## Acceptance Criteria

-   All api calls in the storage api are documented

## Technical Notes
You can see other examples of how this is done in the other node.js apis.

Correspondence-api's createApiRouter should have an example.

**Comment by VerumEmanio** [comment]
I'm new to documenting API endpoints. Would this be a good issue for me to pick up, or are you looking for someone with more experience?

**Comment by AlexGilleran** [comment]
Hi @VerumEmanio! This one's probably easiest for @sajidanower23 as he's written the first version of the storage api :). But if you're looking for somewhere to start, there's a bunch of issues of varying complexity labelled with `good-first-issue` (https://github.com/magda-io/magda/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22), or most issues labelled with "bug" (https://github.com/magda-io/magda/issues?q=is%3Aopen+is%3Aissue+label%3Abug) should be stand-alone enough to try to tackle!

**Comment by AlexGilleran** [comment]
e.g.

```javascript
    /**
     * @apiGroup Correspondence API
     *
     * @api {post} /v0/send/dataset/request Send Dataset Request
     *
     * @apiDescription Sends a request for a dataset to the site administrators
     *
     * @apiParam (Request body) {string} senderName The name of the sender
     * @apiParam (Request body) {string} senderEmail The email address of the sender
     * @apiParam (Request body) {string} message The message to send
     *
     * @apiSuccess {string} status OK
     *
     * @apiSuccessExample {json} 200
     *    {
     *         "status": "OK"
     *    }
     *
     * @apiError {string} status FAILED
     *
     * @apiErrorExample {json} 400
     *    {
     *         "status": "Failed"
     *    }
     */
```
