### ISSUE TITLE
Minio deploys regardless of tags

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2701]
**Describe the bug**
Right now `minio` is included with all deployments regardless of what tags are passed - in particular this means for ui-only previews, we're allocating a full stateful set for minio every time we deploy, which is more expensive than we'd like.

**To Reproduce**
Deploy via helm and set all `tags` to `false`.

**Expected behavior**
Nothing gets deployed

**Screenshots**
```
kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
magda-minio-7b6499644f-rrtd2   1/1     Running   0          19m
```

**Additional context**
This is probably because something is missing in `requirements.yaml`

**Comment by t83714** [comment]
Seems a simple issue. Will probably look at it after https://github.com/magda-io/magda/pull/2734 is merged to avoid merge conflicts
