### ISSUE TITLE
Add a linter for YAML files

### ISSUE THREAD

**Issue by sajidanower23** [magda-io/magda#2709]
## Description

YAML files, particularly the ones generated by kubernetes, should be linted, because no error is thrown when the file is invalid and that leads to issues that are super hard to debug.

## Acceptance Criteria

-   The CI pipeline has a job that checks for invalid YAML.

## Technical Notes

Maybe use [yamllint](https://yamllint.readthedocs.io/en/stable/index.html).

**Comment by sajidanower23** [comment]
`yamllint` cannot process files from stdin. It might be worth giving this a whirl:
https://kubeval.instrumenta.dev/

**Comment by t83714** [comment]
This PR has added helm lint to our gitlab CI:
https://github.com/magda-io/magda/pull/2734
If you need the function locally, you can use the helm's built-in function:
`helm lint path-to-chart -f valuefile`
See here: https://helm.sh/docs/helm/helm_lint/
