### ISSUE TITLE
Upgrade to latest Kubernetes and Helm

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2727]
## Description
Recently there have been a few developments in Kubernetes land:

- Helm 3 has been released (https://helm.sh/docs/faq)
- Kubernetes 1.16 has been released, which is incompatible with some of our charts.

We should upgrade - and I think it makes sense to group these together to make the test / release a bit easier.

### Acceptance Criteria
- Magda now uses Helm 3 instead of Helm 2
    - Documentation has been updated to reflect this - in particular there should be no instructions about creating a user for tiller anymore seeing how there is no tiller
    - Our helm setup has been modified to use helm 3 - in particular, we'll need to move the contents of `requirements.yaml`
    - Deployment via CI still works
    - Deployment via command line still works
    - Deployment via `terraform` still works
- Magda is compatible with the latest version of Kubernetes
    - Magda can be deployed onto a kubernetes environment, with all services, without any warnings about API deprecation
- Write a migration guide
- Make sure all the non-core repos are also compatible

**Comment by t83714** [comment]
🎉 Yeah~ Helm 3 is coming to Magda

**Comment by sajidanower23** [comment]
A migration guide is not necessary. Follow the `Building and Running` instructions again once you have Kubernetes 1.17, Helm 3 and Minikube 1.7+ installed.
