### ISSUE TITLE
K8S Namespace is unable to be set to non-default in Admin API

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2736]
**Describe the bug**
From Dominik at Merck:

> I painfully found out that K8S namespace is hardcoded to “default” here https://github.com/magda-io/magda/blob/release/0.0.56/magda-admin-api/src/k8sApi.ts#L20 and that some additional RBAC settings were required

**Comment by t83714** [comment]
closed via https://github.com/magda-io/magda/pull/3075
