### ISSUE TITLE
Add "Edit" Functionality as per new designs

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2754]
## Description

We currently have editing functionality that we hacked together, but now that we've got a whole nicely designed Add Dataset flow, we should be using that for editing datasets.

## Design
There's a whole set of designs for edit at https://projects.invisionapp.com/share/KMVQ7DH652J#/screens/404720658, but they're predicated on a draft approval flow.

For now, ignore everything to do with drafts - editing should work on existing (fully published) datasets, and saving should immediately change the current metadata in the registry rather than going through an approval flow.

## Acceptance Criteria

-   An "edit" button is present on the dataset page for admins, which opens the edit functionality
-   The edit functionality uses all the same components as the current Add Dataset flow, but with changes to copy where appropriate (in particular, the title should be "Edit Dataset" not "Add a Dataset".
-   If "Save and Exit" is clicked, or the flow is completed (i.e. the user gets through to the end), the changes should immediately be saved in the most recent version of the record.

## Technical notes

- We should be able to reuse nearly everything from the Add Dataset flow here. Most likely the best way is to have two different page components that pass in different props for things like the title caption, but it's up to whoever does this as to the best way to implement it.

## Out of Scope

-   Anything to do with drafts and/or approvals (for now)

**Comment by alyce** [comment]
I've created an [alt design for the 'you're done' page](https://projects.invisionapp.com/share/KMVQ7DH652J#/screens/407557571) that doesn't reference approvals - so then all you need to do is skip the "add a note for your approver" screen
