### ISSUE TITLE
Remove ESRI portal connector related code from Magda

### ISSUE THREAD

**Issue by mwu2018** [magda-io/magda#2786]
## Description

ESRI portal connector is a fully customised connector that is built for Digital twin project.

As Terria team has started to maintain a more up to date version (forked from the [previous magda esri connector repo](https://github.com/magda-io/magda-esri-portal-connector)) here:
https://github.com/TerriaJS/magda-esri-portal-connector
, we don't need to maintain ESRI portal connector anymore and should remove related code from Magda core repo.

## Acceptance Criteria
- Remove the following schema files in `magda-registry-aspects` (and updated [published NPM package](https://www.npmjs.com/package/@magda/registry-aspects)). Those schemas are specific to the esri portal connector and should be defined by the connector itself. 
  - esri-access-control.schema.json
  - esri-dataset.schema.json
  - esri-resource.schema.json
  - group.schema.json
- Mark [Magda esri connector repo](https://github.com/magda-io/magda-esri-portal-connector) as archieved and point anyone who wants to look at it to [Terria team's esri portal repo](https://github.com/TerriaJS/magda-esri-portal-connector)
- Remove esri connecctor from Magda chart [dependencies list](https://github.com/magda-io/magda/blob/83a993eddeb3ffd7efce195cca51a416bc892a45/deploy/helm/magda/Chart.yaml#L329) and remove other reference accordingly (e.g. [this](https://github.com/magda-io/magda/blob/83a993eddeb3ffd7efce195cca51a416bc892a45/deploy/helm/magda/values.yaml#L4))
- Remove esri specifc value file [minikube-esri-dev.yml](https://github.com/magda-io/magda/blob/master/deploy/helm/minikube-esri-dev.yml)

**Comment by t83714** [comment]
@mwu2018 
Since a forked version ESRI connector is already created & maintain by terria, Magda probably don't need to maintain our [esri-portal-connector repo](https://github.com/magda-io/magda-esri-portal-connector)  anymore, right?

**Comment by mwu2018** [comment]
Right. Magda does not need to maintain esri portal connector repo. However, this issue is about the published package `registry-aspects` that includes unwanted and incorrect aspect schemas.

**Comment by t83714** [comment]
👍 No problem to remove those aspects.
However, the current [esri-portal-connector repo](https://github.com/magda-io/magda-esri-portal-connector) actually relies on those aspect schemes. 
I was thinking of marking the repo as archived and point anyone (who wants to look at it) to your forked repo as once remove those aspects from the package.
I also want to remove other presence of `esri-portal-connector` in our repo as well --- particularly, helm chart --- we don't need it as standard dependencies anymore (even it's disabled).
Will update this ticket so we will cover everything

**Comment by t83714** [comment]
@mwu2018 Updated your ticket. Let me know ( or update it directly) if anything is missing
