### ISSUE TITLE
Adding ESRI Rest to dataset by URL no longer works

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2830]
**Describe the bug**
Adding an ESRI REST URL via the Add Dataset flow now always seems to come back with an error. 

In the logs, the error that comes up is:

```
2020/05/13 11:18:00 stderr: Error: Failed to retrieve data from esri API: https://services1.arcgis.com/okWBWNlpfMx5q1bT/arcgis/rest/services/Stormwater_Points/FeatureServer/0?f=json Error: can't locate id or name
2020/05/13 11:18:00 stderr:     at /usr/src/app/component/dist/index.js:55:19
2020/05/13 11:18:00 stderr:     at Generator.next (<anonymous>)
2020/05/13 11:18:00 stderr:     at fulfilled (/usr/src/app/component/dist/index.js:5:58)
2020/05/13 11:18:00 stderr:     at process._tickCallback (internal/process/next_tick.js:68:7)
2020/05/13 11:18:00 POST / - 500 Internal Server Error - ContentLength: 397
```

**To Reproduce**

1. Go to the first page of Add Dataset
2. Enter an ESRI REST url under "(and/or) Link to an API or web service". I tested with:
    - https://services2.arcgis.com/dEKgZETqwmDAh1rP/arcgis/rest/services/City_Plan_2014_Airport_environs_overlay_Obstacle_Limitation_Surfaces_OLS_boundary/FeatureServer/0
    - https://services2.arcgis.com/dEKgZETqwmDAh1rP/arcgis/rest/services/City_Plan_2014_Airport_environs_overlay_Obstacle_Limitation_Surfaces_OLS_boundary/FeatureServer/0
    - https://services1.arcgis.com/okWBWNlpfMx5q1bT/arcgis/rest/services/Stormwater_Points/FeatureServer/0
3. This error comes up:
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/900555/81806971-922c5780-9560-11ea-8665-a721071190aa.png">

**Expected behavior**
The ESRI REST service should have its metadata harvested.

**Comment by t83714** [comment]
Some ESRI system/setup will always return id = 0 (even for different dataset).
So the following validation code will trigger the error:
```
if (!data?.id || !data?.name) {
        throw new Error(
            `Failed to retrieve data from esri API: ${url} Error: can't locate id or name`
        );
    }
```
I will remove the following id field validation code (probably still check whether name is blank as a way of telling whether it's a valid data source):

**Comment by t83714** [comment]
So for an ESRI URL, both `id` & `name` could be absent (depends on URL type and system etc).
For the purpose of validating an ESRI URL, will check one of the following fields must exist:
- `extent`
- `fullExtent`
- `initialExtent`

If more than one fields above present, we will pick an available field to use from the top list above. (e.g. `extent` has higher priority than `fullExtent`)

**Comment by t83714** [comment]
Got another problem that some ESRI server may output extent in:
```
extent: {
xmin: 468770.2703999998,
ymin: 6966850.8054,
xmax: 520510.7213000003,
ymax: 7032527.8387,
spatialReference: {
wkid: 28356,
latestWkid: 28356
}
},
```
We need to find a way to convert it back to lat / lang using wkid supplied (here 28356)

**Comment by t83714** [comment]
This commit: https://github.com/magda-io/magda-function-esri-url-processor/pull/1/commits/ae0731f0106ec397f9f99e8c7f83845a2e552eb8
Added the support of auto transforming coordinate reference system.

**Comment by t83714** [comment]
Fixed in https://github.com/magda-io/magda-function-esri-url-processor/pull/1 and PR merged
