### ISSUE TITLE
Figure out what effect dragging new files should have on metadata

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2839]
## Description

Currently most of our thinking about how Add Dataset should work is based around how to put a new dataset on. However, what happens when you edit an existing dataset, but replace the existing file? Should we replace the existing metadata with generated metadata? Even overwriting existing user-input metadata? Do we need some way to ask the user what metadata they want to keep?

**Comment by alyce** [comment]
The metadata comparison screens can be seen from here onwards (once the replace flow is complete) https://projects.invisionapp.com/share/GMXFFVZ5Y8X#/screens/420440073
