### ISSUE TITLE
Setup instance for PM&C

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2856]
## Description
If we want to demo, we need an instance to demo on. So let's make one.

## Acceptance Criteria
- Must be stable (no preemptible instances)
- Must be able to be quickly upgradable according to changes on a branch in the Magda repo
     - Should have a quick bit of doco explaining how to deploy
- Must have only email-and-password authentication available
    - Should have basic authentication as well
    - Must have all the email addresses for trial users (ask @AlexGilleran) set up and working.
- No need for HA or anything more than one-instance-per-server
- Must have some kind of basic PM&C branding (see https://api.gov.au/service/5bd921345149e90004f326a7 for the logo, https://www.pmc.gov.au/)
- Should have feature flags set up such that it
    - Allows Add Dataset (not preview)
    - Doesn't have placeholder features
    - Doesn't have approval workflow
    - (turn off everything not 100% ready)
- Should have a nice domain like pmc-demo.magda.io, with working https
- Uses a Google Cloud SQL database with backups turned on

**Comment by t83714** [comment]
Config & Doc Repo is here:
https://github.com/magda-io/pmc-config
