### ISSUE TITLE
Remove use of `escapeIdentifier` in registry API

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2869]
See this comment:

Yeah~ I don't think we have used any special chars in identifiers.
How about we remove this `escapeIdentifier ` function and revert it back to the `SQLSyntax.createUnsafely`?

_Originally posted by @t83714 in https://github.com/magda-io/magda/pull/2863_

**Comment by t83714** [comment]
closed via PR https://github.com/magda-io/magda/pull/2873
