### ISSUE TITLE
Visualisations don't always show up on dataset page

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2879]
**Describe the bug**
Currently visualisations don't show up on the dataset page, even if there is potential for a dataset to be visualised - e.g. it's possible to click on individual distributions and see them visualised on the distribution page, but there's nothing on the dataset page.

This is probably because it's dependent on the result of the broken-link-minion, which has gotten pretty unreliable and slow, and doesn't run on some instances of Magda (e.g. where all data is internal).

**To Reproduce**
1. On an instance of magda without minions, ingest data.nsw.gov.au
2. Go to this dataset: https://data.gov.au/dataset/ds-nsw-c647a815-5eb7-4df6-8c88-f9c537a4f21e/details?q=coronavirus
3. Note that there is no visualisation on the dataset page.
4. Open the CSV distribution and note that there is a visualisation on that page.

**Expected behavior**
- If any distribution can be visualised, it should show up on the dataset page.
- Magda should ignore the output of the broken link minion altogether in deciding what should be visualised.
- The visualisation minion should only be used to determine how to visualise something, not whether to visualise it
- The frontend should try to visualise even if there's no output from the visualisation minion available

i.e. once this is fixed, an instance with no minions and the above NSW dataset ingested should show the visualisation of the CSV on the dataset page.

**Comment by t83714** [comment]
the chart preview is currently disabled when brokenlink status not available here:
https://github.com/magda-io/magda/blob/5a895d5989729f7ad84950140d9ee00f0f046c88/magda-web-client/src/Components/Dataset/View/DatasetPagePreview.js#L14

Simply remove `d.linkStatusAvailable && d.linkActive` should make the chart preview show.
the chart preview program itself can figure out csv layout even visual minion not process the file yet (although works better when it does exsit)
