### ISSUE TITLE
Basic API Keys

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2897]
## Description

Following on from @sajidanower23 's spike in #2883

Currently accessing the API without using a browser is super super super annoying. We should have some kind of easy way to generate an API key that authorises you, so that you don't have to go through the process of logging in, copying the cookie header and then putting it in your requests (only to have it be invalidated after 24 hours).

Mainly what we want from this is:
- Simple for us to implement bit-by-bit, as always
- Simple for other people to use
- Secure

## Acceptance Criteria
-   An API key can be generated for a user, which when passed in the `X-Magda-API-Key` header will authenticate them as that user, meaning that there's no need to pass a session id in the cookie or have a cookie at all
- A single user can have zero-to-many api keys
- API keys are always generated for a user - i.e. we don't allow people to set them
- API keys can be deleted once generated. Once the API key is deleted, any requests with that API key should start failing with `400` as soon as possible
- API keys can be generated / removed via a command line tool, like for passwords currently (maybe even extend the existing one?)
    - It's OK for this to access the database directly, we don't necessarily need an API for doing this stuff _yet_
- When a request with an API key attached to it hits the gateway:
    - If the API key is valid, it should be associated with a user and have a signed JWT attached to it before being passed on to the target api, so it looks the same as a call coming in with a cookie from the point of view of other systems
    - If the API key is invalid, return 400 (? or maybe there's a better code) regardless of what the request is
    - So essentially API keys and session cookies are both first-class ways to authenticate
- The system that looks after API keys should be the auth api
    - API keys should be stored in the auth db
    - There needs to be a simple API that allows for API keys to be checked and associated with a user in the authorisation api, that is accessed by the gateway upon receiving a request with `X-Magda-API-Key` present
- API keys should be hashed and salted just like a password

## Out of Scope
-   Having separate API scopes per key. This would be cool but we can add it much later.
-   Rate limiting - we'll refine another issue

**Comment by t83714** [comment]
Will also include a header `X-Magda-API-Key-Id` header to facilitate key looking up

**Comment by t83714** [comment]
For invalid API key, will return 401 Unauthorized to indicate an authentication error.
