### ISSUE TITLE
Inquiry About the Microservice Architecture Employed by `magda`

### ISSUE THREAD

**Issue by research-sudo** [magda-io/magda#2904]
I am a researcher investigating the open source projects that are designed by the microservice architectural style (https://martinfowler.com/microservices/). My preliminary investigation shows that the **_magda_** project (https://github.com/magda-io/magda) is designed by the microservice architectural style.

Can you please **_confirm_** if my interpretation that this project is designed by following the microservice architectural style is correct? Note that if the projects (e.g., frameworks or tools) support the development of microservices-based systems but themselves are not designed by following the microservice architectural style, please also clarify it?
If my interpretation is correct, what **_features_** or **_characteristics_** of the architecture of this open source project show that the microservice architectural style has been used?
**Optional Question:** Do you know any other open-source projects that are designed by following the microservice architectural style?
I would be greatly appreciative if you can kindly answer the three questions above.

**Comment by AlexGilleran** [comment]
The issues tracker isn't a discussion board. If you want to learn more about how Magda is designed there's a whole explanation on https://magda.io/docs.
