### ISSUE TITLE
Allow incoming request explicitly control the `cache` behaviour from Gateway

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2927]
# Allow incoming request explicitly control the `cache` behaviour from Gateway

Currently, Gateway will set a default cache header when an incoming request doesn't carry `cache` header.

```typescript
// Add a default cache time of 60 seconds on GETs so the CDN can cache in times of high load.
        if (
            req.method === "GET" &&
            options.defaultCacheControl &&
            !proxyRes.headers["Cache-Control"] &&
            !proxyRes.headers["cache-control"] &&
            !req.headers["Cache-Control"] &&
            !req.headers["cache-control"]
        ) {
            // the default value for `options.defaultCacheControl` is `"public, max-age=60"`
            proxyRes.headers["Cache-Control"] = options.defaultCacheControl;
        }
```

We tend to use it as a way of disabling cache from frontend recently (So, the gateway won't send default `public, max-age=60` cache header value when `request` carries a cache-header).

This might not be ideal as there would be no cache-control header on `response` and the browser might still decide to cache the content locally (as there is no cache header to indicate browser not to do so).

Probably for the same reason Terria set the default response cache header to `private, max-age=0`

https://github.com/TerriaJS/magda/blob/16c2b67b7e78a45f59f3e6bf68f920a37e02543e/magda-gateway/src/createBaseProxy.ts#L67

However, this makes all content not cachable as every `response` would carry the `private, max-age=0` header.

I think we should:
- The current behaviour should still stay (i.e. when `Cache-Control` not present on incoming request, we set `Cache-Control ` to default value) 
- Add ~support a custom header e.g. `Magda-Disable-Cache`~ We gonna use existing `Cache-Control` header on request to trigger the new behivour
  - ~Why a custom header (rather than re-use `Cache-Control` on request)?~
  - ~Based on my test, chrome might overwrites your outgoing request `Cache-Control` headers when you are `networks` tab~
- When ~`Magda-Disable-Cache` = true~ `Cache-Control` header contains `no-cache` keyword on the incoming request, the gateway should:
  - Do NOT set default `Cache-Control` header value and set the following header instead:
    - `Cache-Control: max-age=0, no-cache, must-revalidate, proxy-revalidate`
    - `Expires: Thu, 01 Jan 1970 00:00:00 GMT`
    - `Last-Modified: xxxxx` (current time in <day-name>, <day> <month> <year> <hour>:<minute>:<second> GMT format)

Technically, the last modified header might be redundant but good to leave here to make sure.

Update on 26th Aug 2020: Based on @AlexGilleran 's feedback, we're gonna use existing `Cache-Control` header to address the "custom header incompatible concerns"

**Comment by soyarsauce** [comment]
Related updateExtraInput

**Comment by soyarsauce** [comment]
Related https://github.com/TerriaJS/nsw-digital-twin/issues/345
