### ISSUE TITLE
Allow Magda serves multiple Web UI server 

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2929]
### Allow Magda serves multiple Web UI server 

When customising Magda as their own solution, people may want to keep existing Magda UI running while implementing their own UI (to leverage magda's existing `login` or `Admin panel`) functionality.

We currently allow people to replace the UI but Magda web UI can't be running at the same time from a different path.

We probably can:
- No changes to `Gateway` (rather than #2928)
- Update `web-server` to:
  - Add helm chart parameter `uiBaseUrl`. Default Value "/". 
    - e.g. `/magda-web-ui` means serving magda UI from path `/magda-web-ui/`
  - Add proper `<base />` tag to 
- Update `web-client` 
  - Add `basename` to `BrowserRouter` component in `index.js`. Its value should be same as `baseUrlPath` that receives as part of [web-server-config](https://github.com/magda-io/magda/blob/master/magda-web-client/src/config.ts)
  - Replace all `<a>` tags with `<Link>` where applicable

@mwu2018  already implement most it [at here](https://github.com/TerriaJS/magda/blob/16c2b67b7e78a45f59f3e6bf68f920a37e02543e/magda-web-server/src/getIndexFileContent.ts#L12)

Although, we probably can simplify a bit (e.g. we don't need to replace `getIncludeHtml`)

**Comment by soyarsauce** [comment]
We can generalise a lot of the changes we made in https://github.com/TerriaJS/magda/pull/14
