### ISSUE TITLE
Time Travel API response 500 sometimes

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2977]
### How to reproduce:

Accessing this URL of test site:

https://dev.magda.io/api/v0/registry/records/ds-dga-ab7eddce-84df-4098-bc8f-500d0d9776d1/history/26690082

You will get:
```
{
message: "The server encountered an unexpected error."
}
```
and the followings printed in log:

![image](https://user-images.githubusercontent.com/674387/94094310-82077b80-fe62-11ea-8343-5171b081bd3e.png)

Related to #2915

**Comment by soyarsauce** [comment]
Related https://github.com/magda-io/magda/issues/2705

**Comment by t83714** [comment]
@soyarsauce Thanks for the reference --- probably mine was a duplicate ticket
I also hit into the bug as well for my other ticket😄 
It's tenantId related and seem not hard to fix~ Will keep you updated

**Comment by t83714** [comment]
[This commit](https://github.com/magda-io/magda/commit/ec91e90de3703f4438daebb7577c4925c67116ff) should fix both #2977 & #2705 
Will merge to master once the full PR is completed
