### ISSUE TITLE
Ordering of PUT response from registry API

### ISSUE THREAD

**Issue by soyarsauce** [magda-io/magda#2987]
**Describe the bug**
Doing a PUT on a record will return a different ordering of the aspects than fetching (resulting in a difference detected every single time if you are relying on the response of that PUT.

**To Reproduce**

PUT to `https://dev.magda.io/api/v0/registry/records/test-ordering` with
```
{
    "aspects": {
        "information-security": {
            "classification": "UNOFFICIAL"
        },
        "dcat-dataset-strings": {
            "title": "Xy"
        }
    },
    "authnReadPolicyId": "object.registry.record.public",
    "id": "test-ordering",
    "name": "test-ordering",
    "tenantId": 0
}
```
2. observe a response
```
{
    "aspects": {
        "dcat-dataset-strings": {
            "title": "Xy"
        },
        "information-security": {
            "classification": "UNOFFICIAL"
        }
    },
    "authnReadPolicyId": "object.registry.record.public",
    "id": "test-ordering",
    "name": "test-ordering",
    "tenantId": 0
}
```

3. GET on https://dev.magda.io/api/v0/registry/records/test-ordering?optionalAspect=dcat-dataset-strings&optionalAspect=information-security

4. observe "information-security" aspect comes first again
```
{
    "aspects": {
        "information-security": {
            "classification": "UNOFFICIAL"
        },
        "dcat-dataset-strings": {
            "title": "Xy"
        }
    },
    "authnReadPolicyId": "object.registry.record.public",
    "id": "test-ordering",
    "name": "test-ordering",
    "tenantId": 0
}
```

**Expected behavior**
If you send a PUT with the results from GET, it should return the same order

**Comment by soyarsauce** [comment]
Actually you can reproduce this within a single aspect as well, if it has nested objects

**Comment by t83714** [comment]
I think it's hard to guarantee that...
See JSON standard here: https://www.json.org/json-en.html
> An object is an `unordered` set of name/value pairs.

i.e. most third-party libraries & database etc won't guarantee the order of keys while processing the JSON object.
The registry API actually do some Json Patch calculations before applying it to the database (that's part of process of generating events).
I guess it's the behaviour of JSON patch library we used.

Even the Postgres database's current behaviour (when you pull it directly from registry api) meet your requirements and match your original order, we probably can't rely on that behaviour --- as those JSON data is stored as JSON or JSONB (binary JSON) type in Postgres, the way who it handles JSON data might be changed (as the key order is defined as unordered in spec).

Can we access aspect data by its key? 
Or you can enforce your own order at your side (so it won't be impacted by third-party software or version differences) -- I assume you are doing some text-based operation on JSON data. e.g. always sort the key alphabetically.

**Comment by soyarsauce** [comment]
Thanks @t83714 - I think we'll just have to client-side sort this as part of the original stale-check logic as depicted in [record editor out-of-order-aspects](https://github.com/TerriaJS/terrace/issues/147).

Happy for you to close this if you agree 🙂

**Comment by t83714** [comment]
Thanks @soyarsauce 👍
