### ISSUE TITLE
Admin Panel Make Admin feature should add adminRole to the user as well

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#3033]
### Admin Panel Make Admin feature should add adminRole to the user as well

The user management page currently only set `isAdmin` field:

https://github.com/magda-io/magda/blob/f5686bbd0d643e6b93af0893039b61548d04b12a/magda-web-client/src/Components/Account/AccountsAdminPage.js#L77

We need to make this function to add an admin role to the user as well

### Updates

We probably also need a simply dedicated cmd tool to set/unset a user as admin. This is will be useful for the newly installed instance when you don't have an admin account yet.

**Comment by soyarsauce** [comment]
Some other notes, from internal terria projects:

>To clarify - in the editor we use the isAdmin flag: https://github.com/TerriaJS/terrace/blob/master/lib/Components/Profile.jsx#L40-L63

>However in magda there's two forms of admin,

>    isAdmin
    role "00000000-0000-0003-0000-000000000000"

>And the UI in magda currently only toggles the first one, but does not set the second

**Comment by soyarsauce** [comment]
To clarify - in the editor we use the `isAdmin` flag: https://github.com/TerriaJS/terrace/blob/master/lib/Components/Profile.jsx#L40-L63

However in magda there's two forms of admin,
- `isAdmin`
- role `"00000000-0000-0003-0000-000000000000"`

And the UI in magda currently only toggles the first one, but does not set the second

**Comment by soyarsauce** [comment]
Parts of magda will only use `role`, so we will often run into a scenario where:
- a user has the `isAdmin` flag but not the role

this will lead the editor UI to think they have full admin, bypassing the client-side admin check & leading to unintended catalog changes as they won't see all records

**Comment by soyarsauce** [comment]
Related: https://github.com/magda-io/magda/issues/2248
