### ISSUE TITLE
Helm will attempt to install CRD even when `global.openfaas.enabled` is set to false

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#3094]
### Helm will attempt to install CRD even when `global.openfaas.enabled` is set to false

Currently, when `global.openfaas.enabled` is `false`, the `openfaas` dependency is supposed to be turned off.

However, due to [this known bug](https://github.com/helm/helm/issues/8508) of helm, the CRD will still be installed even when dependency is turned off.

### Solution

We should remove `openfaas` as a dependency of `magda-core` chart and add it as the dependency of `magda` chart.
People who 100% don't want anything from `openfaas` (due to permission issue e.g.) can choose to depends on `magda-core` to remove `open-faas`

**Comment by jackson-chris** [comment]
This still continues to be a problem. Please fix.

**Comment by t83714** [comment]
Hi Christopher,

I think this issue has been resolved already.

If it did happen again to you, could you please share some information re:
your setup so I can try to re-produce it?

Cheers,

Jacky
