### ISSUE TITLE
Existing or potential support for ERRDAP servers

### ISSUE THREAD

**Issue by steviewanders** [magda-io/magda#3154]
**Is your feature request related to a problem? Please describe.**
I'd love to use Magda to support querying ERRDAP servers (https://www.ncei.noaa.gov/erddap/index.html) but can't find mention of it among the data connectors or the project.

**Describe the solution you'd like**
Someone to tell me I overlooked it or advice on how to add it myself? - I had a look at https://github.com/magda-io/magda-dap-connector and guess it will involve something similar for it's API.

**Describe alternatives you've considered**
Not adopting Magda?

**Additional context**
I did try searching the project and various chat/contact channels for the appropriate place to ask this question - but it was unclear which were current and preferred by the project :)   So thank you to anybody reading this and providing information!

**Comment by t83714** [comment]
Hi @steviewanders, 
had a quick look --- I don't think we have a connector supports it.
You can find all existing connectors from: 
https://github.com/magda-io?utf8=%E2%9C%93&q=magda+connector
If you're interested in building your own connectors, you might want to have a look at this doc:
https://github.com/magda-io/magda/blob/master/docs/docs/how-to-build-your-own-connectors-minions.md
And use existing connector repos as examples.

**Comment by steviewanders** [comment]
Hi @t83714, 

Thanks for taking a look and confirming! Looks like the existing JSON connectors should be fairly easy to adapt to suit.
