### ISSUE TITLE
\u0000 needs to be removed from JSON all data

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#3161]
## \u0000 needs to be removed from JSON all data

Some users see an error message `unsupported Unicode escape sequence, \u0000 cannot be converted to text` while input data to registry.

This is due to design change in postgresql v9.4 (GPDB v6). There is a postgresql community post which talked about this change, a quote was selected from the community post, pasted below:

Source:
https://www.postgresql.org/message-id/8239.1500489054%40sss.pgh.pa.us

> Matthew Byrne writes: Are there any plans to support \u0000 in JSONB and, relatedly, UTF code > point 0 in TEXT?

> No. It's basically never going to happen because of the widespread use of C strings (nul-terminated strings) inside the backend. Making \0 a legal member of strings would break all those internal APIs, requiring touching far more code than anyone would want to do. It'd likely break a great deal of client-side code as well.
 
> The GPDB R&D team also confirmed, even in postgresql v12, this usage will report the same error. The R&D team has no plans to change this design.

[a possible workaround](https://community.pivotal.io/s/article/loading-data-report-error-unsupported-Unicode-escape-sequence?language=en_US):
```
SELECT (regexp_replace(the_string::text, '
u0000', '', 'g'))::json;
```

We need to sanitise all json input to postgresQL DB.

**Comment by Evdlaar** [comment]
We used the supplied anonymized and fictional dataset. Uploading this file to our Magda installation resulted in the mentioned error.
[Customers_Anon.zip](https://github.com/magda-io/magda/files/6669620/Customers_Anon.zip)

**Comment by t83714** [comment]
@Evdlaar Thanks for the sample file provided.
I can reproduce your error with the sample CSV.
Notice the csv file is encoded in UTF-16 which is where the `\u0000` is introduced by our keywords prediction module.
Before the UTF-16 encoding support issue is fixed, you probably can save your file as UTF-8 encoding to avoid this issue.
