### ISSUE TITLE
Upgrade Elasticsearch to OSS Opensearch 2.x

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#3261]
### Upgrade Elasticsearch to OSS Opensearch 2.x

> If too much work possible, we should look at upgrading to OSS Opensearch 1.x only

- our current version OSS Elasticsearch `6.8.22`

Planned upgrade path:
- upgrade to 7.10.2
- and migrate to OpenSearch 1.x
- try migrating to OpenSearch 2.0
  - might require many code changes, we can leave the upgrade to OpenSearch 1.x later

### Works required:
- Helm chart changes:
  - for min. download
  - Adopt Opensearch architecture
  - Better cluster management
- Code changes
  - how to handle / "Drop support for JDK 8" (required by Opensearch 2.x)
  - how to migrate all test cases (depends on OSS Elasticsearch  code base at this moment)
  - accommodate breaking API changes among versions

# Resources:
- https://opensearch.org/docs/latest/upgrade-to/upgrade-to/
- https://opensearch.org/docs/latest/upgrade-to/docker-upgrade-to/
- https://opensearch.org/docs/latest/breaking-changes/

**Comment by ljowen** [comment]
Update 13 May: Testing on larger scale cluster

**Comment by t83714** [comment]
- A replicate cluster & DB has been set up to replicate the DGA setup with a larger datasets scale
- v3.0.2 has been deployed tested and followed with migration to v4 test to verify the migration steps drafted on migration v4 docs
- the test was done and successful with a few helm chart logic bugs fixes along the way
- the next is to do more testings on the staging cluster for the following items:



- [ ] 1> Timed out while waiting for a dynamic mapping update – How to solve this Elasticsearch exception

https://opster.com/es-errors/timed-out-while-waiting-for-a-dynamic-mapping-update/

https://medium.com/john-lewis-software-engineering/elasticsearch-handling-mappings-for-dynamic-document-structures-8af77512272b

  - [ ] 2> test Initial set master node list procecss

  - [ ] 3> test fault resilience

  - [ ] 4> test Readiness probe / indexing creating timeout at cluster initiation stage

  - [ ] 5> 10000 results issue

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html#track-total-hits

  - [ ] 6> replace `master` with `cluster_manager` role

  - [ ] 7> evaluate  whether should adopt index.auto_expand_replicas

**Comment by t83714** [comment]
released v4.0.0-alpha.1: https://github.com/magda-io/magda/releases/tag/v4.0.0-alpha.1

**Comment by t83714** [comment]
released: https://github.com/magda-io/magda/releases/tag/v4.0.0-alpha.2
Ready to merge to `next` branch --- might get one more ticket done before release official v4

**Comment by t83714** [comment]
closed via PR: https://github.com/magda-io/magda/pull/3506
