### ISSUE TITLE
upgrade to v1.0.1 without loosing metadata

### ISSUE THREAD

**Issue by cleman95** [magda-io/magda#3281]
I'm trying to upgrade Magda from v0.0.58 to v1.0.1 using the helm chart due to the log4shell vulnerability. 
But I've seen that combined DB has now changed and i'm wondering if they were a solution to keep my old PVC with this new combined DB. 

I have tried to Edit the statefullSet and change the VolumeClaimTemplate but it's forbiden. I can't change the name of my PVC and can't clone it with the data-combined-db-postgresql-0 name since permission inside are not the same.

Is it possible to upgrade with helm and still have metadata in Magda with the new combined DB? 

Is there a solution to migrate metadata from a combined DB in v0.0.58 to a combined DB in v1.0.1 with the two instances deployed on kubernetes? 

Thanks for your help

**Comment by t83714** [comment]
Hi @cleman95 you probably can deploy the new version into a different namespace and manually migration the database before switch over the traffic.
here is some recommendations might help: 
https://github.com/magda-io/magda/blob/master/docs/docs/migration/0.0.60-to-1.0.0.md

**Comment by t83714** [comment]
by the way, by upgrading to the v1, the existing PV won't be removed. The new version will created a new PV & PVC instead.
i.e. your existing database won't be deleted unless you manually delete the PV.
We can't reuse the existing PV as v1 use postgreSQL version 13.
