### ISSUE TITLE
No key / secrets cert-manager setup for dev & prod cluster

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#3476]
### No key / secrets cert-manager setup for dev & prod cluster

By leveraging [google workload identity federation](https://cloud.google.com/iam/docs/workload-identity-federation), we can update our current cert-manager setup to no  key / secrets secret.

This will save us the efforts of key rotation every 90 days

**Comment by staffordsmith83** [comment]
UPDATE 2 August 2023:

Trying to set up so key rotation is not required in the future.
@t83714 to discuss with @pete

**Comment by t83714** [comment]
done with TerriaJs dev & test cluster & Magda dev cluster.
leave DGA cluster as it's (need client's help to update DNS record).
All keys are rotated and `catalog-manager-route53` was deleted as no longer required
