### ISSUE TITLE
Update magda to use ASGS 2021 boundaries and latest LGAs

### ISSUE THREAD

**Issue by steve9164** [magda-io/magda#3487]
## Description

Update magda to use ASGS 2021 boundaries and latest LGAs for indexing and rendering the region selector map in the frontend

## Acceptance Criteria

-   Newest versions of each current supported regions used in indexer and frontend

## Technical Notes

To be done in conjunction with TerriaJS/nationalmap#1219

## Out of Scope

- ?

### Updates 27th Jun 2024

Tasks:
- Update Magda region files used for indexer
- Update region mapping served from search api
- Update MVT tiles bucket & server (switch to tiles.magda.io)
- Add migration doc for v4.1.0

Instruction on how to generate region files & vector tiles can be found here:

https://github.com/magda-io/magda-regions/tree/main?tab=readme-ov-file#how-to-generate-default-region-files

**Comment by t83714** [comment]
closed via PR: https://github.com/magda-io/magda/pull/3544

Released via:
https://github.com/magda-io/magda/releases/tag/v4.1.0
