### ISSUE TITLE
As a government researcher, I want to see related file types to the one I selected

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#352]
Designs: https://invis.io/7HFAXNWBD

**Comment by AlexGilleran** [comment]
@tkeuneman I can't see any designs for file formats (same as types right) in that invision link.

**Comment by tkeuneman** [comment]
@AlexGilleran no designs just yet. @tristochief has a sketch that I did and we're waiting to see if this could get done in time before mocking up.

**Comment by AlexGilleran** [comment]
Closing this seeing as tristan's left and we're not going to get to it any time soon.
