### ISSUE TITLE
Visualisation sleuther improvements: column types

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#381]
- Make column type checking a little more formal
    + Use a proper validation library (needs to be extensible to support TerriaJS date formats)
    + Decide what to do with:
        * Empty cells
        * null, n/a or other null-like string in a numeric/time/date column
        * Other semi-numeric strings in a numeric column (like >10)
    + Add checking for known region types
        * Probably requires changes to TerriaJS (being able to tag a column as a specific region type) to be very useful
- Change fields from `fields: {[name: string]: {time: boolean, ...}}` to `fields: [{name: string, time: boolean, ...}]` (more for the GraphQL API than anything else, but better to change this earlier)
- Support other formats

**Comment by AlexGilleran** [comment]
Closing in favour of https://github.com/magda-io/magda/issues/1714
