### ISSUE TITLE
Expand the colour palette of DGA to more than just red

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#446]
User benefit is that we are able to show what's clickable and what's not, plus it's more aesthetically pleasing to have a range.

**Comment by AlexGilleran** [comment]
Expanded... to just purple. 🤷‍♂️ . 💜

**Comment by tkeuneman** [comment]
![image](https://user-images.githubusercontent.com/2201814/42484088-82cf36fc-8434-11e8-9f13-07c0050ca6f4.png)
