### ISSUE TITLE
Auto Zoom Support for KML datasource

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#461]
[PR 458](https://github.com/TerriaJS/magda/pull/458) upgraded the Preview Map to latest code and also make sure `zoomOnEnable` option is sent as `true` to the Preview Map module.
This makes the preview map function auto zoom to the smallest possible area that will cover the whole dataset rather than the default Australia map.

TerriaJs support the `zoomOnEnable` option very well [except KML data](https://github.com/TerriaJS/terriajs/issues/2547).
This issue is about modifying the `KmlCatalogItem.js` to auto-filled `this.rectangle` with correct instance after `doneLoading` is called.

This will guarantee correct execution of later `zoomTo` call.

**Comment by kring** [comment]
This is also tracked in TerriaJS/terriajs#2547.

**Comment by tkeuneman** [comment]
Affects 1.14% of datasets.

**Comment by AlexGilleran** [comment]
Closing, TerriaJS issue.
