### ISSUE TITLE
UX: broken link indicator

### ISSUE THREAD

**Issue by chloeleichen** [magda-io/magda#487]
<img width="1172" alt="screen shot 2018-02-20 at 4 22 18 pm" src="https://user-images.githubusercontent.com/7508939/36408564-3eeba800-165a-11e8-820e-a5e1189bdbd5.png">
We need a way to indicate if this link is broken (if it is maybe hide download button?) also need a way to hide broken link

**Comment by tkeuneman** [comment]
A visual way to say, hey, it's broken...we think, but you're free to test it out

**Comment by tkeuneman** [comment]
Design is here: https://www.figma.com/file/CxY8j1GBEqgcTyUftj7CERfd/Broken-link-indicator

**Comment by tkeuneman** [comment]
@philipgrimmett can you please replace the font awesome iconography to go with the custom work you've been doing thus far?

**Comment by aneesha09** [comment]
Closed - duplicate
