### ISSUE TITLE
New Dataset Page: Open Data Stories

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#511]
This issue about implementing the `Open Data Stories` section for the new dataset page:

![image](https://user-images.githubusercontent.com/674387/36655087-baeb52f2-1b14-11e8-8c0f-26fce4fe54bb.png)

**The section is part of New Dataset Page Design (Tracked as issue #500).**

**Created a new issue in order to track this functionality separately.**

## Overview

1. Each story item links to a new story page.
2. The content of each story will be manually created by human
3. Dataset page needs to select `Relevant` stories to be displayed 

More info is required regarding the requirements:
1> How to determine `Relevant` stories

**Comment by AlexGilleran** [comment]
@tkeuneman do we still need this?

**Comment by tkeuneman** [comment]
Closing it for now.
