### ISSUE TITLE
Visual adjustment of Recent Search Function to match new home page design

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#554]
The purpose of the issue is to separate visual adjustment task from issue #515 so that we can close #515 (and merge relevant PR) and tracking the remaining work here.
Requirements:
- Make sure recent search function matches design here: https://invis.io/CVG233EKXF7#/281956522_04_01_Homepage_saved_search

We may want to look at this issue once we made some progress on the new homepage design.

**Comment by AlexGilleran** [comment]
Done.
