### ISSUE TITLE
Dataset page: map should be faster and go to the region

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#643]
From users:
“The map takes a couple of seconds to spin around the globe, I mean, it’s nice, but take me straight to the specific region, don’t make me wait.”
Map: Oh hey! That’s cool. Right, the GNAF. It’s stuck on the world with no information loading. This is annoying. I don’t have time to play with that.

**Comment by AlexGilleran** [comment]
@tkeuneman So what's the recommendation here?

I for one like the globe spin - should we make sure it starts on Australia before it starts zooming maybe?

**Comment by AlexGilleran** [comment]
We've changed the starting region to be Australia.
