### ISSUE TITLE
Verify GeoJSON has a download file

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#644]
Check for file types like HTML etc and don't allow download for them
***********

From a user looking at Alpine Shire Council Garbage Collection:
Download displays the raw GeoJSON file, instead of downloading the file to my computer. That’s annoying. Do I have to copy and paste that instead of getting a file?

**Comment by AlexGilleran** [comment]
This is a hazardous one.

Essentially when people click the "Download" button it should always be a download. But a lot of the time naughty publishers set the download url as a link to their HTML portal, so people will come along, think they're downloading a ZIP or a CSV or something, then open it up and find `<!doctype html5><html><head>` etc.

So we probably need to fiddle the broken link sleuther into inspecting the mime type and changing download URLs that come back as `text/html` when their format is something else into access URLs.

**Comment by aneesha09** [comment]
Do we show access URL as a download button? We probably shouldn't
