### ISSUE TITLE
Dataset page: Open links in a new tab

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#649]
- [ ] Download, organisation and distribution links should open in another page, when accessed from the dataset page:

From a user:
“The download button should open in another tab, I don’t like using the back arrow. I want to read lots of similar things, so I would normally open more than one file (in the browser) and see what’s useful.”

**Comment by AlexGilleran** [comment]
Maybe download but I disagree with organisation and distribution, I'd start getting super annoyed if navigating around like that left a trail of old tabs behind. Especially given that it's easy to open something in a new tab but not to open a `target=_blank` link in an existing one.

Can't this user just use the middle mouse button? 🤔

**Comment by AlexGilleran** [comment]
We've made download/distribution open in another tab.
