### ISSUE TITLE
Zoom on preview map doesn't work for region-mapped CSV-GEO-AUs

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#651]
... at least that's what I think is the problem.

Point-based csv-geo-aus seem to work fine, even when not time series:
https://search.data.gov.au/dataset/ds-dga-2fe15526-9ea5-4432-9b49-d8821b40b67c/details

But region mapped:
https://search.data.gov.au/dataset/ds-dga-e29ef9ca-0d1a-47ec-9e9b-14a79a941511/details

**Comment by kring** [comment]
https://github.com/TerriaJS/terriajs/issues/920

**Comment by AlexGilleran** [comment]
> 2015

Ah jeez lol

**Comment by AlexGilleran** [comment]
Closing this seeing as it's a TerriaJS issue - making the starting location the same as NationalMap mostly fixes this for us at the moment.
