### ISSUE TITLE
Add AURIN CSW Connector

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#664]
AURIN has a lot of high-quality Australian datasets that would be nice to have... but they have their own API so we'll need a new connector for it: https://aurin.org.au/aurin-apis/datasets-available-in-the-openapi/

**Comment by lmoran** [comment]
Hi Alex, since the AURIN OpenAPI offers WFS and CSW endpoints, this should be fairly easy to implement.

**Comment by AlexGilleran** [comment]
Oh it has CSW? Excellent, that makes it trivial :D

**Comment by AlexGilleran** [comment]
On second thought, the OpenAPI needs a login and we don't have the ability to harvest protected endpoints yet so this is a bit bigger than trivial for now.

**Comment by lmoran** [comment]
Just a quick note: AURIN now has a [no-auth CSW endpoint](https://openapi.aurin.org.au/public/csw?request=GetCapabilities)

**Comment by AlexGilleran** [comment]
🎉 thanks @lmoran !

**Comment by aneesha09** [comment]
Copy paste some config and change the URL and name. Should be exactly the same as GA connector and other CSW ones.
