### ISSUE TITLE
Put 'Feedback' link in mobile footer only

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#719]
It goes to the feedback form that you see on desktop

**Comment by Garrison88** [comment]
In your CSS, you can use a media query (something like:)
`@media only screen and (min-width: 426px) {
  .feedback-link {
    display: none; 
  }
}`
to specify what will appear on a screen of a given size. So for your issue I would suggest setting the 'Feedback' link to 'display: none;' when 'min-width' is 426px, or whatever size means mobile to you

**Comment by steve9164** [comment]
Isn't present on master - might have disappeared in a merge?

**Comment by maxious** [comment]
#813 followed this to hide the button

**Comment by AlexGilleran** [comment]
All replaced with zenhub now
