### ISSUE TITLE
Publishers individual page: When I click on 'view all datasets from x', hide the * in the searchbar

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#732]
It confuses me with what's happening, although to be honest, it takes a while to realise the filter has been set.
![Screen Shot 2018-03-29 at 12.21.30 pm.png](https://images.zenhubusercontent.com/5a5b31cc4b5806bc2bc2a818/927aa53c-a4ee-45e6-af9b-64d14c4c3a92)

**Comment by aneesha09** [comment]
Closing as this is done
