### ISSUE TITLE
Performance Optimisation for Registry API

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#749]
A whole performance optimisation on registry API, to also solve the below problem.

It's possible for the Registry API to max out the CPU while doing very little
See this incident (if you can): https://app.google.stackdriver.com/incidents/0.kqbhybqnvvgj

Essentially the registry api was using its node's entire CPU - it was still responsible enough to survive livesness checks but slow enough that further-away stackdriver checks started to time out.

Restarting the pod fixed it.

Not sure what caused it or what the best mitigation is - perhaps more stringent liveness checks for now?

**Comment by t83714** [comment]
@AlexGilleran 
It seems change MAX_EVENTS in this line:
https://github.com/TerriaJS/magda/blob/79e9340fcd48d94bd3498de533f66ee785bf1061/magda-registry-api/src/main/scala/au/csiro/data61/magda/registry/WebHookActor.scala#L113
to 10 solve most my CPU usage problem locally.
Do you think it could be a potential fix?

**Comment by t83714** [comment]
Good idea! will do~

**Comment by aneesha09** [comment]
Do 8 points worth of optimisation :D

**Comment by mwu2018** [comment]
A quick search found that blocking code (Await) is used extensively, which should be avoid as it will exhaust resources.
