### ISSUE TITLE
Use case clarification on DGA CKAN

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#775]
From Marita:

As to your above query Tash (part 1):

1. Have added direct link instruction
2. There is ability to submit a use case, but only if you have an account and are logged in;
![image](https://user-images.githubusercontent.com/37681628/38398565-fad1900c-3987-11e8-9813-af64be0f00e2.png)
If you aren't logged in, it only allows you to read other peoples use cases; https://data.gov.au/showcase

We may need to update this section of the website to be more 'add your use case!' friendly (https://data.gov.au/showcase). I would like to have some info here for people who aren't logged in, i.e:

**Want to add a use case?** You must have an account and be logged in to submit a use case.

**What are use cases?** Use cases share how people have used data from data.gov.au in new and interesting ways. This can include the creation of apps, news articles, visualisations or ideas using data sets. Even if you've only used partial information from a data set, we (and the data set owner) would love to know what you discovered and how you used it. 

_(caveat to be included_) Use cases submitted to data.gov.au are currently approved for publication based on their context and appropriateness. 
Use cases created from resources found on data.gov.au have been developed, are operated and owned by third parties. data.gov.au does not endorse, approve, or certify the applications or the developers, nor does it make any representation or warranty that the information based on which the applications have been developed, is accurate, complete, or correct. 
We do not own responsibility for the regular update and maintenance of any applications created with data.gov.au resources. Any queries about applications or tools published need to be directed to the originator.

There should also be the ability to add a use case against a data set page, so that you're looking at your data set page, click on 'add use case' and it redirects to the 'create a use case' screen (https://data.gov.au/showcase/new). Forgive my terrible mock up, but to give you an idea:

![image](https://user-images.githubusercontent.com/37681628/38400017-470f54c8-3991-11e8-8c14-61e68af9f4f0.png)

I think the submit use case screen could be more comprehensive than what it is now;
![image](https://user-images.githubusercontent.com/37681628/38399283-d70001a4-398c-11e8-962d-4707ef607ee0.png)

Perhaps we should book in a workshop on this Tash? meanwhile, my ideas so far;

![image](https://user-images.githubusercontent.com/37681628/38399452-d63690ac-398d-11e8-97fc-fe544d330298.png)

**Comment by AlexGilleran** [comment]
@tkeuneman what should we do with this? Is there a resolution for this as an issue?

**Comment by tkeuneman** [comment]
It looks like this could be a ticket that DTA takes on afterwards, if they're so inclined. Do you agree @maxious or should we keep it closed?

**Comment by maxious** [comment]
I suspect this functionality is most relevant to public data portals like data.gov.au so keep closed for now.
