### ISSUE TITLE
Western Australian Shipwrecks isn't available when filtering by Western Australia

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#780]
This dataset: https://search.data.gov.au/dataset/ds-wa-bf006416-589e-4d9f-bc46-566ac564c405/details?q=Western%20Australian%20shipwrecks

Isn't available when searching for "shipwrecks" and filtering by WA:
https://search.data.gov.au/search?q=shipwrecks&regionId=5&regionType=STE

But it seems to have a viable polygon:
https://catalogue.data.wa.gov.au/api/3/action/package_show?id=bf006416-589e-4d9f-bc46-566ac564c405

**Comment by aneesha09** [comment]
Might be a symptom of a larger issue with search so we want to fix it

**Comment by aneesha09** [comment]
Timeboxed to 2 days because we don't know enough about it
