### ISSUE TITLE
Hamburger to X issues (QA)

### ISSUE THREAD

**Issue by steve9164** [magda-io/magda#838]
### Problem description
- Hamburger to X transition in slow on one tested iOS device every time and slow the first time on Android
- Align the X so that it's in the middle of the hamburger space (obviously when the hamburger is not present)
- X has longer lines than hamburger?

**Comment by tkeuneman** [comment]
[video demo.zip](https://github.com/TerriaJS/magda/files/1941033/video.demo.zip)

**Comment by AlexGilleran** [comment]
Looks ok to me now 👍

**Comment by tkeuneman** [comment]
😀
