### ISSUE TITLE
NaN returns! Occurs in date filter before search api responds

### ISSUE THREAD

**Issue by steve9164** [magda-io/magda#846]
### Problem description
- NaN appears for start and end date on date filter when the search hasn't loaded (i.e. progress bar shown)
- This is a bigger deal on dev than prod (since prod search api is pretty quick to respond)

### Problem reproduction steps
- Search for something on dev site
- Open date filter before search api responds

### Screenshot
- I am not fast enough to screenshot this

### Fix
Potential fixes:
1. Disable expanding filters before search api data arrives
1. Fill in some dates:
    * Could be hardcoded in frontend, or 
    * Fetch them separately like region information
        + Could send default state information for all filters at once instead of the `regions` endpoint

The first option sounds better to me.

**Comment by AlexGilleran** [comment]
Can't reproduce anymore
