### ISSUE TITLE
Privacy Policy Content has an incomplete sentence?

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#847]
QA feedback re: #516 

- make a complaint about our handling of your personal information. To protect your privacy and the privacy of others, we will need evidence of your identity before we can grant you access to information about you or change it.

See content above, it should start a new pragraph from `To protect`

- 3 links missing in section `Our obligations`

**Comment by aneesha09** [comment]
Hi @stephencannings - please see if you want to change the content of privacy policy inline with above
