### ISSUE TITLE
See full description button highlighted on mobile chrome

### ISSUE THREAD

**Issue by steve9164** [magda-io/magda#848]
### Problem description
The see full description button on Dataset page is highlighted on mobile chrome (Android), but not iOS.

### Problem reproduction steps
- Open a dataset with a long description on mobile chrome
- E.g. https://magda-dev.terria.io/dataset/ds-sa-790b37cf-9d9b-40d7-8e72-3e568de3d935/details?q=asbestos

**Comment by AlexGilleran** [comment]
@steve9164 is this still a problem? (no android phone)
