### ISSUE TITLE
No Logout link / Reset Password button

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#855]
### Problem description

No Logout link / Reset Password button

### Problem reproduction steps

Login to system. And you cannot find the buttons

### Screenshot / Design / File reference

![image](https://user-images.githubusercontent.com/674387/39170888-6c14bef4-47e0-11e8-82c7-41ecb6843236.png)

**Comment by AlexGilleran** [comment]
There's definitely a logout button now. Reset password not so much, but that's more the domain of whoever the user signs in with.
