### ISSUE TITLE
Search Filters: There should be feedback when no publisher/format found

### ISSUE THREAD

**Issue by sukhrajghuman** [magda-io/magda#856]
### Problem description

When I search for a publisher (also for Format and Location filters), if there is no publisher found for that particular query, there isn't any feedback for it. Maybe a little message below saying "no results found" would be good.

### Problem reproduction steps

Try typing in a publisher in the publisher drop down filter that doesn't exist

### Screenshot / Design / File reference

![image](https://user-images.githubusercontent.com/20184809/39170496-1f7d6b78-47df-11e8-8dd7-52d5d1c70c87.png)

### maybe have something like this:

![image](https://user-images.githubusercontent.com/20184809/39171074-128632b8-47e1-11e8-8002-7dcea24af355.png)

When the user clicks away, clear the search

**Comment by adamzerella** [comment]
Similar thing with `location`:
<img width="648" alt="screen shot 2018-04-24 at 4 59 20 pm" src="https://user-images.githubusercontent.com/1501560/39171021-e5a74b7e-47e0-11e8-9cbf-0cd547f76b1c.png">

and `format`: 
<img width="682" alt="screen shot 2018-04-24 at 4 59 36 pm" src="https://user-images.githubusercontent.com/1501560/39171034-ee28d22c-47e0-11e8-89af-a60bd4a42803.png">
