### ISSUE TITLE
Search filters: Add lines as per design

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#857]
### Problem description

There is a line that is missing between the filter and the X

### Problem reproduction steps

Reproducible in https://magda-dev.terria.io
![Screen Shot 2018-04-24 at 5.06.29 pm.png](https://images.zenhubusercontent.com/5a5b31cc4b5806bc2bc2a818/9ac3157a-e98e-47a6-869e-da4b57cb1fe1)

### Screenshot / Design / File reference

Design: https://projects.invisionapp.com/share/HVF8ORL7P#/screens/272862061_searchResults_01_02_03

**Comment by AlexGilleran** [comment]
Line is there now
