### ISSUE TITLE
As a person performing a search, I want to know that if I clear filters, I will be able to see way more results

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#868]
### Problem description
Right now, if someone has lots of search filters, they could get minimal results. We want to inform them that if they clear some, they'll get more results.

### Screenshot / Design / File reference
https://www.figma.com/file/B635GhKdrAZM4c1V94NBljUq/Smarter-Conversations?node-id=346%3A255

**Comment by AlexGilleran** [comment]
I tend to think we're now doing this with this design:

![image](https://user-images.githubusercontent.com/900555/42432848-02c30a28-8390-11e8-85dc-c49c31758f85.png)

So I'm closing it - @tkeuneman feel free to reopen :)

**Comment by tkeuneman** [comment]
Yes, the results show that filters are applied, and the 'clear all' button is present.
