### ISSUE TITLE
When I see no results for my keyword input, show me other things I can do

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#869]
### Problem description
When a customer currently gets a 'no results' message, it's not very helpful. We want to provide them with an option to suggest a new dataset, as well as view interesting datasets.

### Screenshot / Design / File reference
https://www.figma.com/file/B635GhKdrAZM4c1V94NBljUq/Smarter-Conversations?node-id=346%3A0

**Comment by AlexGilleran** [comment]
I think this is done for all intents and purposes - we now direct them to suggest a dataset, and we decided to get rid of the other interesting datasets bit because it was confusing.

**Comment by tkeuneman** [comment]
Yup. Eventually, they'll see interesting datasets.
