### ISSUE TITLE
Fix the publishers so that these 'D' related things are at the top

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#878]
### Problem description

The publishers should be alphabetised, yet you have two lone riders on top of the A's.

### Problem reproduction steps
Go to publishers on S.DGA

### Screenshot / Design / File reference
![Screen Shot 2018-04-27 at 2.40.01 pm.png](https://images.zenhubusercontent.com/5a5b31cc4b5806bc2bc2a818/de2a1a34-5081-40b5-a1f6-e76b0525e035)

**Comment by AlexGilleran** [comment]
Same as https://github.com/magda-io/magda/issues/1066
