### ISSUE TITLE
Front end npm start fails

### ISSUE THREAD

**Issue by chloeleichen** [magda-io/magda#887]
### Problem description
There seems to be an infinite loop with `npm start` in the front end, once you made a change it just builds, again and again, causing CSS files not served properly
### Problem reproduction steps
`lerna bootstrap` in magda then `npm start` in magda-web-client`, then make a change in `_variables.scss`

### Screenshot / Design / File reference
![screen shot 2018-04-30 at 11 09 03 am](https://user-images.githubusercontent.com/7508939/39412962-eaa16d64-4c66-11e8-9a63-0bf7cfccdc18.png)

**Comment by chloeleichen** [comment]
Actually, it does stop at last, but it seems to take 2 min to compile each change, it also no longer does hot reload

**Comment by AlexGilleran** [comment]
@t83714 this turned out to be because of a zombie node-sass process right?

**Comment by t83714** [comment]
@AlexGilleran 
Yes. At least for me, that's the issue. 
Hard to find out as somehow the zombie node-sass process won't be terminated even you close all terminal windows.
You will have to kill it manually

**Comment by AlexGilleran** [comment]
Haven't seen this for a while.
