### ISSUE TITLE
Create content for the homepage and about page based on user feedback

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#900]
### Problem description
- Who is this for?
- What does open data mean?
-  What's available

It looks like the first two questions need to be answered on the homepage.

**Comment by tkeuneman** [comment]
@sukhrajghuman I assigned this to you so that you can chase this up with Gordon. Hope that's ok as you've already spoken to him about it.

**Comment by sukhrajghuman** [comment]
yea that's cool. Gordon and Marita are away for next two weeks unfortunately :(
i'll come up with a few ideas before they come back and run it by them.

**Comment by sukhrajghuman** [comment]
handed over to stephen cannings
