### ISSUE TITLE
Which dept is the source and what do they do

### ISSUE THREAD

**Issue by sukhrajghuman** [magda-io/magda#901]
### Problem description
Which agency/department/company is the data coming from. What do they do?
We can make a link to the publisher as per the highlighted text in the screenshot below.

### Problem reproduction steps

When on the specific dataset details page, there isn't any link back into the publisher page for that particular dataset.

### Screenshot / Design / File reference

![image](https://user-images.githubusercontent.com/20184809/39556948-75eb3384-4ec7-11e8-91e9-6e65a627b099.png)

**Comment by AlexGilleran** [comment]
There is now :D
