### ISSUE TITLE
Files should be arranged by newest to oldest

### ISSUE THREAD

**Issue by sukhrajghuman** [magda-io/magda#903]
### Problem description
The files should be in order of most up to date to least. See screenshot below.

### Problem reproduction steps

https://search.data.gov.au/dataset/ds-sa-df2fb8ac-7756-4060-aea0-65080826ee4a/details?q=adelaide

### Screenshot / Design / File reference
![image](https://user-images.githubusercontent.com/20184809/39557340-2e619406-4eca-11e8-912f-793d067642d1.png)

**Comment by aneesha09** [comment]
We can live with this for now
