### ISSUE TITLE
Design: review map preview functionality

### ISSUE THREAD

**Issue by philipgrimmett** [magda-io/magda#942]
### Problem description

It is not clear whether the map previews in dataset pages are intended as fully functional Terria instances, or as stripped-back gateways to nationalmap.gov.au. Currently users have complete drag/zoom control in the map preview and are able view feature info by clicking on the map (full functionality), but are limited by the scale of the map.

### Problem reproduction steps

1. Navigate to a spatial dataset page (eg. Murray-Darling Basin Water Resource Plan Areas – Surface Water)
2. Map preview: click on map data

### Proposed solution

- Remove free pan/zoom functionality
- Set default zoom level to show Australia on load
- Display bounds box for map data with '+' icon to signal clickability (see screenshot)
- Apply min-width/height for bounds box (eg. 48*48)
- When user clicks on the bounds box they are zoomed in so that map data fits the frame
- Display zoom controls to allow users to toggle between the two zoom levels
- Display persistant 'Open in National Map' button

**Default view**
![screenshot 2018-05-08 16 45 00](https://user-images.githubusercontent.com/5292858/39741965-2a4b4ed4-52df-11e8-8de6-094f37b27a66.png)
**Zoomed to extent**
![screenshot 2018-05-08 16 40 32](https://user-images.githubusercontent.com/5292858/39741990-42765aa8-52df-11e8-955b-7d976b987b42.png)

**Comment by aneesha09** [comment]
Seems to be fixed. @philipgrimmett - Can you please verify and close it?

**Comment by philipgrimmett** [comment]
@t83714 I'm seeing some strange camera behaviour here, not sure if it's occurring across multiple datasets: https://dev.magda.io/dataset/ds-dga-fa0b0d71-b8b8-4af8-bc59-0b000ce0d5e4/details?q=*

There are some minor style changes required to ensure map UI components match the (configurable) MAGDA theme (eg. zoom, scale), documented here: #1673

The core map preview functionality is in place so I'll close this issue.
