### ISSUE TITLE
Organisations: Hide description text that says "A little information about my organization......"

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#947]
### Problem description
This is probably a legacy problem from CKAN. Let's hide this description because it doesn't add any value.

### Problem reproduction steps
![screen shot 2018-05-09 at 10 52 10 am](https://user-images.githubusercontent.com/2201814/39790084-2975057a-5377-11e8-9971-c61f99cc094c.png)

**Comment by mwu2018** [comment]
1). Query for "Consumer Affairs Victoria"
https://search.data.gov.au/api/v0/search/organisations?query=%22Consumer%20Affairs%20Victoria%22
Result:
{
    "query": "\"Consumer Affairs Victoria\"",
    "hitCount": 1,
    "organisations": [
        {
            "acronym": "CAV",
            "name": "Consumer Affairs Victoria",
            "identifier": "org-vic-03c18378-9678-48f2-83e6-1a8358fdde36",
            "description": "A little information about my organization...",
            "datasetCount": 18
        }
    ]
}
2). Query for source
 https://search.data.gov.au/api/v0/registry/records/org-vic-03c18378-9678-48f2-83e6-1a8358fdde36/aspects/source
Result:
{
    "id": "vic",
    "url": "https://www.data.vic.gov.au/data/api/3/action/organization_show?id=03c18378-9678-48f2-83e6-1a8358fdde36",
    "name": "Victoria Government",
    "type": "ckan-organization"
}

3). Go to the url from the result of 2)
https://www.data.vic.gov.au/data/api/3/action/organization_show?id=03c18378-9678-48f2-83e6-1a8358fdde36
"description": "A little information about my organization..." appears 19 times in the result page. So the problem originates from the external source.

**Comment by AlexGilleran** [comment]
Maybe we could put some extra code in the CKAN connector to filter it out? 🤔
