### ISSUE TITLE
Page goes blank if I download a file by clicking CMD + Click

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#948]
### Problem description
The page goes white if a user downloads a file by clicking Command + clicking on the download button

### Problem reproduction steps
1. Go to https://search.data.gov.au/dataset/ds-qld-3ea4f56a-3a23-4797-9cfa-c3d8cadcca94/details?q=water
2. Click on the download button while holding down Command or Option
3. Re-directs to a new portal, but when you hit the back button or go back to SDGA in the existing tab, it's white
Disclaimer: You do have to click around a bit and try to break it in order to replicate.

### Screenshot / Design / File reference
![screen shot 2018-05-09 at 11 01 57 am](https://user-images.githubusercontent.com/2201814/39790267-6ae3f600-5378-11e8-9148-2b2123ff7564.png)

**Comment by t83714** [comment]
Can't reproduce this issue. 
the white screen seems an intermittent `vwo` issue.

**Comment by AlexGilleran** [comment]
Yeah looks ok now.
