### ISSUE TITLE
Bug: Data quality minion doesn't score Data.json/ArcGIS sources correctly

### ISSUE THREAD

**Issue by maxious** [magda-io/magda#953]
eg. https://search.data.gov.au/dataset/ds-logan-http%3A%2F%2Fdata-logancity.opendata.arcgis.com%2Fdatasets%2Fbc07c26cb26d4b4880715f3e55ccdb17_0/details?q= has several machine readable formats like kml/csv and open licences - should be 4 stars but instead 2?

https://search.data.gov.au/api/v0/registry/records/ds-launceston-http%3A%2F%2Fopendata.launceston.tas.gov.au%2Fdatasets%2Fe4c2e98c2aed4be688ccf9e901deb84a_0?aspect=dcat-dataset-strings&optionalAspect=dcat-distribution-strings&optionalAspect=dataset-distributions&optionalAspect=temporal-coverage&dereference=true&optionalAspect=dataset-publisher&optionalAspect=source&optionalAspect=link-status&optionalAspect=dataset-quality-rating has Zero score except for a working link.

**Comment by AlexGilleran** [comment]
First one appears to have lost its license info :(.

Second one is affected by this: https://github.com/magda-io/magda/issues/897

**Comment by aneesha09** [comment]
Needs investigating
