### ISSUE TITLE
Give preference to results from state name entered as keyword 

### ISSUE THREAD

**Issue by tkeuneman** [magda-io/magda#983]
Make sure this includes acronyms (e.g. NSW).

For example - Boost results that feature NSW if a user searches for NSW.

**Comment by aneesha09** [comment]
@AlexGilleran to have a chat to @steve9164 to figure out where we are with this.

**Comment by aneesha09** [comment]
Two-thirds done. It would work now but some annoyances e.g. South boosts things in SA. Work out how to change fields/analysers in the Elastic Search API.

**Comment by t83714** [comment]
As sprint 20, issues for the MVP of the agriculture dept. instance is higher priority now.
I will come back to this issue once those are completed.

**Comment by t83714** [comment]
Summarise the problem & my findings today:
- The requested feature requires recognising region keywords in user input. The problems are:
  - Most query / search features of `elasticsearch` are designed to analyse a keywords in indexed data. Not the other way round (analyse possible matches). This is also relevant hard / slow in traditional database.
  -  We have limited capability to customise tokeniser. i.e. There is no programming way to define a tokeniser that can `cut` the following user input `I love south australia` into desired tokens:
      - `I`
      - `love`
      - `south australia`
i.e. there is no easy way to establish the relationship between `south` & `australia` without cutting into 2 tokens.

My solution is to create the following analysis process to analyse user input:
- start with a `Whitespace` Tokeniser (`cut` by any whitespaces) and it will produce the followings:
  - `I`
  - `love`
  - `south`
  - `australia`
- filter with a `lowercase` token filter
- filter with a `Synonym Graph Token Filter` (See [here](https://github.com/magda-io/magda/blob/issue/983-alt/magda-elastic-search/regionSynonyms.txt) for synonym dictionary I created): as it `creates a "graph token stream" during processing`, token `south` & `australia` will be linked together and converted into new token `ste/4`

Here are two tests to show the results:
```
POST regions22/_analyze
{
  "analyzer": "region_synonym_graph_for_search",
  "text": "I love south australia"
}
```
We will get tokens:
```
{
  "tokens": [
    {
      "token": "i",
      "start_offset": 0,
      "end_offset": 1,
      "type": "word",
      "position": 0
    },
    {
      "token": "love",
      "start_offset": 2,
      "end_offset": 6,
      "type": "word",
      "position": 1
    },
    {
      "token": "ste/4",
      "start_offset": 7,
      "end_offset": 22,
      "type": "SYNONYM",
      "position": 2
    }
  ]
}
``` 
and 
```
POST regions22/_analyze
{
  "analyzer": "region_synonym_graph_for_search",
  "text": "I love south"
}
```
will produce tokens:
```
{
  "tokens": [
    {
      "token": "i",
      "start_offset": 0,
      "end_offset": 1,
      "type": "word",
      "position": 0
    },
    {
      "token": "love",
      "start_offset": 2,
      "end_offset": 6,
      "type": "word",
      "position": 1
    },
    {
      "token": "south",
      "start_offset": 7,
      "end_offset": 12,
      "type": "word",
      "position": 2
    }
  ]
}
```  
You can tell:
- for 1st test, user input `I love south australia` has been converted into `I`, `love` & `ste/4` (region id)
- and for the 2nd test, user input `I love south` will not trigger any matches.

You can replicate my result using my branch `issue/983-alt` and it will create a new region index `regions22` with relevant analyser.
