### ISSUE TITLE
Stop search filtering out distribution-less datasets

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#990]
### Problem description
Historically the search has always filtered out datasets without distributions because they didn't seem useful, but it turns out that there are exceptions to this - it'd be best if we just stopped doing it.

This should be a pretty trivial scala change in `indexer` - find the line that does this filter and delete it, then remove any test cases for it.

**Comment by maxious** [comment]
examples: https://data.gov.au/dataset?unpublished=True

**Comment by steve9164** [comment]
Datasets with 0 distributions SQL:
```sql
SELECT r.recordid, r.name, jsonb_array_length(ds_ra.data->'distributions') AS distributions FROM records r JOIN recordaspects ds_ra ON r.recordid = ds_ra.recordid WHERE ds_ra.aspectid='dataset-distributions' ORDER BY distributions ASC LIMIT 50;
```
Results:

|                  recordid                   |                                                  name                                                  | distributions |
|---------------------------------------------|--------------------------------------------------------------------------------------------------------|---------------|
| ds-dga-c134af07-6fba-4bda-9a2a-77346b070df9 | Australian Securities and Investments Commission FOI Disclosure Log                                    |             0|
| ds-dga-16bbb736-0728-46d1-b629-c2bf719610a7 | Department of Education FOI Disclosure Log                                                             |             0|
| ds-dga-455e5dce-670d-46b6-8007-18aee43d80a3 | Australian Institute of Criminology FOI Disclosure Log                                                 |             0|
| ds-dga-f3f0c58a-e086-4183-b2fc-820783e1236c | Australian Skills Quality Authority FOI Disclosure Log                                                 |             0|
| ds-dga-dd906d44-70b7-4cca-bc45-0d3779c8eb3d | Comcare FOI Disclosure Log                                                                             |             0|
| ds-dga-6fa8a41d-2069-468d-9ab8-d02d5557e248 | Department of Employment FOI Disclosure Log                                                            |             0|
| ds-dga-2ffeeeca-4c23-4d27-b931-f331d38b1395 | Airservices Australia FOI Disclosure Log                                                               |             0|
| ds-dga-3d6daaa0-2b62-427b-ab52-3a3df405bda4 | Australian Federal Police FOI Disclosure Log                                                           |             0|
| ds-dga-b22c557f-7ee7-447e-ac07-d2a54cc85d2e | Australian Organ and Tissue Donation and Transplantation Authority FOI Disclosure Log                  |             0|
| ds-dga-f8cf270b-4276-4311-bd95-2272ffb0d82a | Australian Research Council FOI Disclosure Log                                                         |             0|
| ds-dga-24693745-b57f-435b-8461-aa5689d7ba93 | Australian War Memorial FOI Disclosure Log                                                             |             0|
| ds-dga-f0451ede-0c1a-4e05-bf1b-121ddc98b18f | Civil Aviation Safety Authority FOI Disclosure Log                                                     |             0|
| ds-dga-a4891f36-08b0-448d-ab79-6f95496850af | Commonwealth Superannuation Corporation FOI Disclosure Log                                             |             0|
| ds-dga-19af4827-b03d-4de6-acc8-a0451cebe191 | Department of Defence FOI Disclosure Log                                                               |             0|
| ds-dga-7345a645-a313-4c12-9003-ca0cde4fea3e | Surface Water Entitlement Locations Gippsland Southern Rural Water 20141218                            |             0|
| ds-dga-12b23c19-9bc4-482d-98b4-8fcbb7e914b1 | 2007 Community Attitudes to Privacy survey data                                                        |             0|
| ds-dga-192d4120-23f6-4f8f-acd8-4cd11d8f3481 | Australian Broadcasting Corporation FOI Disclosure Log                                                 |             0|
| ds-dga-016a5d2c-e7ec-45d2-b4b3-e00b641bbce1 | Australian Crime Commission FOI Disclosure Log                                                         |             0|
| ds-dga-4332512b-aa0a-4dc7-894c-66115a8ddee2 | Australian Law Reform Commission FOI Disclosure Log                                                    |             0|
| ds-dga-a56d0b78-89af-400d-9320-42551c0bd1bd | Australian National University FOI Disclosure Log                                                      |             0|
| ds-dga-359886fd-4238-4c0f-821c-d26e40ae7335 | Australian Radiation Protection and Nuclear Safety Agency FOI Disclosure Log                           |             0|
| ds-dga-c590aefd-3231-4b94-83fc-f6c3d29d957f | Australian Prudential Regulation Authority FOI Disclosure Log                                          |             0|
| ds-dga-ae5cd817-f92c-4710-bab5-848771a0b976 | Australian Sports Commission FOI Disclosure Log                                                        |             0|
| ds-dga-91afb480-ce5d-44e6-b5b6-ca3779047377 | Australian Transport Safety Bureau FOI Disclosure Log                                                  |             0|
| ds-dga-b0415dd8-91c1-4d52-ba09-397f01ff6c8a | Bureau of Meteorology FOI Disclosure Log                                                               |             0|
| ds-dga-98c1c078-1b33-4f4f-8c8c-474a88df15f1 | Cancer Australia FOI Disclosure Log                                                                    |             0|
| ds-dga-5d6148b1-60ad-4682-88b2-d738ea8d33e0 | Clean Energy Regulator FOI Disclosure Log                                                              |             0|
| ds-dga-43742eb5-4781-4672-ae85-5dbfe5ee3e21 | ComSuper FOI Disclosure Log                                                                            |             0|
| ds-dga-1d7c10f3-1b6a-41c8-91d0-3774c48baaa2 | Department of Communications FOI Disclosure Log                                                        |             0|
| ds-dga-9a25ab61-2187-4e9c-9667-f32e30ca6768 | CSIRO FOI Disclosure Log                                                                               |             0|
| ds-dga-61924c21-853e-4152-b56b-c578fc727b70 | NSW Office of Water GW licence extract linked to spatial locations for NorthandSouthSydney v3 13032014 |             0|
| ds-dga-99596257-1ab4-4873-af9b-99884e71483b | Surface Water Economic Entitlements GIP 20141219                                                       |             0|
| ds-dga-6190e88a-bfd6-425e-b4a5-cc14d76af32a | GLO Preliminary Assessment Extent                                                                      |             0|
| ds-dga-4f324834-1566-4900-ad59-bbcae4d57faa | 2013 Community Attitudes to Privacy survey data                                                        |             0|
